### ISSUE TITLE
WeakSet

### ISSUE THREAD

**Issue by arv** [compat-table/compat-table#100]
I think only V8 with --harmony supports WeakSet but it would be good to have it in the table for completeness sake.

**Comment by kangax** [comment]
Does a test like this look right?

``` js
try {
  var set = new WeakSet(), obj = { };
  set.add(obj);
  return set.has(obj) && set.size === 1;
}
catch(err) {
  return false;
}
```

**Comment by kangax** [comment]
Hm, looks like Chrome fails this due to lack of `size`.

**Comment by arv** [comment]
WeakMaps and WeakSets have no size. The following should be sufficient:

``` js
try {
  var set = new WeakSet(), obj = { };
  set.add(obj);
  return set.has(obj);
}
catch(err) {
  return false;
}
```

**Comment by kangax** [comment]
@arv thanks!
