### ISSUE TITLE
Array.prototype.@@iterator on IOS9-10

### ISSUE THREAD

**Issue by olanod** [compat-table/compat-table#1005]
Not sure if it belongs here, but the table says IOS 9 and 10 supports `Array.prototype[Symbol.iterator]` but the devices I tested it with didn't support it.

**Comment by afmenez** [comment]
Looking at data-es6.js, this feature shows as "true" for Safari 9, but there's no mention of iOS 9 or iOS 10.  In environments.json, iOS9 is defined as "equals Safari 9" and iOS10 as "equals Safari 10".  I don't have a Mac to test Safari 9/10 (or an iPhone to test iOS 9/10), but if the implementation really diverged we may need to revise this definition.

It is possible to add ios9:false,ios10:false to data-es6.json, but this can become a maintenance nightmare on each new Safari/iOS release.

@olanod, is this the only divergence on the results for iOS/Safari?

**Comment by chicoxyzzy** [comment]
> It is possible to add ios9:false,ios10:false to data-es6.json, but this can become a maintenance nightmare on each new Safari/iOS release.

overriding should work OK even if `equals` field is presented

**Comment by zloirock** [comment]
100% ES6 tests passed in desktop / mobile Safari 10. If you can show how to reproduce your issue - please, do it.

**Comment by chicoxyzzy** [comment]
I have 100% as well on mobile Safari 10
