### ISSUE TITLE
add Array.prototype.includes

### ISSUE THREAD

**Issue by chharvey** [compat-table/compat-table#1011]
let arr = [1,2,3]
    arr.includes(2) // true

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Comment by ljharb** [comment]
This ES2016 feature is already [here](http://kangax.github.io/compat-table/es2016plus)

**Comment by chharvey** [comment]
oops I missed it on that page. Thanks for pointing it out.

I assumed `Array.prototype.includes` would be under category [Array.prototype methods](http://kangax.github.io/compat-table/es6/#test-Array.prototype_methods). Any chance of adding it to that?

**Comment by chicoxyzzy** [comment]
@chharvey it's not a part of ES6/ES2015
