### ISSUE TITLE
Update Intl tests

### ISSUE THREAD

**Issue by zbraniecki** [compat-table/compat-table#1032]
Intl tests are pretty outdated at this point:

* Year ago we added `Intl.getCanonicalLocales` API
* This year we added `Intl.DateTimeFormat.prototype.formatToParts`
* This year we landed https://github.com/tc39/ecma402/pull/84 which changes constructor semantics

At the moment, kangax compat-table does not recognize the new APIs and does show the updated constructor semantics as missing features.

**Comment by afmenez** [comment]
Notice that Firefox 54 (Nightly) has already updated the constructor semantics and is now failing the 3 Collator tests, which it shouldn't.

**Comment by afmenez** [comment]
I believe issue #930 is related to this one.

**Comment by zbraniecki** [comment]
`Intl.PluralRules` has been merged into ECMAScript 2018. `hourCycle` for DateTimeFormat as well. DateTimeFormat and NumberFormat `formatToParts` are in 2018 as well.

There are also three small normative changes like adding new options to the options bag and clipping allowed Date input into DateTimeFormat.

Also, `Intl.Segmenter` is in stage 3, `Intl.ListFormat` advanced to Stage 3 today, `Intl.RelativeTimeFormat` and `Intl.Locale` likely will tomorrow.

You can find some notes from ECMA402 last meeting here: https://github.com/tc39/ecma402/blob/master/meetings/agenda-2018-01-19.md

It would be nice to finally see this reflected in the table.

**Comment by chicoxyzzy** [comment]
Duplicate of #467
