### ISSUE TITLE
What about separate test for ES6 Symbols ?

### ISSUE THREAD

**Issue by Yaffle** [compat-table/compat-table#104]
Seems, Chrome supports it:

var object = {};
var symbol = Symbol();
object[symbol] = 42;
Object.getOwnPropertyNames(object).length === 0 && object[symbol] === 42;

P.S.
although, 
http://jsperf.com/symbol-vs-weakmap/3
may be i write a bad test or Chrome's support is not very good.

**Comment by kangax** [comment]
Can you please make PR
