### ISSUE TITLE
Intl tests are probably incorrect

### ISSUE THREAD

**Issue by chicoxyzzy** [compat-table/compat-table#1044]
Latest Chrome Canary, Firefox Nightly and WebKit Nightly fail on following test:
- calling Collator with Collator instance throws error
- calling NumberFormat with NumberFormat instance throws error
- calling DateTimeFormat with DateTimeFormat instance throws error

It looks like spec has changed and we should update / delete these tests

**Comment by claudepache** [comment]
The spec has indeed changed between v1.0 and v2.0. If we remove or correct those tests (as we should), we should also update the links so that they don't point to the obsolete 1st edition anymore.

**Comment by afmenez** [comment]
We should probably update all the results for these tests, since browsers that passed before may fail now.

**Comment by chicoxyzzy** [comment]
other Intl-related issues:
https://github.com/kangax/compat-table/issues/1032
https://github.com/kangax/compat-table/issues/930
https://github.com/kangax/compat-table/issues/926
https://github.com/kangax/compat-table/issues/900
https://github.com/kangax/compat-table/issues/467

**Comment by chicoxyzzy** [comment]
Some of these issues are duplicates. I will manage that as soon as I can (probably tommorrow).

**Comment by claudepache** [comment]
This issue is a duplicate of #900... although the web-reality and the specced behaviours of those constructors are still disagreeing in a semi-unrelated way as of v3 (per https://github.com/tc39/ecma402/issues/57)

**Comment by chicoxyzzy** [comment]
We'll back to this after March TC39 meeting

**Comment by afmenez** [comment]
How about disabling the 3 tests while they are not updated, to avoid showing false negatives?

**Comment by chicoxyzzy** [comment]
we can do it as a temporary solution

**Comment by afmenez** [comment]
What is the best way to disable a test?

**Comment by chicoxyzzy** [comment]
I think we can just comment them and add a comment that these tests should be updated

**Comment by chicoxyzzy** [comment]
Duplicate of #467
