### ISSUE TITLE
Consolidate items on esintl tab

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#1062]
There are some categories on esintl tab that I believe should be consolidated:
-Intl.Collator + Intl.Collator.prototype.compare + Intl.Collator.prototype.resolvedOptions
-Date.prototype.toLocaleString + Date.prototype.toLocaleDateString + Date.prototype.toLocaleTimeString

Most of these have only a single test, and I believe grouping them will simplify the table.

I will work on a patch if nobody opposes.

**Comment by ljharb** [comment]
Wouldn't it be better to add more thorough subtests?

**Comment by afmenez** [comment]
Yes, it would be great!  But it is not the point of this patch. ;)

**Comment by ljharb** [comment]
Right, but this patch makes "adding more subtests" harder; so I'm not sure it's worth consolidating the tests in the meantime.

**Comment by afmenez** [comment]
Closing due to opposition by @ljharb .
