### ISSUE TITLE
ES6 Iterator support

### ISSUE THREAD

**Issue by codebox** [compat-table/compat-table#107]
The ES6 table says that Iterators aren't supported in any version of Firefox, however my own testing in Firefox 23 indicates that they are supported.

**Comment by kangax** [comment]
This is the test we use to check `Iterator` support:

``` js
test(function () {
  if (typeof Symbol !== 'function' || typeof Symbol.iterator !== 'symbol') {
    return false;
  }

  var iterator = {
    next: function () { return { done: true, value: 1 }; }
  };
  var iterable = {};
  iterable[Symbol.iterator] = iterator;

  try {
    eval('for (var a of iterable) { return a === 1; }');
  } catch (e) {
    return false;
  }
}());
```

Is there something wrong with it? What did you use in your testing?

**Comment by codebox** [comment]
How about this? I tested it in Firefox 23 and it passes, fails in Chrome as it should

``` js
test(function () {
  var obj = { key: 'value' };
  var it = Iterator(obj);

  try {
    return eval("(function(){for(var pair of it){return pair[0] === 'key' && pair[1] === 'value'}}())");
  } catch (e) {
    return false;
  }
}());
```

**Comment by codebox** [comment]
I think there are a couple of problems with the test you have - the **Symbol** variable is undefined in my version of Firefox (and is apparently not a prerequisite for Iterators because they do work), also the eval expression gives an error because it contains a return statement which is not enclosed in a function.
