### ISSUE TITLE
Edge 15 nested parameters destructuring with default fail

### ISSUE THREAD

**Issue by klimashkin** [compat-table/compat-table#1076]
Hi! That arrow function can't be created in Edge 15.15063
```
var test = (param, {deep = {}}) => {}; // Error: Expected ':'
```

**Comment by ljharb** [comment]
You have to surround the destructuring pattern in parentheses.

**Comment by klimashkin** [comment]
@ljharb Not sure if I understood you correctly

Do you mean `var test = (param, ({deep = {}})) => {}` ?

**Comment by ljharb** [comment]
Apologies, I deleted my comment because I'd misread.

**Comment by martinsuchan** [comment]
Edge 15 also supports Shared Memory & Atomics behind flag, see:
https://blogs.windows.com/msedgedev/2017/04/20/improved-javascript-performance-webassembly-shared-memory/
