### ISSUE TITLE
Why not jQuery?

### ISSUE THREAD

**Issue by tiye** [compat-table/compat-table#109]
[master.js](https://github.com/kangax/es5-compat-table/blob/gh-pages/master.js) looks really crazy to me.
Why not using jQuery or Zepto for manipulating the DOM?

**Comment by Yaffle** [comment]
@jiyinyiyong , you need to love DOM API, after that jquery will looks really crazy

**Comment by tiye** [comment]
@Yaffle DOM API might be nice, but it's probably hard to for maintaining and cooperating.

**Comment by ghost** [comment]
@jiyinyiyong  The master.js file isn't that complex. Just take 10 minutes to read all the way though it. By the way, some people, like myself, prefer not to use jQuery.
