### ISSUE TITLE
Remove String trim-left/right from non-standard?

### ISSUE THREAD

**Issue by adam77** [compat-table/compat-table#1096]
As they're being tracked in esnext. Confusing to track them in two places.

**Comment by adam77** [comment]
Also, how about removing the rows from non-standard for which no tracked engine has support?

**Comment by ljharb** [comment]
Which rows are those? Be sure you're checking all platforms, even obsolete ones.

**Comment by ljharb** [comment]
As to the OP, I'm fine moving all the nonstandard data for trim* to esnext.

**Comment by adam77** [comment]
\__count\__
\__present\__

appear to be No in all columns (for example)

i'm guessing FF has dropped a bunch of obsolete es4 era stuff.

**Comment by ljharb** [comment]
Sorry, was mobile previously. 

It seems that `count` should be true for Firefox 4, but the browser isn't in the list for some reason. I think that we should go back and add a browser entry such that every row *does* have a Yes in it - I don't think we should remove a historical reference to a feature, even if it no longer applies.

**Comment by adam77** [comment]
that's of historical interest but is it any use to anyone?

**Comment by ljharb** [comment]
It's of use to me whenever I have to fix bugs in the es5-shim.

Also, it might potentially be of use to one person in 100 years, which means it's worth keeping forever anyways.

**Comment by afmenez** [comment]
I have already proposed #1025, so we would still keep historical reference but would not pollute the table.

**Comment by afmenez** [comment]
I already merged the removal on #1097, but I can't close this one.
