### ISSUE TITLE
Remove SIMD from esnext

### ISSUE THREAD

**Issue by skcc75** [compat-table/compat-table#1103]
>SIMD.js has been taken out of active development in TC39 and removed from Stage 3, and is not being pursued by web browsers for implementation. SIMD operations exposed to the web are under active development within WebAssembly, with operations based on the SIMD.js operations. With WebAssembly in advanced development or shipping in multiple browsers, it seems like an adequate vehicle to subsume asm.js use cases, which are judged to be the broader cases. Although some developers have expressed interest in using SIMD.js outside of asm.js, implementers have found that implementing and optimizing for this case reliably creates a lot of complexity, and have made the decision to focus instead on delivering WebAssembly and SIMD instructions in WASM.

https://github.com/tc39/ecmascript_simd

**Comment by afmenez** [comment]
I am not sure if this should be moved from esnext->non-standard tab or simply moved to another category inside esnext.  As I understand the proposal was not rejected, but postponed.

**Comment by chicoxyzzy** [comment]
https://github.com/rwaldron/tc39-notes/blob/1b0b9ac1429fe91160be8e84f6ba21df23557068/es8/2017-03/mar-21.md#conclusionresolution-10

**Comment by afmenez** [comment]
So it stays in Stage 3 for now, and will eventually be moved to the non-standard tab. :)

**Comment by ljharb** [comment]
Nothing should change here until https://github.com/tc39/proposals/issues/46#issuecomment-301794868 changes.

**Comment by chicoxyzzy** [comment]
I think we can comment out SIMD for now and add a note about its withdrawal.

**Comment by ljharb** [comment]
It's now stage 1/inactive in the proposals repo; it's probably still useful to leave it active.

**Comment by afmenez** [comment]
I'll write a patch tomorrow.

**Comment by afmenez** [comment]
Can't this one be closed now that the patch was merged?

**Comment by ljharb** [comment]
Closed in #1117
