### ISSUE TITLE
Split Opera results from Chrome

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#1126]
Opera is one of the many browsers derived from the Chrome engine, but it is the only one attached to it in the result tables.   I believe Opera results should be at least split, and maybe even dropped from the tables.

**Comment by ljharb** [comment]
All the browsers derived from the Chrome engine should have the results linked - are there even any examples where that conceptual link (in the actual result data) doesn't hold true?

**Comment by afmenez** [comment]
I am not talking about the "equals" tag.  I mean that the the title for the Chrome columns say "Chrome, Opera".  I believe it should say just Chrome.
My proposal is to drop Opera >= 15 altogether, since it is now just a wrapper to the Chrome engine.  We don't have any other "wrapper browser" in the table, and I don't believe we should have.
Note that I am not proposing to drop Opera <= 12, nor Opera Mini (which isn't there yet but should be).

**Comment by ljharb** [comment]
ah. I don't think we should drop Opera altogether - I think it should continue to be its own column.

As for other "wrapper browsers", my expectation is that the ones not included in the table are because not enough people care about testing in them; not because they're "wrappers".

**Comment by chicoxyzzy** [comment]
We should split Opera from Chrome because it’s release date and retire date are completely wrong now

**Comment by ljharb** [comment]
Totally on board with that, but I want to preserve pre-Blink Opera results.
