### ISSUE TITLE
ECMAScript 2017 released

### ISSUE THREAD

**Issue by mgetzbw** [compat-table/compat-table#1132]
[ECMAScript 2017](https://www.ecma-international.org/publications/standards/Ecma-262.htm) was officially release this morning, the table should reflect that the features within are no longer draft or vNext.

**Comment by ljharb** [comment]
<sub>It's ES2017; nobody calls it by edition number post ES6 (and maybe ES7/ES2016)</sub>

**Comment by afmenez** [comment]
I have already fixed the links to the final spec on #1130, I don't believe there's anything else to do on this issue.

**Comment by ljharb** [comment]
Yes, I just reviewed the data and it looks correct to me.

@mgetzbw please note; a feature is in ES the instant it hits stage 4 and lands in the spec on github; the publication year doesn't change much - so we're usually pretty far ahead of the publication :-)

**Comment by mgetzbw** [comment]
@ljharb I know, but I have co-workers that see the word 'Draft' and run away screaming 😉

**Comment by ljharb** [comment]
@mgetzbw time to educate them :-) it's a living standard.
