### ISSUE TITLE
Sticky thead works only in Safari

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#1139]
The current implementation of the position:sticky workaround (on master.js) works only in Safari:
```
  if (thead.css('position') === "-webkit-sticky") {
    // Remove floatThead when native position:sticky is usable.
    // Currently, only Safari (which floatThead incidentally does not support),
    // and its -webkit-sticky prefix, works correctly with <thead>.
    $.fn.floatThead = function() { return this };
  }
```
It should check also for the actual "sticky" value, which is implemented on Edge 16 preview and will possibly be implemented in other browsers in the future.

**Comment by afmenez** [comment]
Would this be correct/enough?
```
-if (thead.css('position') === "-webkit-sticky") {
+if ((thead.css('position') === "sticky") || (thead.css('position') === "-webkit-sticky")) {
```
The .css seems to be correct already.

**Comment by ljharb** [comment]
that seems reasonable to me

**Comment by afmenez** [comment]
Yes, that was what I thought.  But this breaks the buggy implementations on Chrome and Firefox. :(

**Comment by ljharb** [comment]
Is there any way to feature-detect the bug, instead of checking the CSS values?

**Comment by afmenez** [comment]
That's the problem exactly.  Both Chrome and Firefox support "sticky", but are buggy for `<thead>`. :(
