### ISSUE TITLE
How to view `obsolete: very`?

### ISSUE THREAD

**Issue by Schweinepriester** [compat-table/compat-table#1157]
Hi,

first of all: Thanks for this great resource :)

I was searching for info about Android Browser 4.4(.4) - I know it's Chromium 33 - and older, but don't seem to be able to show those, using "Show obsolete platforms"?

Neither Android nor this old version of Chrome.
Is there a way?

I did see #1104 and if it's not possible to view old Android or at least Chrome 33 anymore, I'd like to preemptively voice that I think it's sadly too early to hide them, as Android 4.4 is embarrassingly still at 16 % (https://developer.android.com/about/dashboards/index.html).

Thanks again! :)

**Comment by afmenez** [comment]
Android 4.4 uses Google Chrome by default, which is regularly updated.  The version available today is Chrome 61.

**Comment by Schweinepriester** [comment]
The WebView sadly doesn't.

**Comment by afmenez** [comment]
I believe you are mistaken.  From the [FAQ](https://developer.chrome.com/multidevice/webview/overview): "The WebView in Android L can be updated via the Play Store, so you need to check the latest version on the device under App Settings."
You can get the updated WebView component from the [Play Store](https://play.google.com/store/apps/details?id=com.google.android.webview).

**Comment by afmenez** [comment]
Hum, I see your point now.  Only Android L and above can be updated, not K.  I will write a patch later to fix this.

**Comment by Schweinepriester** [comment]
I wish I were, Android L is 5.X though: <https://en.wikipedia.org/wiki/Android_version_history#Android_5.0_Lollipop_.28API_21.29>

I don't have an Android 4.4(.4) device, but I could provide you screenshots on Monday (if nobody fires up an emulator to check).

EDIT: Oh, never mind, I saw your comment - thank you very much :)

**Comment by afmenez** [comment]
The patch was merged, I believe this issue can be closed.

**Comment by Schweinepriester** [comment]
Yes, thanks :)

**Comment by ljharb** [comment]
The original question imo is still valid - how can one view "very obsolete" data on the webpage?

**Comment by afmenez** [comment]
As it is implemented now, you can't.  The data is simply ignored during the page generation and is not available to the js.
And I believe we can't put it in, the page is already too slow as it is with the current limited set of data.  It may become viable after #1145 and #1147 are fixed.
