### ISSUE TITLE
Returning duplicates from the Proxy trap [[OwnPropertyKeys]] now throws

### ISSUE THREAD

**Issue by evilpie** [compat-table/compat-table#1164]
See https://github.com/tc39/ecma262/pull/833. This invalidates the 2017 misc test: Proxy "ownKeys" handler, duplicate keys for non-extensible targets.

**Comment by afmenez** [comment]
Yep, the test is now failing for Firefox 57 Beta, which implements the new behavior.

**Comment by afmenez** [comment]
There are many engines implementing the current tested behavior, so maybe this test should be moved to the non-standard tab before implementing the correct test?

**Comment by ljharb** [comment]
I would expect that we might want to invert the results, but moving it could work too.

**Comment by afmenez** [comment]
The new behavior is now implemented by most major browsers (Firefox, Chrome, Safari Beta and Edge Beta).

**Comment by ljharb** [comment]
Let's move the old test to "non-standard", and add the new test in its place.
