### ISSUE TITLE
V8 TCO compatibility data is out of date

### ISSUE THREAD

**Issue by amirouche** [compat-table/compat-table#1166]
Héllo,

I can't reproduce the results regarding TCO even with the harmony flag using current unstable Chrome dubbed 62.0.3198.0.

@chicoxyzzy can you help? Which version of Chrome did you use? Which OS?

**Comment by chicoxyzzy** [comment]
Hi @amirouche 

It seems that TCO was moved to `--harmony-tailcalls` in February and [was removed from V8 completely since July](https://bugs.chromium.org/p/v8/issues/detail?id=4698#c69)

We should update compat-table data.
Thank you for your report!

**Comment by afmenez** [comment]
How to add two notes for different versions of the same browser?  I tried to do it like this:

```
      res: {
        tr: {
          val: "flagged",
          note_id: 'tr-tco',
          note_html: 'Requires the <code>properTailCalls</code> compile option.'
        },
        tr: {
          val: "flagged2",
          note_id: 'tr-tco2',
          note_html: 'Requires the <code>--harmony-tailcalls</code> run option.'
        },
        babel: false,
        typescript: typescript.fallthrough,
        firefox2: false,
        chrome51: "flagged",
        chrome58: "flagged2",
        chrome62: false,
        safari10: true,
        xs6: true,
        duktape2_0: true,
      },
```
But versions 58-61, which should have the second note, appear blank.

**Comment by amirouche** [comment]
@afmenez can you tell me what's the exact command you use to run `google-chrome` to have tco, please?

**Comment by afmenez** [comment]
I didn't, I am using the data from the bugtracker to update the table.

**Comment by afmenez** [comment]
Actually, after further investigation I believe it is the `--js-flags="--harmony-tailcalls"` flag.

**Comment by chicoxyzzy** [comment]
I believe that TCO was available with `--harmony` flag before [February 11](https://bugs.chromium.org/p/v8/issues/detail?id=4698#c67) (if I understand correctly what "implication" mean)

**Comment by afmenez** [comment]
Yes, that's what is in my patch #1168.  I mentioned just the current flag here because I believed it was what @amirouche meant.

**Comment by chicoxyzzy** [comment]
@afmenez `--harmony-tailcalls` was also removed in latest V8 versions as I mentioned in https://github.com/kangax/compat-table/issues/1166#issuecomment-327424255

**Comment by afmenez** [comment]
Yes, it is in the patch #1168 too.

**Comment by chicoxyzzy** [comment]
I haven't seen it yet. Will check it now!
