### ISSUE TITLE
Promise.prototype.finally has been available behind a flag since chrome 61

### ISSUE THREAD

**Issue by gsathya** [compat-table/compat-table#1170]

**Comment by afmenez** [comment]
What is the flag?  I tried `--harmony`, but the feature is not enabled.

**Comment by gsathya** [comment]
> What is the flag? 

`--harmony-promise-finally`

> I tried --harmony, but the feature is not enabled.

I just [staged it](https://github.com/v8/v8/commit/4de946d96ddf2e4f7b033c9b5e763dada8fb5d61). `--harmony` should work in the next canary release. 
EDIT: It's on 63.0.3212.0 canary release (on Mac at least)

**Comment by afmenez** [comment]
Thanks, updated #1168 to address this one too.

**Comment by afmenez** [comment]
Hey @gsathya, are there other flags for specific Harmony features?  I am trying to document them all on #1169, but don't know where to find this information...

**Comment by gsathya** [comment]
> Hey @gsathya, are there other flags for specific Harmony features?

https://cs.chromium.org/chromium/src/v8/src/flag-definitions.h?q=flag-defi&sq=package:chromium&l=192

The more stable, staged features (all available behind `--harmony` flag) are:
https://cs.chromium.org/chromium/src/v8/src/flag-definitions.h?q=flag-defi&sq=package:chromium&l=210 (defined by 

Thinking more about this, maybe we shouldn't mark the individually flagged features on the compat table because they are still in development and may not even work. It might be better to just mark the staged features as 'flagged'.

**Comment by afmenez** [comment]
So you mean that for this feature (Promise.prototype.finally) we should have just "flagged" for Chrome 61 and "--harmony" for Chrome 63?  And remove the notes for the TCO and SIMD flags too?

**Comment by gsathya** [comment]
> So you mean that for this feature (Promise.prototype.finally) we should have just "flagged" for Chrome 61 and "--harmony" for Chrome 63? And remove the notes for the TCO and SIMD flags too?

I only see "flagged" on the compat table. Are you planning on adding a "--harmony" state to the table as well? That might be confusing to users. 

I would suggest --
(a)  "No" for features behind individual `--harmony-*` flags.
(b) "Flag" for features available behind `--harmony` flag.
(c) "Yes" for features available unflagged.

I would change Promise.prototype.finally as "Flag" for Chrome 63 and "No" for Chrome 61, 62.

**Comment by afmenez** [comment]
Yes, I was, and the patch was merged before I could see this.  I am OK with your suggestion, and I will do a follow up patch, see the discussion on #1169.
In the meanwhile, I believe this issue can be closed, since the respective patch was merged.
