### ISSUE TITLE
SIMD implementation in Chrome seems to be removed

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#1172]
The note on the SIMD features on the esnext table says they are available in Chrome via the `--js-flags="--harmony-simd"` flag, but this is not working on Chrome 61.  Was the feature removed or did the flag change?  When?

**Comment by chicoxyzzy** [comment]
SIMD proposal was suspended recently. It's on stage 1 now and there are no plans to push it forward in near future.

**Comment by afmenez** [comment]
Yep, I know that and I updated the esnext page myself not long ago.  What I meant is that the note on the esnext page currently says it is supported behind a flag on Chrome 61, but it isn't.  I intend to fix that, but first I need to know when the feature was removed.

**Comment by afmenez** [comment]
According to the bug tracker, it was removed on Feb 14, 2017:
https://bugs.chromium.org/p/v8/issues/detail?id=4124#c147

Which means Chrome 58 according to the branch calendar:
http://www.chromium.org/developers/calendar

**Comment by ljharb** [comment]
Closed in #1178.
