### ISSUE TITLE
Feature marked incorrectly for Safari 10

### ISSUE THREAD

**Issue by ssilve1989** [compat-table/compat-table#1175]
`babel-preset-env`, which uses this table, ends up incorrectly excluding a plugin `transform-es2015-block-scoping` when targeting support of Safari 10.

I believe this is due to the features `const` and `let` under bindings being marked completed but there is a bug in Safari 10, [shown here](https://bugs.webkit.org/show_bug.cgi?id=159270) where the following 
```javascript
{
  let a = 3
}

let a = 3
```
throws `SyntaxError: Can't create duplicate variable that shadows a global property: 'a'`

References babel/babel-preset-env#411

**Comment by afmenez** [comment]
@chicoxyzzy, by reading the description I thought it was about writing two new subtests (for `let` and `const`), but it is now marked as "test code bug".  Do you mean the existing tests should be changed to fail on the Safari buggy implementation?

**Comment by ljharb** [comment]
Separate tests are good, but yes, absolutely a test should always fail on a buggy implementation.

**Comment by afmenez** [comment]
I was not able to cram this issue on the existing subtests, so I added new ones.

**Comment by ssilve1989** [comment]
Just upgraded to Safari Version 11.0 (12604.1.38.1.7) today and safari **still** throws this error with that code snippet :rage:

**Comment by afmenez** [comment]
Yep, my patch #1183 is not merged yet.

**Comment by afmenez** [comment]
I believe one of the reasons for not merging is that I haven't actually run the new tests on Safari.  Could you do that and comment on the PR if it actually solves your issue?

**Comment by ssilve1989** [comment]
So I ran the build and opened up Safari to view it. In the Safari 11 column, it lists `No` for `scope-shadow-resolution` and `scope-shadow-resolution (strict mode)`. However in the `Current Browser` column they show as passing. The current browser, that i was running it on was `Safari Version 11.0 (12604.1.38.1.7)`, and indeed it **does** work on that version of 11. I'm not sure why it didn't 13 days ago when I first upgraded Safari, its the same exact version as then

**Comment by afmenez** [comment]
Yes, the result columns are hard-coded, only the "current browser" column is live.  I marked it `no` for Safari because you said it should not work.  I can change it to `yes`, but some questions remain:
- How about Safari 10.1 and earlier?
- If they work too, is the test incorrect?

**Comment by ssilve1989** [comment]
So since I've upgraded my MacOS, the only easy way I have to test lower Safari versions is through [crossbrowsertesting.com](crossbrowsertesting.com), and through that, Safari 10 is actually showing as passing on `Version 10.1.2 (12603.3.8)`, and that **is** accurate as running the snippet in that console doesn't throw an exception. Unfortunately I did not record the build number of the Version 10 that did throw the error so I can't tell if this is the same and something bizarre is happening, or it's a different build where the fix was implemented.

**Comment by afmenez** [comment]
I am starting to believe the test is incomplete.  Did you check the code I implemented to see if it should triggers the problem you refer to?

**Comment by ssilve1989** [comment]
The code for your tests looks fine. What's troubling is that running code like that, or the snippet at the start of this thread, in the Safari 10 version crossbrowsertesting.com supplies, works without any errors. So I'm thinking the version 10 I had used where the error did occur must have been a different build or patch version, but I no longer have access to find out what that version was.

So in short, as far as I can tell, shadow scoping is now not throwing errors and working as expected in Safari 10+

**Comment by afmenez** [comment]
OK, I'll fix that in my PR.  But I believe you mean 10.1+, right?

**Comment by ssilve1989** [comment]
Correct, 10.1.2 to be precise

**Comment by afmenez** [comment]
OK, I updated the patch to reflect 10.1 results.  Now the only version where this makes a difference is 10.0.  Can you test it to check if this test is still necessary?

**Comment by ssilve1989** [comment]
I don't currently have access to that version. It seems crossbrowsertesting.com only supplies the latest version that comes with a particular MacOS.

**Comment by afmenez** [comment]
Since #1183 was merged, I believe this issue can now be closed.

**Comment by wessberg** [comment]
@afmenez, I would suggest that we reopen this issue. #1183 was merged, but in it, only Safari 10 and not 10.1 was marked as having this bug. See https://github.com/kangax/compat-table/blob/gh-pages/data-es6.js#L561.

However, Safari 10.1 too has the bug. I’ve made a simple repro: http://safari_10_1_repro.surge.sh/ that includes the following piece of code:

```javascript
function func(a = 1) {
    for (let a = 2; ;) {
        break;
    }
}
func();
```

I’ve tested it in Safari 10.1 and can confirm that it doesn’t work. We get `SyntaxError: Cannot declare a let variable twice ‘a’`.

<img width="1296" alt="Screen Shot 2019-06-23 at 12 38 38 PM" src="https://user-images.githubusercontent.com/20454213/59975035-dcf15980-95b3-11e9-976d-c56a5266f2a1.png">

**Comment by chicoxyzzy** [comment]
Is it Safari 10.1.0?

**Comment by wessberg** [comment]
I tested in Safari 10.1.2 (12603.3.8).
So, at least the range from Safari 10.0 to 10.1.2 is having the bug.
