### ISSUE TITLE
Duplicate note_html for node.js

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#1189]
Both node 0.10 and 0.12 have the same note_html.  I believe it can be removed from 0.12.

**Comment by ljharb** [comment]
For reference, what is the note and why can it be removed from 0.12?

**Comment by afmenez** [comment]
`"note_html": "Flagged features have to be enabled via <code>--harmony</code> or <code>--es_staging</code> flag"`

It is the same note on 0.10 and 0.12, so I believe it is not needed on 0.12 because it is inherited from 0.10 anyway.  I did test it, and removing it from 0.12 makes no difference on the generated html.

**Comment by afmenez** [comment]
On a related note, odd versios of node.js are supposed to be the "development branch" and are not considered stable for production.  Do we need to keep them in the tables?  Currently we have 5.0, 7.0 and 7.6.  If we want to have all the versions, there are several missing.  But I believe we should remove these 3.

**Comment by ljharb** [comment]
`--es-staging` is not a valid flag in 0.10; it was added in 0.11 - it seems like the 0.10 note is incorrect.

For historical reasons, we should have 5.0, 5 latest, 7.0, 7 latest, and any 5 or 7 versions that had notable changes.

**Comment by afmenez** [comment]
OK, all addressed on #1190

**Comment by afmenez** [comment]
Done.
