### ISSUE TITLE
Consider adding an ES5 identifier test

### ISSUE THREAD

**Issue by mathiasbynens** [compat-table/compat-table#12]
E.g. [`a\u200c\u200d`](http://mothereff.in/js-variables#a%5Cu200c%5Cu200d) is a [valid identifier](http://mathiasbynens.be/notes/javascript-identifiers) as per ES5, but not all browsers/engines support it (yet).

This can easily be tested as follows:

``` js
var supportsZeroWidth = (function() {
    try {
        Function('var a\u200c\u200d');
        return true;
    } catch(e) { }
}());
```

`supportsZeroWidth` will be true if ZWJ and ZWNJ characters are supported in `IdentifierPart`, else `undefined` (which is falsy).

**Comment by kangax** [comment]
Are U+200C and U+200D (from all the allowed characters) the only ones that fail in some clients at the moment?

**Comment by kangax** [comment]
Not significant, but maybe:

``` js
var supportsZeroWidth = (function() {
  try {
    return eval('_\u200c\u200d = true');
  } catch(e) { }
}());
```

**Comment by mathiasbynens** [comment]
U+200C and U+200D are the only two characters that haven’t changed categories since Unicode 3.0 yet still fail in multiple browsers, even though they’re explicitly mentioned in the spec. (Btw, I fixed the U+200C/U+200D bugs in [V8](http://code.google.com/p/v8/source/detail?r=10800) and [WebKit/JavaScriptCore](http://trac.webkit.org/changeset/108742) now.)

It’s funny, really; most browsers that claimed full ES5-compliance months ago still fail on a simple [`var a\u200c\u200d`](http://mothereff.in/js-variables#a%5Cu200c%5Cu200d) — only stable versions of IE9 and Firefox 10 get it right.

Other than those characters, the spec mentions the Unicode categories that are allowed in `IdentifierStart` and `IdentifierPart` — but that’s a separate issue. Of course, not all JavaScript engines have the same level of Unicode support yet. As the spec says:

> ECMAScript implementations may recognize identifier characters defined in later editions of the Unicode Standard. If portability is a concern, programmers should only employ identifier characters defined in Unicode 3.0.

So no, there are lots of other identifiers that fail in multiple browsers at the moment, but these are one of the few characters that are explicitly mentioned in the ES5 spec (not deferred to a Unicode spec) yet they still fail. See the list of links to browser bugs in [my post](http://mathiasbynens.be/notes/javascript-identifiers) — only Firefox nightly seems to have full Unicode 6.1.0 support.

Nice simplification of the feature test!

**Comment by kangax** [comment]
I see... So if we only consider Unicode 3.0, do implementations fare well with all the allowed characters?

**Comment by mathiasbynens** [comment]
Other than the ZWJ and ZWNJ characters, I haven’t found a problem with non-Unicode 3.0 chars in any browser. As I tested some seriously crazy symbols, I doubt there are any. (I mostly tested browser implementations, though.)

The variable name validator might be useful when testing this further, as it will show a warning if a given identifier would not be allowed if the Unicode 3 database would’ve been used instead of the Unicode 6.1 database. E.g. http://mothereff.in/js-variables#%5Cu0cf1

**Comment by kangax** [comment]
Yeah. I'm surprised [test262](http://test262.ecmascript.org/) didn't catch that. Need to check if they test for it.

**Comment by kangax** [comment]
Added. Thanks.
