### ISSUE TITLE
Hide IE11 from es2016+ and next tabs by default?

### ISSUE THREAD

**Issue by chicoxyzzy** [compat-table/compat-table#1205]
Does it make sense to show IE11 in es2016+ and next tabs by default?

**Comment by ljharb** [comment]
Absolutely. Old browsers are the *primary reason* imo for the compat table, and many people still support down to IE 8 and 9.

**Comment by afmenez** [comment]
IE8 and IE9 are not on es6, es2016+ and esnext tabs.  And I believe this is good.

**Comment by ljharb** [comment]
I think that browsers with zero support in a given tab shouldn't be shown on that tab by default, certainly - but I think it'd be useful to be able to toggle showing them - but I think it's a good idea for the *last* browser with zero support to be shown by default.
