### ISSUE TITLE
RegExp.prototype.flags test failing in recent Node versions

### ISSUE THREAD

**Issue by williamkapke** [compat-table/compat-table#1208]
The test isn't dynamic enough to account for new flags.

```js
function(){
  // RegExp.prototype.flags -> Get -> [[Get]]
  var get = [];
  var p = new Proxy({}, { get: function(o, k) { get.push(k); return o[k]; }});
  Object.getOwnPropertyDescriptor(RegExp.prototype, 'flags').get.call(p);
  return get + '' === "global,ignoreCase,multiline,unicode,sticky";
}
```

In Node with `--harmony` flag or Node's Nightly- `get` has additional values and yields:
>  global,ignoreCase,multiline,dotAll,unicode,sticky

Initially reported here:
https://github.com/nodejs/node/issues/16449

**Comment by ljharb** [comment]
ah, because of `dotAll`. Good catch!

**Comment by ljharb** [comment]
(also see #1135)
