### ISSUE TITLE
Update traceur

### ISSUE THREAD

**Issue by Alxandr** [compat-table/compat-table#121]
Traceur supports a lot of the features the table states it doesn't. Especially if you enable the experimental features. Things like destruction for instance is implemented already, and experimental support for `let` and `const` is in place (though it might kill your performance).

**Comment by kangax** [comment]
Thanks for the update! If you can send a PR, that would be awesome.

**Comment by Alxandr** [comment]
Not sure how to run the tests to generate the table.

**Comment by kangax** [comment]
`node build.js` will update html based on data-es6.js

**Comment by johnjbarton** [comment]
Are the table entries created by hand? Or is there some way that `traceur` is run to verify the entries? (A lot of the traceur column is not correct).

**Comment by kangax** [comment]
@johnjbarton Updated by hand. A PR with updated results is always welcome, of course!

**Comment by johnjbarton** [comment]
PR #156 generated by running Traceur over the tests in data-es6.js, using the code in https://github.com/google/traceur-compiler/pull/1164

**Comment by johnjbarton** [comment]
Well this should have been fixed by #156, but the online table is not updated.

**Comment by kangax** [comment]
Updated
