### ISSUE TITLE
ES6: Remove "Structs (binary data storage)"

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#122]
Typed objects and StructType aren't in the latest ES6 spec, and none of the tracked platforms implement it.

**Comment by kangax** [comment]
Thanks! PR is welcome, or I'll get to it sometime soonish (currently travelling)

**Comment by webbedspace** [comment]
Q: If I were to do a PR, is it expected I fill in the table row with accurate browser data myself?

**Comment by kangax** [comment]
If you can. But in this case, it's just a removal, so nothing to fill, right?
