### ISSUE TITLE
es2016+: test about duplicate keys in Proxy ownKeys handler went mixed with some “(ES Draft Style)” nonstandard feature recently removed from FF 

### ISSUE THREAD

**Issue by claudepache** [compat-table/compat-table#1224]
Something strange happened.

![es-2016-strangeness](https://user-images.githubusercontent.com/3309637/32808960-54bdbc20-c995-11e7-9cca-3735d64cc668.png)

**Comment by chicoxyzzy** [comment]
cc @afmenez

**Comment by afmenez** [comment]
Yep, this is due to #1164, Firefox 57 implements the new behavior.

**Comment by chicoxyzzy** [comment]
If this is an old behavior we definitely should move that test to non-standard tab

**Comment by afmenez** [comment]
Do you mean now or when the test is fixed?

**Comment by ljharb** [comment]
The test for the old behavior, with its results, should probably move to the nonstandard tab or be deleted.

The new behavior should be tested on the standard tab.

**Comment by claudepache** [comment]
@afmenez The label “(ES draft style)” attached to the current test and results is confusing; it sounds like it is the one from the latest draft, whereas it is *precisely* not (since https://github.com/tc39/ecma262/pull/833 was merged). The current test and results should be marked with “(ES 2017 semantics)”, or “(old semantics)”, or “(ES 2017 old semantics)”, or whatever.

**Comment by afmenez** [comment]
We can improve the title when we fix the test or move it to the non-standard tab.

**Comment by claudepache** [comment]
@afmenez There is no need to wait for a test update in order to correct the wording. I’ve just gone ahead and quickly fixed the cause of my confusion that leads me to open the current Issue, with PR #1225.
