### ISSUE TITLE
ES6: add __proto__

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#123]
As summarised [here](http://esdiscuss.org/topic/proxy-proto-is-not-getprototypeof#content-7), there are about three things to check:
- `__proto__` is present as a getter/setter property on Object.prototype:

```
var desc = Object.getOwnPropertyDescriptor(Object.prototype,"__proto__");
return desc && "get" in desc && "set" in desc && desc.configurable && !desc.enumerable;
```
- `{ __proto__ : [] } instanceof Array` is true (currently Chrome and Firefox support this)
- `{ "__proto__" : [] } instanceof Array` is false (currently Chrome and Firefox do NOT support this, as it relies on treating quoted object keys as computed properties)

**Comment by kangax** [comment]
Oh right, **proto** is now part of ES6... :) If you could PR, that would be great. Or I'll get to it sometime soon (currently travelling).

**Comment by webbedspace** [comment]
It's come to my attention there's a mistake in that post: it should actually say that `{ ["__proto__"] : [] } instanceof Array` is false, instead of just `"__proto__"`.
