### ISSUE TITLE
Array.indexOf / lastIndexOf in IE7

### ISSUE THREAD

**Issue by NN---** [compat-table/compat-table#1240]
It is not supported although stated as supported.
https://www.keithcirkel.co.uk/compat-table/es5/

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

**Comment by ljharb** [comment]
I'm not sure what that website is; this compat table is https://kangax.github.io/compat-table/es5/

Either way, both of them indicate that indexOf/lastIndexOf only exists in IE 9+, so I'm not sure where you see "stated as supported".

**Comment by NN---** [comment]
If you check 'Show obsolete browsers?'  then under IE7 everything is green and not red.
I guess that page doesn't work correctly.

Thanks.

**Comment by ljharb** [comment]
Hmm, for me, it shows up red (and there's no IE7 at all)
<img width="764" alt="screen shot 2018-01-03 at 12 00 19 am" src="https://user-images.githubusercontent.com/45469/34512769-329b5260-f019-11e7-97c2-a7eed6fb60a8.png">

Can you share a screenshot of what you're seeing?

**Comment by zloirock** [comment]
@NN--- this repo is not a correct place where you should report your issue. Seems https://www.keithcirkel.co.uk/compat-table/es5/ is a very old (~3 years old) fork of this site. As @ljharb wrote, this compat table site is https://kangax.github.io/compat-table/es5/. In this compat table, IE7 marked as "very obsolete" and does not displayed even with "show obsolete platforms" flag.

**Comment by ljharb** [comment]
@NN--- note that i see an IE 7 column, all red, on the other link.

@keithamus - any chance you could take down your outdated mirror? :-)

**Comment by NN---** [comment]
Thank you all.

**Comment by keithamus** [comment]
@ljharb Sorry about this. I've taken it down. This is an unfortunate side effect of forking repos with a the only branch being `gh-pages` - it automatically sets up a pages site for the fork
