### ISSUE TITLE
Gratipay widget fails to load, blocking the whole page from loading for ~10s

### ISSUE THREAD

**Issue by nwoltman** [compat-table/compat-table#1242]
It seems like there's something wrong with the DNS for https://grtp.co. The JS for the widget tries to load for about 10 seconds before timing out (it's been like this for at least a couple days). Since [the widget code](https://github.com/kangax/compat-table/blob/gh-pages/es6/skeleton.html#L73) uses a synchronous <script> tag, the whole page is blocked from loading until the request times out. Would it be possible to change it to an `async` script and have it still work once Gratipay fixes their DNS issue?

**Comment by ljharb** [comment]
(#328 may be related)

**Comment by nwoltman** [comment]
Turns out that Gratipay no longer exists: https://gratipay.news/the-end-cbfba8f50981 😢

**Comment by ljharb** [comment]
Sounds like we just need a PR to remove the widget then :-)
