### ISSUE TITLE
Shared Mem and Atomics disabled in Safari to mitigate Meltdown and Spectre

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#1245]
Shared Memory and Atomics were disabled in Safari to mitigate the Meltdown and Spectre CPU bugs, according to this blog:
https://webkit.org/blog/8048/what-spectre-and-meltdown-mean-for-webkit/

On #1243, I updated the situation for Firefox and Chrome, but I have no access to Safari to test which versions are affected.

**Comment by chicoxyzzy** [comment]
I have SAB disabled in both Safari 11.0.3 (13604.5.6) (shipped with macOS 10.13.3 Beta 5) and Safari Technology Preview Release 47 (Safari 11.1, WebKit 13605.1.19.1)

Atomics are still enabled in both

**Comment by chicoxyzzy** [comment]
I'll create PR
