### ISSUE TITLE
Add async-generators & for-await syntax

### ISSUE THREAD

**Issue by rektide** [compat-table/compat-table#1270]
The [Async Iteration Proposal](https://github.com/tc39/proposal-async-iteration) adds async-generator functions and a new for-await syntax. This proposal has recently been moved to [Stage 4 acceptance](https://github.com/tc39/proposals/commit/a41dccc91675f41c65dee354c18c19946d6f2f45), and has shipped in Chrome 63 and Firefox 57.

Please kindly add tests for this amazing wonderful new feature.

**Comment by zloirock** [comment]
http://kangax.github.io/compat-table/es2016plus/#test-Asynchronous_Iterators ?
