### ISSUE TITLE
Remove `document.write(…)`, and never use it again

### ISSUE THREAD

**Issue by ExE-Boss** [compat-table/compat-table#1289]
I found 3 instances of [`document.write(…)`](https://developer.mozilla.org/docs/Web/API/Document/write) that have to be removed due to this resulting in horribly slow page loads (in the range of **MINUTES**) which results [in horrible interactivity problems](https://philipwalton.com/articles/why-web-developers-need-to-care-about-interactivity/).

Even assigning to [`Element.innerHTML`](https://developer.mozilla.org/docs/Web/API/Element/innerHTML) or [`Element.outerHTML`](https://developer.mozilla.org/docs/Web/API/Element/outerHTML) is faster, despite accomplishing the same thing, as those don’t need to synchronously block parsing the web page, unlike the aforementioned `document.write(…)`.

https://github.com/kangax/compat-table/blob/03303b06c337d84e7810505898d2c154214bf059/es6/skeleton.html#L143 https://github.com/kangax/compat-table/blob/7db11bd87d2a51e7562a869d3533af01b00d5f4c/master.js#L20 https://github.com/kangax/compat-table/blob/7db11bd87d2a51e7562a869d3533af01b00d5f4c/master.js#L23

There’s also this which gets printed to the console for every invocation of the `test(…)` on every page, because it’s called from inside a table:
<pre>An unbalanced tree was written using document.write() causing
data from the network to be reparsed. For more information
<a href="https://developer.mozilla.org/docs/Web/HTML/Optimizing_your_pages_for_speculative_parsing">https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing</a></pre>

**Comment by Perelandric** [comment]
This could use some testing in old browsers. I don't have my VMs set up right now, but if no one else can do it, I'll get to it this week.
