### ISSUE TITLE
The jquery.floatThead script causes an error in IE6

### ISSUE THREAD

**Issue by Perelandric** [compat-table/compat-table#1309]
According to the [script's page](http://mkoryak.github.io/floatThead/), it supports: *"**Internet Exploder 8+**, FireFox 10+ or Chrome15+"*.

The ES5 compatibility table doesn't really need it, so maybe it should be removed. This will also require edits to master.js where that plugin is accessed.

**Comment by ljharb** [comment]
the ES6 table still needs to work in the same browsers the ES5 table does, because of polyfills.

**Comment by Perelandric** [comment]
The edits to master.js would only prevent calls to the plugin when it isn't loaded. It would still work for the other tables. We could also use IE conditional comments to conditionally load the plugin for IE8+ and non-IE browsers.

**Comment by Perelandric** [comment]
...however, I spoke too soon. The error seems to be coming from this test: https://github.com/kangax/compat-table/blob/255c25f8bda2e732b0a755e56cf03916339aa1b3/data-es5.js#L1140-L1143

It should be in a try/catch.

**Comment by ljharb** [comment]
Indeed - shouldn’t all the tests be in a try catch?

**Comment by Perelandric** [comment]
Only the ones that potentially throw. Some only test for the existence of something, or for the side effect of a function.

**Comment by Perelandric** [comment]
Though I guess it wouldn't hurt if they all did.

**Comment by Perelandric** [comment]
Closing this since the plugin was a red herring, and isn't proving to be an actual issue just yet. This IE6 error is addressed in pull request: #1310

**Comment by mkoryak** [comment]
I'm curious If floatthead works in ie6 (on your site, with polyfills). Does anyone here know?

Sorry for replying to a closed issue.
