### ISSUE TITLE
let/const temporal dead zone

### ISSUE THREAD

**Issue by rwaldron** [compat-table/compat-table#131]
One of the important things that sets ES6 let/const lexical bindings apart from some existing implementations is that those bindings _cannot_ be accessed in a way that calls their internal [[Get]] at anytime prior to declaration, eg:

``` js
function f() {
  console.log(a); // 2. throws, because `a` isn't declared yet.
}
f(); // <-- 1. calls
let a = 1; // never reached because #2 threw an exception
```

This is the same for `const` bindings.

**Comment by rwaldron** [comment]
Any implementation missing these semantics is **wrong** and should be updated to a nasty red "No". As far as I know, only IE11 does this right.

**Comment by webbedspace** [comment]
FWIW the dead zone test correctly throws in Chrome 35 (but not Firefox <= 30).

(I also feel like incorrect or partial implementations should have a slightly different colour than the red shade used for "missing", but that's for another issue.)

**Comment by rwaldron** [comment]
@webbedspace sure, but it's still broken: 

<img src="http://i.gyazo.com/a5c17a7129d34bc9ad0f857d00990868.png">

`let` and `const` aren't restricted to strict mode (the term "extended mode" appears to refer to "strict mode" + experimental JS)
