### ISSUE TITLE
Remove WebKit Nightly from results

### ISSUE THREAD

**Issue by chicoxyzzy** [compat-table/compat-table#1311]
Nobody's testing WebKit Nightly builds since October 4, 2017. I tried to install it couple times but failed to run it. I think presence of WebKit Nightly is useless and could be even misleading. Should we remove it from table?

**Comment by ljharb** [comment]
I was able to download and run r232513 just fine, and the compat table loaded fine in it. I think we should update the results rather than removing it.

**Comment by chicoxyzzy** [comment]
Nice! I'll try again when WK Nightly will be available for macOS Mojave if no one else will add results before builds for Mojave will be available
