### ISSUE TITLE
RegExp "u" flag anomaly in Safari

### ISSUE THREAD

**Issue by nkalvi** [compat-table/compat-table#1322]
I encountered a problem when testing examples from [You-Dont-Know-JS](https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20%26%20beyond/ch2.md#unicode-flag): 

while 
```js
/^.-clef/u.test( "𝄞-clef" );		// true
```
returned `true` as expected in Chrome and Firefox, it returned `false` in Safari.

Safari is marked as 'passing' for this feature in _compat-table_, based on the following test:
```js
"return 𠮷".match(/^.$/u)[0].length === 2;
```

While Safari 'passes' with this test, it fails to return `3` for the length for the following expression (because it doesn't find a match):
```js
"𠮷x".match(/^.x$/u)[0].length
```
Both Chrome and Firefox return the expected length.

I'm wondering whether the test should be improved and Safari should be marked as 'partially passing'.
BTW, Safari Technology Preview Release 59 (Safari 12.0, WebKit 13606.1.21) also fails.

**Comment by ljharb** [comment]
cc @mathiasbynens @msaboff

**Comment by mathiasbynens** [comment]
This seems to be a JSC bug.

```
$ eshost -e '/^.-clef/u.test("\u{1D11E}-clef")'
#### Chakra
true

#### JavaScriptCore
false

#### V8 --harmony
true

#### SpiderMonkey
true

#### V8
true

#### xs
true
```

I initially assumed it tried to create a range between `.` and `c` (because of `.-c`) but it seems like the `^.` is what’s causing it:

```
$ eshost -e '/^.clef/u.test("\u{1D11E}clef")'
#### SpiderMonkey
true

#### JavaScriptCore
false

#### Chakra
true

#### V8
true

#### V8 --harmony
true

#### xs
true
```

Without the `^` before the `.`, JSC behaves as expected:

```
$ eshost -e '/.clef/u.test("\u{1D11E}clef")'
#### SpiderMonkey
true

#### Chakra
true

#### JavaScriptCore
true

#### V8
true

#### V8 --harmony
true

#### xs
true
```

cc @leobalter who has been working on expanding Test262 RegExp tests lately.

**Comment by nkalvi** [comment]
@mathiasbynens Thanks. Would you be able to point this bug to the developers? They'll certainly take it into consideration if you did 😺.

**Comment by mathiasbynens** [comment]
@msaboff is CC’d on this thread, and works on JSC. I’m sure he’ll take a look :)

**Comment by leobalter** [comment]
This error is persisting for every codePoint from 0x10000 to 0x10FFFF in JSC. It fails to match `u` codePoints using `^.`. I still want to gather more info for this.

This loop might help. Replace the `if (!r)` with `if (r)` if running on JSC, otherwise it will print everything.

```js
for (let i = 0x10000; i < 0x10FFFF; i++ ) {
  let r = /^.x/u.test(`${String.fromCodePoint(i)}x`);
  if (!r) {
    console.log(`0x${i.toString(16)}`);
  }
}
```

**Comment by ljharb** [comment]
@nkalvi based on the confirmation, i think adding a separate subtest to the table that covers this would be great, if you’re willing to submit a PR.

**Comment by msaboff** [comment]
This is indeed an issue in JSC.  I added a WebKit bug <https://bugs.webkit.org/show_bug.cgi?id=187248> - "YARR: ^. doesn't match non-BMP Unicode characters".

**Comment by nkalvi** [comment]
@ljharb @mathiasbynens @msaboff 

I'm not sure about the extent of the JSC bug: I did one more test, this time without `^` or any other anchor:
```js
/c.lef/u.test( "c𝄞lef" )
```
and Safari returns `false` where as Chrome and Firefox return `true`.

I liked how [You-Dont-Know-JS](https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20%26%20beyond/ch2.md#unicode-flag) illustrated the effect of the `u` flag using `.` - so I think current test could be replaced with one based on it.  
I'm familiar with ragex in Perl, but I'm new to JS & Unicode. I wonder whether @mathiasbynens can suggest a better test(s) here. 

Also, aren't there unit tests to validate the implementation?

**Comment by msaboff** [comment]
This has been fixed in JavaScriptCore and it works correctly in Safari Tech Preview 61.

**Comment by ljharb** [comment]
We still need to update the table to have a new test that covers this bug, and indicates when Safari started passing it.
