### ISSUE TITLE
No Iterator constructor, use "well known symbol" Symbol.iterator

### ISSUE THREAD

**Issue by rwaldron** [compat-table/compat-table#133]
The Iterator test should should be based on the existence of `Symbol.iterator`, something like...

``` js
(typeof Symbol === "function" && typeof Symbol.iterator === "symbol");
```

**Comment by webbedspace** [comment]
Since this is fixed, you can close this now. (Sorry, didn't remember to reference this issue in the commit message.)

**Comment by kangax** [comment]
@webbedspace No problem. Will get to remaining PR's as soon as I get some time.
