### ISSUE TITLE
Object.getOwnPropertyDescriptors is ES7

### ISSUE THREAD

**Issue by rwaldron** [compat-table/compat-table#134]

**Comment by kangax** [comment]
Thanks. I need to start adding ES7 table and thinking of better organization of ES5, ES6, ES7, and non-standard tables.

**Comment by rwaldron** [comment]
@kangax have you considered browserscope? for ringmark I just used browserscope and posted the results of every test run via their JS API. You would only have to store the tests and nothing more, which would give you a greater amount of flexibility for organization.

**Comment by kangax** [comment]
@rwaldron opened new ticket for your suggestion; i'm gonna have to look into it when I get a chance, thanks!
