### ISSUE TITLE
Typo in Array.prototype.flat example? [ES.next]

### ISSUE THREAD

**Issue by aaarichter** [compat-table/compat-table#1343]
should there be a  `,` between 5 and 6 ?

<img width="706" alt="screen shot 2018-09-08 at 1 33 45 pm" src="https://user-images.githubusercontent.com/2707029/45257439-efbfd800-b36b-11e8-8249-3aee9d8963e4.png">

**Comment by ljharb** [comment]
Yes - flat only flattens 1 level by default.
