### ISSUE TITLE
npn error with github:kangax/compat-table#688097f1ce623cb113640cc9108fe04fc41

### ISSUE THREAD

**Issue by MatellioSumit** [compat-table/compat-table#1360]
We were using "babel-preset-es2015". But when we tried to use "babel-preset-env", we are getting error in npm install. The error is as follows:

npm ERR! Unexpected end of input at 1:49197
npm ERR! able":"github:kangax/compat-table#688097f1ce623cb113640cc9108fe04fc41

Please suggest what we should do?

**Comment by ljharb** [comment]
i don’t see any issues with 688097f1ce623cb113640cc9108fe04fc41, and it’s a very old commit. I think you need to file this on babel-preset-env.

**Comment by MatellioSumit** [comment]
Ok. Thanks.
