### ISSUE TITLE
asap vs queueMicrotask

### ISSUE THREAD

**Issue by zloirock** [compat-table/compat-table#1365]
Adding `asap` method for queue microtasks to ECMAScript [was discussed in 2014](https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-09/sept-25.md#510-globalasap-for-enqueuing-a-microtask). Stage 0 and no more discussions (at least, in notes). Now, [`queueMicrotask`](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-queuemicrotask) with the same functionality added to HTML spec. So what should we do with `asap` line in stage 0?

**Comment by ljharb** [comment]
That proposal isn't listed on tc39/proposals; I'll ask the champions if they're still pursuing it.

**Comment by ljharb** [comment]
It seems like it never got anywhere past those meeting notes; the champions don't consider it active. I think we should probably just remove it from the table entirely.
