### ISSUE TITLE
Wrong tests data with Node.js for ES2018 and ES2019

### ISSUE THREAD

**Issue by ehmicky** [compat-table/compat-table#1374]
All ES2018 and ES2019 (optional catch binding) features have been implemented by Node.js `10.13`. They are correctly marked as passing on `http://kangax.github.io/compat-table` but not inside `data*.js` files.

For example `RegExp Unicode Property Escapes` is positive with `node10_13`, which is what `http://kangax.github.io/compat-table/es2016plus/` indicates. However its entry in `data-es2016plus.js` does not indicate any `node10_13`.

This impacts tools like `@babel/preset-env` which will add transforms for all those features when targeting latest Node.js even though it does not need to.

**Comment by afmenez** [comment]
If you look at the `node10_13` definition on environments.json, you'll see that it has an `"equals": "chrome68"` attribute.  This makes all the `chrome68` results cascade to `node10_13`, and that's why there's no need to add explicit node results.

**Comment by ehmicky** [comment]
Yes you're correct, so this is a problem on `@babel/preset-env`, not `compat-table`. Thanks for the quick answer!
