### ISSUE TITLE
Outline Problem in Opera

### ISSUE THREAD

**Issue by cyberstream** [compat-table/compat-table#14]
The outline around the "Current Browser" column is being displayed over the info window that is displayed when you hover over (c)

**Comment by kangax** [comment]
Looks like Opera's implementation of outline paints it on top of all other content? Bumping z-index doesn't help.

**Comment by cyberstream** [comment]
I filed a bug report at https://bugs.opera.com/wizarddesktop/. Hopefully we'll see a fix soon.
