### ISSUE TITLE
Babel Can't find private variable @derivedConstructor (Safari iOS 10.3.1)

### ISSUE THREAD

**Issue by adrienharnay** [compat-table/compat-table#1419]
Hey,

Related Babel issue: https://github.com/babel/babel/issues/9465

Basically, async private methods get transpiled wrongly by Babel, resulting in something that looks like this:

```js
class SomeClass_SomeClass extends react_default.a.Component {
  constructor() {
    super(...arguments);

    _defineProperty(this, "state", getInitialState(this.props));

    _defineProperty(this, "someFunction", async (props, state) => {
      ...
    }
  }
}
```

Safari 10.3.1 doesn't seem to like it, throwing this error:
`Can't find private variable @derivedConstructor` on the `async` keyword.

I'm not sure how compat-table is used by Babel, but please tell me if I can help solving this!

Thanks in advance

**Comment by ljharb** [comment]
Seems like we need a test on async functions in classes specifically, that covers that browser - won’t to make a PR?

**Comment by adrienharnay** [comment]
Sure! Could I ask for a starting point to understand how I should proceed? Thanks!

**Comment by ljharb** [comment]
Async functions are tested here: https://github.com/kangax/compat-table/blob/c28c86b928408920ed3650c40a88a72f9742d243/data-es2016plus.js#L448-L897

You'd want to add another object to that array, that tested this case, and included test results.

**Comment by adrienharnay** [comment]
I see some code that looks like what I'm doing: https://github.com/kangax/compat-table/blob/c28c86b928408920ed3650c40a88a72f9742d243/data-es2016plus.js#L782-L813, isn't it already covered then?

**Comment by ljharb** [comment]
Ah, if so, then you may just need to make a PR that adds the `false` test results for the browser that has a bug?

**Comment by adrienharnay** [comment]
I created a PR, but as I'm said I'm not really sure what I'm doing so I hope I'm right! https://github.com/kangax/compat-table/pull/1420 Thanks for your guidance
