### ISSUE TITLE
TypeScript support for BigInt

### ISSUE THREAD

**Issue by gilamran** [compat-table/compat-table#1431]
It looks like [TypeScript 3.2](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html) supports `BigInt`, but in the table it's marked as it's [not supported](http://kangax.github.io/compat-table/esnext/#test-BigInt).

**Comment by zloirock** [comment]
IIRC TypeScript does not support compiling of `BigInt` for old engines, just type-checking.

**Comment by gilamran** [comment]
tsconfig.json
```
{
  "compilerOptions": {
    "target": "esnext",
    "lib": ["esnext"],
  },
}
```

```
let b = 1n;
```

Will compile to:
```
let b = 1n;
```

**Comment by zloirock** [comment]
Yep. Since this code does not work in old engines, it should not be added to `compat-table`.

**Comment by gilamran** [comment]
WDYM? 
The table should reflect the supported features... and currently the table shows that TypeScript does NOT support BigInt... The table should reflect what TypeScript "understands" not what older engines can run...

For example: Compile the above code (With the BigInt) using TypeScript and run it on NodeJS 11. it works...

**Comment by zloirock** [comment]
`Yes` for compilers in this table shows that after compiling this feature should work in the previous version of the language. You can check `ES6` TypeScript results - it does not mean that TypeScript parser understands just 68% of ES6, it means that just 68% of tests will work after compiling tests to ES5.

**Comment by gilamran** [comment]
@zloirock This behaviour is not really useful... You never compile your JavaScript (Using TypeScript or Babel) code and run it on an older version of the same compiler... why would one need that?

IMHO, the table should indicate if you can use a language feature or not, the target environment can vary... See example above. Sometime you would want to run code on an old browser, latest Chrome, or a specific version of Node...

**Comment by zloirock** [comment]
See #407.

**Comment by gilamran** [comment]
@zloirock According to #407 some of the `No` cells are marked with `Requires native support or a polyfill` and point to a [footnote](http://kangax.github.io/compat-table/esnext/#typescript-es6-note).

This should be the same, but with a different footnote.

**Comment by zloirock** [comment]
@gilamran makes sense, feel free to add a PR with it.

**Comment by ljharb** [comment]
Bigint support can’t really be transpiled or polyfilled, however. I don’t think a note is appropriate there - the question this table answers isn’t “what syntax can i type”, it’s “what can i safely rely on”.  Is the only thing I can rely on is native support, then only native engines should be able to claim yes.

**Comment by gilamran** [comment]
@ljharb Isn't that exactly the reason to add a note that ONLY native support is required? Otherwise, the `BigInt` in all compilers will always be Red... => useless.

**Comment by ljharb** [comment]
That’s not useless - that’s an accurate picture of support.

**Comment by gilamran** [comment]
@ljharb and will never be supported... because you can't polyfill it.
While depending on your target platform, you ARE able to run it...
Is that an accurate picture of support?

**Comment by ljharb** [comment]
Yep! Because use of typescript has no bearing on whether you can use bigints.

**Comment by gilamran** [comment]
It depends on the native support. so why not add a note?
A developer that's considering `bigint` with TypeScript might think that using `bigint` with TypeScript will fail. while it's fully supported and even possible with NodeJS...

**Comment by ljharb** [comment]
Adding or removing Typescript has no bearing on your ability to use bigint - thus, typescript doesn’t support it.

If that developer thinks that, then they’ve misread the table. A note to fix that that makes the actual intention of the table less clear isn’t a good tradeoff.

**Comment by gilamran** [comment]
When you say "TypeScript doesn't support it" what do you mean?
According to what you said, it means that TypeScript will not downgrade this feature, but to what platform?

**Comment by ljharb** [comment]
TypeScript (`tsc`) is two things conflated into one: a typechecker, and a transpiler. What it typechecks is utterly irrelevant to this table - only what it transpiles matters. Since it doesn't transpile bigint, it doesn't support it - it's pretty straightforward.

**Comment by gilamran** [comment]
As you said, it is not possible to transpile BigInt... When will this cell change to green?
A year? Two? Ten? Never? There will be day that BigInt is supported by all major platforms...

**Comment by ljharb** [comment]
Never, since TypeScript will never support it. It'll never turn green for babel either.

**Comment by gilamran** [comment]
Ok, got you. Thanks for the time and effort!

**Comment by zloirock** [comment]
@ljharb it *can be* green for `babel` and a PR for that available more than a year, but, by performance reason, I don't think that it's a good idea.

**Comment by ljharb** [comment]
@zloirock fair :-). I’m sure the same could be said about typescript (that they wouldn’t do that for perf reasons)
