### ISSUE TITLE
There’s no such thing as “Edge 19 preview”

### ISSUE THREAD

**Issue by claudepache** [compat-table/compat-table#1461]
PR #1355 optimistically added “Edge 19 preview”—where the version number is in fact the one of EdgeHTML. However, future Edge releases should not be based on EdgeHTML any longer. 

Concretely, the latest version of Edge from the Canary Channel (on which I’m writing this issue) shows the same results as Chrome 76 in the compat-table, and identifies itself as:

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3803.0 Safari/537.36 Edg/76.0.175.0

although I’ve admittedly not researched whether there exists some Windows-only  preview version of Edge that performs differently.

**Comment by chicoxyzzy** [comment]
I think that we can just remove Edge 19 for now until we really know which version of Chromium-based Edge will be stable release

**Comment by chicoxyzzy** [comment]
On the other hand, we can add Edge 76, but the question is: should we add dev version, canary version or both? AFAIK dev and canary are both 76 and beta is not available on any platform yet

**Comment by zloirock** [comment]
I'm for removing and waiting.

**Comment by ljharb** [comment]
+1 to removal; there's minimal benefit from having unreleased browsers in the table at all imo.
