### ISSUE TITLE
Add JerryScript?

### ISSUE THREAD

**Issue by akosthekiss** [compat-table/compat-table#1479]
Would you be interested in adding the JerryScript engine (https://github.com/jerryscript-project/jerryscript) to the project? I saw that Duktape, another JS engine for embedded systems, is already included. I've prototyped a test runner for JerryScript based on the existing duktape.js runner (https://github.com/akosthekiss/compat-table/commits/jerryscript). Let me know if this could be integrated.

**Comment by zloirock** [comment]
Feel free to add a PR.
