### ISSUE TITLE
How do I see support for Opera 31?

### ISSUE THREAD

**Issue by shawty** [compat-table/compat-table#1509]
Ticking show obsolete platforms doesn't go back far enough, I'm working on a project on a TV browser that uses Opera 31.

Actually I have Opera 31 & Opera 40 on a different device, and I need to know what they do and don't support, how can I make the web view show these older browsers?

**Comment by ljharb** [comment]
I don't think we have a way to show "very obsolete" browsers on the website. You could certainly clone the repo, change the browser data, and build it locally though.

**Comment by shawty** [comment]
ok, thanks for that :-)
I'll have a look at doing that.

**Comment by afmenez** [comment]
Can this be closed then?

**Comment by shawty** [comment]
Yes, sorry... I should have closed it ages ago.

Stupid me ...
