### ISSUE TITLE
Non-standard: add more SpiderMonkey extensions

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#151]
- (`Date#toLocaleFormat`)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleFormat]
- (Function `displayName` property)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/displayName] (What it actually does, when set, is make an anonymous function have a different name than `"(anonymous function)"` on the dev tools' call stack.
- (Error `columnNumber` property)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/columnNumber]
- (Object `__noSuchMethod__` property)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/noSuchMethod] ...(Despite the page name, `"__noSuchMethod__" in Object.prototype` is false in Firefox.)
- (InternalError)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError]
- (Object `__lookupGetter__` property)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/lookupGetter]

**Comment by kangax** [comment]
@webbedspace thanks for all the suggestions and bug reports! If you can create PR's for all or any of them, that would be amazing. I don't have much time right now between work and all the OS projects, so not sure when I'll be able to get to this.

**Comment by webbedspace** [comment]
OK, I've given it a shot. #155

**Comment by webbedspace** [comment]
Update: `displayName` isn't possible to test for inside page Javascript (given that it only affects console output) so that's sadly out. Also I didn't notice `__noSuchMethod__` was already present.

Other things that this table could do with:
- `for each` loops
- `Iterator` constructor and the `__iterator__` [property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators)
- JS 1.8-style generators (e.g. `yield` in bare functions without the `*`)
- [JS 1.8-style generator comprehensions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators#Generator_expressions)
- [String generic methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#String_generic_methods)

I'm idly wondering whether early-draft ES6 features should also be included on the non-standard table - such as `Number.prototype.clz`, which WebKit still supports.
