### ISSUE TITLE
Merge strawman and pre-strawman

### ISSUE THREAD

**Issue by chicoxyzzy** [compat-table/compat-table#1513]
<img width="446" alt="image" src="https://user-images.githubusercontent.com/1507086/66340185-5176bb00-e94d-11e9-8eb7-e6d79455d11c.png">

I don't think that pre-strawman is somehow different from stage 0 aka strawman, so we probably should just move pre-strawman proposals to strawman.

**Comment by chicoxyzzy** [comment]
Oh, and AFAIR it's named strawperson now

**Comment by ljharb** [comment]
I suppose it's fine to merge them; the difference is that "pre" hasn't been presented to TC39.

**Comment by zloirock** [comment]
I don't care.

**Comment by ljharb** [comment]
tbh it’s probably better to just delete anything that hasn’t been presented yet.

**Comment by zloirock** [comment]
Reflect metadata API is actively used, so I don't think that removing it is a good idea. Why it was marked as a pre-strawman - [this](https://github.com/rbuckton/reflect-metadata/issues/9#issuecomment-135177873) and similar comments.

**Comment by ljharb** [comment]
Usage is irrelevant; if it’s not in the proposals list, it’s not a proposal, and a non-proposal that isn’t shipped in browsers shouldn’t be in this repo.

**Comment by zloirock** [comment]
Doubtful statement. If a proposal is not in the official proposals list, this does not mean that it is not a proposal, it's just not presented. If it's positioned as a proposal, if it's from someone related TC39, if were plans to present it in the future and it's actively used, I don't think that it should be removed from the table.

**Comment by ljharb** [comment]
yes, it does - the proposals list is the source of truth. Although being presented isn’t a requirement, being in the list imo is.

**Comment by chicoxyzzy** [comment]
According to [process document](https://tc39.es/process-document/) and [championing proposal doc](https://github.com/tc39/how-we-work/blob/master/champion.md#stage-1), stage 1 proposal is something, that was presented to the committee and stage 0 proposal has no any entrance criteria

**Comment by ljharb** [comment]
That is technically true, but in practice, if it’s not on an agenda or on the proposals list, it’s not considered stage 0 - otherwise every random idea would be, and the category would be meaningless.

**Comment by zloirock** [comment]
#550 funny -)

**Comment by ljharb** [comment]
Indeed, my stance has evolved over time as the proposals repo has become the source of truth.

**Comment by chicoxyzzy** [comment]
stage -1 and stage 0 proposals was removed from table in https://github.com/kangax/compat-table/commit/3d720c820661a4ec4fe827ace8094c8921420723
