### ISSUE TITLE
ES6: mark Opera 15 obsolete, add Opera 22

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#153]
I think Opera 12 is still supported for at least another couple months.

**Comment by webbedspace** [comment]
Thinking about this... Opera 15+ is pretty much lock-step with Chrome, where its Chromium/Blink version has been [Opera version + 13] for every release, so maybe the Opera 15 column should be removed and replaced with just an extra label over the Chrome columns (e.g. changing "CH35" to "CH35,<br>OP22") and so forth.

**Comment by kangax** [comment]
Hm, yeah that's not a bad idea to join them.
