### ISSUE TITLE
Huge HTML / page content

### ISSUE THREAD

**Issue by DanielRuf** [compat-table/compat-table#1533]
The website contains so much HTML that it is too much for some tools which parse it. Can this be improved?

**Comment by ljharb** [comment]
What tools?

**Comment by DanielRuf** [comment]
htmlcompressor.com and a few others which are used to benchmark html-minifier.

**Comment by ljharb** [comment]
it seems like a tool whose specific purpose is to handle html should be able to handle large quantities of it, no?

**Comment by DanielRuf** [comment]
>  should be able to handle large quantities of it, no?

I do not fully understand your answer. Did you forget some words?

Currently the html from the compat tbale website is too much for this and it closes the connection / pipe during generation fot the benchmark results. See https://github.com/kangax/html-minifier/blob/gh-pages/benchmark.js#L358

Probably the tool by Will Peavy too.

I#m just asking to improve the current size of the website so such tools do not yet this problem =)

**Comment by DanielRuf** [comment]
To be exact, it's 6.35 MB

<img width="1099" alt="Bildschirmfoto 2019-11-02 um 16 08 54" src="https://user-images.githubusercontent.com/827205/68072901-18ced380-fd8b-11e9-9939-42789642411d.png">

**Comment by DanielRuf** [comment]
To be exact, it's 6.35 MB (240KB compressed, but still way too much):

<img width="1099" alt="Bildschirmfoto 2019-11-02 um 16 08 54" src="https://user-images.githubusercontent.com/827205/68072901-18ced380-fd8b-11e9-9939-42789642411d.png">

**Comment by chicoxyzzy** [comment]
@DanielRuf isn't this a downside of htmlcompressor? According to the [table from html-minifier repo](https://github.com/kangax/html-minifier#minification-comparison), it's not an issue for some other tools

**Comment by DanielRuf** [comment]
> According to the [table from html-minifier repo](https://github.com/kangax/html-minifier#minification-comparison), it's not an issue for some tools

`n/a` means that it threw an error or did not get a response at all.

But this is more about optimizing the website in general than just this one tool.
6 MB is much data and there might be other usecases to fetch and parse the content.

Also this would be a problem on mobile devices for example.

**Comment by ljharb** [comment]
(I forgot no words in my comment; it’s proper English)

Obviously if there’s a trivial way to produce less html, we can and should do it; but i suspect the architecture of the site just lends itself to having lots of html, and a large scale refactor isn’t likely worth it to avoid 240k (down to whatever it gzips to, even) over the wire, which is about the size of a smallish image.

**Comment by DanielRuf** [comment]
> down to whatever it gzips to, even

It is actually 6MB gzipped to 240KB.

**Comment by DanielRuf** [comment]
I just missed some comma and `it` in the answer. After reading it for the fourth time with a few commas and breaks in ,y mind makes more sense now.

No, 6MB is probably nothing what it was meant to handle. The markup is currently too much to get a fast response from the tool(s).

**Comment by chicoxyzzy** [comment]
@DanielRuf while we all agree that's a great idea to reduce compat-table HTML size, I don't get it why should we adjust HTML size for some random tool. That's not our fault that some HTML parsers can't parse HTML with size bigger than Wikipedia's POTUS page. There are other parsers available which can do this.

**Comment by DanielRuf** [comment]
https://github.com/kangax/compat-table/issues/1533#issuecomment-549053528

It is not mainly about these tools. My internet connection in the village is not so fast and it is loading very long on my computer and smartphone.

It is about optimization in general.
