### ISSUE TITLE
[regression] Pre-chromium edge doesn't show correct data for let/const

### ISSUE THREAD

**Issue by nicolo-ribaudo** [compat-table/compat-table#1575]
Ref: https://github.com/babel/babel/pull/11039#discussion_r369237851

Old comapt-table versions correctly showed Edge 16 as supporting `let`/`const`: https://web.archive.org/web/20191113231919/https://kangax.github.io/compat-table/es6/
The current version doesn't.

According to `git bisect` the regression has been introduced by 44c16dd2e3b2d16ad8280a5edd23fc48def434c1 (@existentialism You were right :stuck_out_tongue:)

I'm investigating a fix.

**Comment by ljharb** [comment]
cc @chicoxyzzy
