### ISSUE TITLE
ES6: Symbol.iterator test code is wrong

### ISSUE THREAD

**Issue by muratsu** [compat-table/compat-table#158]
According to the revision 25 of the ES6 [spec](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-getiterator) this example is wrong.
In spec section 13.6.4.8 Runtime Semantics: ForIn/OfBodyEvaluation, 3.a IteratorStep will be called and since done value is true, it will return false. This will cause 3.c to return a NormalCompletion which will result in _c_ remaining _undefined_ and ofBodyEvaluation will be skipped. 

Below is a better example:

``` javascript
var a = 0, b = {};
b[Symbol.iterator] = function() {
    return {
        next: function() {
            return { 
                done: a === 1,
                value: a++ 
            };
        }
    };
};

for (var c of b) { 
    console.log(c === 0);
} 
```

**Comment by rwaldron** [comment]
@muratsu Can you prepare a patch with this change—thanks!

**Comment by muratsu** [comment]
there you go @rwaldron  
https://github.com/kangax/compat-table/pull/162

**Comment by rwaldron** [comment]
Awesome, thank you
