### ISSUE TITLE
support for non-browser (and non-eval-capable) hosts

### ISSUE THREAD

**Issue by toshok** [compat-table/compat-table#166]
I'm guessing traceur runs up against this as well somewhat, but they at least support eval() which EJS doesn't.

I'd love to figure out some way to express the tests such that the eval + try/catch wrappers are applied during the build.js process, so I could have build.js also spit out the tests in a form that ejs can work with natively.

Would there be much/any interest in such a PR?

**Comment by kangax** [comment]
I suppose it would make sense, so go ahead and I'll take a look at it.

How would you test things without eval though?

**Comment by webbedspace** [comment]
Followup: would #234 help fix this, do you think?
