### ISSUE TITLE
Unmark rhino as obsolete and update compatibiliy for recent versions

### ISSUE THREAD

**Issue by gausie** [compat-table/compat-table#1687]
Since Nashorn has been deprecated as Java's Javascript engine, Rhino now has increased importance for people who don't want their existing applications to rely on 20mb of GraalVM.

Additionally, Rhino as currently tabulated is very out of date. Rhino themselves maintain a [kangax-compatible](http://mozilla.github.io/rhino/compat/engines.html) table.

**Comment by ljharb** [comment]
Updating the results sounds great, but “obsolete” doesn’t just mean “nobody’s using it”. Rhino remains obsolete forever, and as far as i understand it, the best practice for Java users is still to use graal or node.
