### ISSUE TITLE
ES6 subclassable builtins

### ISSUE THREAD

**Issue by Yaffle** [compat-table/compat-table#169]
What about a test for subclassable builtins?

```
  function CustomError(message) {
    Error.call(this, message);
  }
  CustomError.prototype = Object.create(Error.prototype);
  var error = new CustomError("123");
  var ok = error.toString().indexOf("123") !== -1;
```

Although, this will be not very useful, because if "error.stack" will be initialized, it will contain extra stack entry...
Although, subclass of `Promise` can be useful for `XMLHttpRequest` wrapppers to have `abort` method on resulting promise.

see 
https://github.com/Modernizr/Modernizr/issues/1283
http://wiki.ecmascript.org/doku.php?id=strawman:subclassable-builtins
https://code.google.com/p/v8/issues/detail?id=3101
https://bugzilla.mozilla.org/show_bug.cgi?id=838540

`Promise` subclassing may be more interesting

**Comment by dead-claudia** [comment]
I would think subclassing an Array would be a better test (it is completely unsubclassable in ES5).

**Comment by Yaffle** [comment]
@impinball, possibly, but I have no real world use cases for this.
New UI allows to add many tests per each "row".
P.S.
Actually, this is a duplicate of https://github.com/kangax/compat-table/issues/105
