### ISSUE TITLE
Can't open the site in China

### ISSUE THREAD

**Issue by smalllong** [compat-table/compat-table#1732]
As you know, `https://ajax.googleapis.com/` won't work in China. As a result, when accessing the site from China, it takes forever to load. Can you replace it with something like `https://unpkg.com`? As I tested, unpkg.com works well in China.

**Comment by FrankHB** [comment]
It may be an improvement, but ...

> The unpkg CDN is powered by Cloudflare.

Not sure someday it would be slow enough like being blocked in China mainland.

**Comment by smalllong** [comment]
No worries, there is a better solution for this: https://github.com/justjavac/ReplaceGoogleCDN
