### ISSUE TITLE
"spread parameters after optional chaining" works in Chrome 91

### ISSUE THREAD

**Issue by fgblomqvist** [compat-table/compat-table#1737]
https://kangax.github.io/compat-table/es2016plus/#test-optional_chaining_operator_(?.)_spread_parameters_after_optional_chaining

This was originally added in https://github.com/kangax/compat-table/pull/1708 which referenced https://github.com/babel/babel/issues/13001 which in turn referenced [this Chrome bug](https://bugs.chromium.org/p/v8/issues/detail?id=11558). That bug was fixed at the end of March and [is supposedly released V8 9.1](https://bugs.chromium.org/p/v8/issues/detail?id=11729#c3) (I don't know how to formally check which version a bug was fixed in?) which [was first used in Chrome 91](https://v8.dev/blog/v8-release-91).

I'm not entirely sure how this compat table works, if it's all just manually put together. If so, maybe it's time to mark it as a yes in Chrome 91 and onwards?

Finally, for very particular issues like this, is there a way to quickly find the browser bug for it without digging through the web? 😄   Maybe a citation should have been added originally, along with a link to the Chrome bug? Or is there a different way you guys do it?

Appreciate the hard work with this table!

**Comment by ljharb** [comment]
To update this here, find the test result in the relevant data-*.js file, update it, and run `npm run builds. Want to make a PR? :-)

Linking to bugs would be done in a note, and it’s always a good idea, but we don’t always know to add them.

**Comment by fgblomqvist** [comment]
Alright, yeah I'd be happy to submit a PR (sometime in the next couple of days). Does Edge just use the same test result as Chrome?

**Comment by ljharb** [comment]
Yes, all v8-based engines inherit the same results, unless overridden.

**Comment by fgblomqvist** [comment]
Great. I just verified the test on Chrome 90 (not working) and 91 (working) using BrowserStack, so will submit the PR later once I've pulled down the code and gen'd the files.

**Comment by fgblomqvist** [comment]
Btw how do you track which V8 version other browsers have shipped? To know how to inherit stuff.

**Comment by ljharb** [comment]
Not by the v8 version - we say, eg, edge N is similar to chrome M
