### ISSUE TITLE
"Global symbol registry is wrong" is wrong

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#175]
#160 did not actually fix the global symbol registry test - it merely updated the compiled HTML file instead of `data-es6.js`.

(This may make you wonder why the compiled HTML file is even in version control anyway. Maybe it should be `.gitignore`d from now on?)

**Comment by kangax** [comment]
My bad; can't believe I missed it. The problem with putting html in .gitignore is that we still need it to be in the repo and updated, so AFAICS can't exclude it.

One option would be to include data files dynamically via JS and build HTML accordingly. That way we could avoid entire compilation process, in exchange for (unfavorable but maybe ok?) dependence on JS.
