### ISSUE TITLE
Can't find URL Standard

### ISSUE THREAD

**Issue by TimDaub** [compat-table/compat-table#1782]
Consider that it may be that I'm confused about what the table is tracking, but I'm looking for the compatibility of JavaScriptCore and the What-WG URL spec https://url.spec.whatwg.org/

I've clicked through the different ES versions but couldn't find it. Does it not belong there? Can I help adding it?

**Comment by nicolo-ribaudo** [comment]
compat-table only tracks ECMAScript features (defined at tc39.es/ecma262/), and not WHATWG features. You can check on caniuse: https://caniuse.com/?search=URL

**Comment by TimDaub** [comment]
Thanks for your speedy answer. I tried using canIuse.com, but I need to specifically know if JavaScriptCore can be directly equated to e.g. "Safari on iOS" as e.g. the React Native docs say: "RN runs on iOS in JavaScriptCore". But JavaScriptCore is never mentioned specifically anywhere? Are "JavaScriptCore" and "Safari on iOS" equivalents in terms of compatibility? Sorry for bothering you with this question. Feel free to ignore.

**Comment by ljharb** [comment]
No, jsc is not equivalent to Safari when it comes to non-language things; at one point it didn't even have a setTimeout.

**Comment by TimDaub** [comment]
Thanks @ljharb. Since you're somewhat experts in this field, do you have suggestions where I could find out this type of compatibility? I already sent an email to an @apple.com address, but is this information being tracked somewhere publicly? Again sorry for off-topic.

**Comment by ljharb** [comment]
I'm not sure - Apple doesn't maintain a list I'm aware of, and there doesn't seem to be much interest in anyone tracking jsc directly.

You may be able to run Web Platform Tests against jsc, and that would tell you?

**Comment by TimDaub** [comment]
> You may be able to run Web Platform Tests against jsc, and that would tell you?

fair enough, I'll look into that! Thanks for your help!
