### ISSUE TITLE
"let" test for non-Firefox browser

### ISSUE THREAD

**Issue by rwaldron** [compat-table/compat-table#18]
<img src="http://gyazo.com/4d433b7d42ef218b394b61a4e9cb02c8.png">

**Comment by rwaldron** [comment]
I have a patch for this, but I just ran head-on into an issue where `let` throws in Opera:

`Unhandled Error: at index 71: expected expression, got reserved word 'let'`

Which is a parse error :(

**Comment by kangax** [comment]
Looks like `let` works in Chrome (at least in my dev 19) only in strict mode.

**Comment by rwaldron** [comment]
Sure does and I have a test for it, but the test throws in opera, because `let` is a reserved word.

**Comment by kangax** [comment]
Well, surely nothing try/catch+eval can't fix? :)

**Comment by rwaldron** [comment]
I'll push the branch and let you take a look ;)

**Comment by rwaldron** [comment]
`git checkout -b current-browser-let-test && git pull git://github.com/rwldrn/es5-compat-table.git current-browser-let-test`

Hopefully you can identify anything I might've missed

**Comment by kangax** [comment]
Thanks. I'll get to it tomorrow.

**Comment by kangax** [comment]
I cleaned it up a little. Didn't find a way to prevent error in Opera. It's crazy how Opera claims that exception is unhandled even when _handling_ it via try/catch. But the error is innocent, so I corrected layout and we should be all good to go.

Might be a good idea to add a note about Chrome only supporting `let` in strict mode...
