### ISSUE TITLE
Look into browserscope, ringmark

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#184]
"@kangax have you considered browserscope? for ringmark I just used browserscope and posted the results of every test run via their JS API. You would only have to store the tests and nothing more, which would give you a greater amount of flexibility for organization."

-- https://github.com/kangax/compat-table/issues/134#issuecomment-45222621

**Comment by afmenez** [comment]
Browserscope is an obsolete browser test (last commit in jan/2016), it checks for security, network performance, CSS implementation and Web APIs, but not JS.
Ringmark is also an obsolete browser test (last update in 2012), with no JS tests.
I don't see the point of integrating any of those with this JS compatibility test.
