### ISSUE TITLE
Feature Request - Browser Market Share

### ISSUE THREAD

**Issue by FabianoLothor** [compat-table/compat-table#1841]
Do you guys have any plans to add current's market share of each browser, it would be a fantastic addition.

**Comment by ljharb** [comment]
How do you suggest measuring that?

**Comment by FabianoLothor** [comment]
So, it might not be easy to get the data for all browsers that you guys are supporting, but those could be combined in a "other" category.

We've other sources of course, but personally, I like to check here:
- https://gs.statcounter.com/browser-market-share

They currently provide a `.csv` file with the market share of 24 browsers (and increasing).

Unfortunately the `csv` doesn't provide the market share by browser version, but it would be a start.

**Comment by ljharb** [comment]
What would be the value in including this info? Overall, it's basically "Chrome and Safari constitute nearly 85% of the internet", but in reality, the only thing that matters is the demographics of your own site - which might be quite different.

**Comment by FabianoLothor** [comment]
> Chrome and Safari constitute nearly 85%

It doesn't mean that other browsers aren't important and that you shouldn't consider them when starting a new project.

---

![image](https://user-images.githubusercontent.com/2192995/204049409-f7d8b306-b948-4c95-ba6c-68bf6d2b58f9.png)

Even browsers with 0.5% of market share are still relevant.

![image](https://user-images.githubusercontent.com/2192995/204049512-645d06dd-fc9b-4509-a596-9b5a9320a350.png)

25 million of people is still a relevant number I guess.

I agree with you when you say that what matters is the public of your own site, but you don't have this information when you are starting a new project.

---

I see a lot of value in have the market share close to the browser when I'm checking the compatibility that those browsers provide.

It makes much more easy to define which browsers worth to be supported or not.

---

Anyway, it was just a suggestion, if you guys don't see any value, just ignore it.

Have a nice day!
