### ISSUE TITLE
Deno uses V8; should not be painted yellow but green (also current Opera)

### ISSUE THREAD

**Issue by tats-u** [compat-table/compat-table#1848]
![image](https://user-images.githubusercontent.com/12870451/217259107-deaee86e-4f54-452d-a07c-01aefcd335e8.png)

https://deno.land/

> Powered by Chrome's V8
>
> Built on top of the fastest and most complete JavaScript engine.

Deno's runtime is V8; it's same as Node, Chrome, and Edge. It should be painted green like them.

**Comment by zloirock** [comment]
Feel free to add a PR.

**Comment by zloirock** [comment]
The same with Chromium-based Opera.

**Comment by tats-u** [comment]
> The same with Chromium-based Opera.

Right.

> Feel free to add a PR.

PR only? ~~I've found it doesn't seem to be due to `environments.json` as of now. Do we have to edit HTML directly?~~

https://github.com/kangax/compat-table/blob/c19308c9785e62b54b6b45755a47a54f34ba1efc/master.js

This file looks suspicious. Do you think it is bingo?

**Comment by zloirock** [comment]
IIRC yes.
