### ISSUE TITLE
add new es2023 Array.prototype methods

### ISSUE THREAD

**Issue by chharvey** [compat-table/compat-table#1874]
[ECMAScript 2023 introduced](https://tc39.es/ecma262/multipage/#sec-intro) new `Array.prototype` methods: `toSorted`, `toReversed`, `with`, `findLast`, `findLastIndex`, and `toSpliced`. The `findLast` and `findLastIndex` methods are already present on [the compatibility table](https://kangax.github.io/compat-table/es2016plus/), but the rest are missing. This request is to add them to the table for completion. Thank you.

**Comment by zloirock** [comment]
Feel free to add a PR.
