### ISSUE TITLE
Show Chrome support without #enable-javascript-harmony

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#188]
Some developers may be interested in what ES6 features Chrome supports for stable users, not just those with #enable-javascript-harmony enabled. At the moment this could be a new column, but I'm thinking it'd be more correct if the current column had some augmentation to it: all of the features that are present but require #enable-javascript-harmony have a badge (similar to caniuse's prefix marker) in their squares.

**Comment by kangax** [comment]
Yep, I like this idea. We should do it at some point.

**Comment by jerone** [comment]
I support this feature. Right now it looks like Chrome supports some features out-of-the-box, while in reality it requires the Enable Experimental JavaScript (`#enable-javascript-harmony`) flag be enabled to support those features.

**Comment by webbedspace** [comment]
Just jotting down some support notes:

Opera 18 / Chrome 31:
- const
- typed arrays
- Object.is
- function 'name' (basic)
- Number.isFinite
- Number.isNaN
- Math.imul

Opera 20 / Chrome 33:
- Promise

Opera 21 / Chrome 34:
- Object.setPrototypeOf
- String#normalize
- All remaining Number methods/properties

Opera 23 / Chrome 36:
- WeakMap
- WeakSet

Opera 25 / Chrome 38:
- const
  - basic (non-strict)
- for..of
- Map
- Set
- Object.getOwnPropertySymbols
- Symbol
- Global symbol registry
- Symbol.iterator
- Symbol.unscopables
- Array#keys
- <strike>Array#values</strike>
- Array#entries
- Array#[Symbol.unscopables]
- All remaining Math methods/properties

Opera 26 / Chrome 39:
- generators
  - all except shorthand methods

These seem to be the only changes in unflagged ES6 support.
