### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by nicolo-ribaudo** [compat-table/compat-table#1880]
http://kangax.github.io/compat-table/ gives a 404 error.

**Comment by ljharb** [comment]
ah yes, thanks. To fix this, @kangax will need to make some changes on their github; I'll figure out what the exact steps are and then ping them to execute.

**Comment by ljharb** [comment]
Steps: https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7#the-solution

The new URL is https://compat-table.github.io/compat-table/, and everything should be updated to point to that, but the old URL should still redirect forever, so hopefully that will be fixed soon.

edit: filed https://github.com/kangax/kangax.github.com/pull/2 which will fix this issue.

**Comment by ljharb** [comment]
All fixed!
