### ISSUE TITLE
Some of the subtests of "Proxy, internal 'get' calls" on the es6 tab seem to be broken

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#1894]
The subtests "RegExp.prototype.flags", "RegExp.prototype[Symbol.match]" and "RegExp.prototype[Symbol.replace]" are failing on both Chrome and Firefox. Is it a coincidence or are the tests actually broken?

**Comment by ljharb** [comment]
They're all passing for me on Chrome and Firefox, and haven't changed in a long time.

**Comment by afmenez** [comment]
I tested again:
- `RegExp.prototype.flags` is failing on Firefox 127, Firefox Nightly 129, Chrome 126 and Edge 126
- `RegExp.prototype[Symbol.match]` is failing on Firefox 127, Firefox Nightly 129, Chrome 126 and Edge 126
- `RegExp.prototype[Symbol.replace]` is failing only on Firefox 127 and Firefox Nightly 129

**Comment by ljharb** [comment]
On Firefox 127 on my Mac, all those tests are passing for me.

**Comment by afmenez** [comment]
I can't test on a Mac, but I got the same failures on Firefox 127 for Win10, Win11 and Android 14, and on Chrome 126 for Win10, Win11 and Android 14.

**Comment by ljharb** [comment]
oh hmm, i may have been looking at the wrong results.

I see in Safari that the flags test is failing because of the addition of `hasIndices` and `unicodeSets`; the other tests are failing for similar reasons. I'll put up a PR.
