### ISSUE TITLE
Promise.withResolvers appears to be missing

### ISSUE THREAD

**Issue by Snugug** [compat-table/compat-table#1926]
[`Promise.withResolvers()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers), per MDN data, is available across the board, but I don't see this feature in the compat table, which winds up breaking tests that rely on this list for availability.

**Comment by ljharb** [comment]
Indeed, as is Promise.try. I'll try to get some tests for them written in the next day or so and put up a PR (if nobody beats me to it)
