### ISSUE TITLE
Is the ArrayBuffer.prototype.realloc() test valid?

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#1927]
I haven't found a reference to `ArrayBuffer.prototype.realloc()` on the [`ArrayBuffer.prototype.transfer`](https://github.com/tc39/proposal-arraybuffer-transfer) proposal, and none of the browsers implement it.  Should the test really be there?  Is there a separate spec for it?

**Comment by ljharb** [comment]
No, it shouldn't - there's just `transfer()`, `.transferToFixedLength()`, and `.detached`.
