### ISSUE TITLE
Konqueror supports proper tail calls???

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#199]
Actually, it doesn't - but the test shows "Yes" when I run it in Browsershots. The reason seems to be that when KQ evaluates something like `var x = (function f(n){ if (n <= 0) return true; return f(n - 1);}(1e6));`, it runs out of call-stack and creates a RangeError object... but _returns_ it instead of throwing it. That is, the RangeError object is silently assigned to `x`, and execution continues on its merry way.

In the case of the test, since RangeError objects are truthy, the test shows "Yes". Very funny :3

**Comment by kangax** [comment]
That's crazy... Good catch :)

**Comment by pvdz** [comment]
Well hey, better a random return value than an unrecoverable error. I guess.
