### ISSUE TITLE
inverted checkbox option

### ISSUE THREAD

**Issue by michaelficarra** [compat-table/compat-table#2]
The checkbox option is inverted. When checked, the columns are hidden, and when unchecked (after having been checked initially), they are show.

https://github.com/kangax/es5-compat-table/blob/50dfabff13b963e7f681/index.html#L1132

Line 1132 of index.html should be changed to

```
document.body.className = this.checked ? 'hide-old-browsers' : '';
```

**Comment by kangax** [comment]
Fixed in https://github.com/kangax/es5-compat-table/commit/2d619b7293ea9bb633e0ea99a1729afabceda337
