### ISSUE TITLE
ES6: Maybe add results for Continuum

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#200]
[Continuum](http://benvie.github.io/continuum/) is actually not too bad for ES6 support.

I did a test crudely based off the Node test script, and came up with these positive results:
- `arrow functions`
- `const`
- `let`
- `default function params`
- `rest parameters`
- `spread call (...) operator`
- `spread array (...) operator`
- `shorthand properties`
- `shorthand methods`
- `For..of loops`
- `Generators (yield)`
- `Map`
- `Set`
- `Proxy "get" handler`
- `Proxy "set" handler`
- `Proxy "has" handler`
- `Proxy "deleteProperty" handler`
- `Proxy "getOwnPropertyDescriptor" handler`
- `Proxy "isExtensible" handler`
- `Proxy "enumerate" handler`
- `Proxy "apply" handler`
- `Proxy "construct" handler`
- `Block-level function declaration`
- `Destructuring parameters`
- `Destructuring rest`
- `Object.assign`
- `Object.is`
- `String.prototype.repeat`
- `String.prototype.startsWith`
- `String.prototype.endsWith`
- `String.prototype.contains`
- `Unicode code point escapes`
- `Array.from`
- `Array.of`
- `Array.prototype.keys`
- `Array.prototype.values`
- `Array.prototype.entries`
- `Number.isFinite`
- `Number.isInteger`
- `Number.isNaN`
- `Number.EPSILON`
- `Math.imul`
- `Math.sign`
- `Math.log10`
- `Math.log2`
- `Math.log1p`
- `Math.expm1`
- `Math.cosh`
- `Math.sinh`
- `Math.tanh`
- `Math.acosh`
- `Math.asinh`
- `Math.atanh`
- `Math.hypot`
- `Math.trunc`
- `Math.cbrt`
- `__proto__ in object literals`
- `String.prototype HTML methods`

Note that I was running this off my #197 branch, so there are extra Proxy results included.

**Comment by kangax** [comment]
We could. And this would bring us to 3 compilers (Traceur, EJS, Continuum), which reminds me that we should really start grouping engines by type — Desktop, Mobile, Compilers. Aside from more convenient table exploration (maybe hide compilers by default?), this would also make it easier to show overlaps in the future; e.g. if someone wants to see supported features when running FF30 (desktop) + Traceur (compiler).

**Comment by dead-claudia** [comment]
By the way, the [last commit](https://github.com/Benvie/continuum/commits/gh-pages) affecting actual code was in March (I'm not counting the docs link fix in June). I kinda get the vibe that it's a dead project at this point.
