### ISSUE TITLE
ES6: Add Typed Array tests

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#207]
I forgot that the Typed Arrays are in ES6 now and not the DOM. That calls for, at the least, existence checks for the following:
- `ArrayBuffer`
- `DataView`
- The "view" constructor functions, `Int8Array`, `Uint8Array`, `Uint8ClampedArray`, `Int16Array`, `Uint16Array`, `Int32Array`, `Uint32Array`, `Float32Array`, `Float64Array`

**Comment by jdalton** [comment]
:+1: I'll see about doing a PR this week.

**Comment by webbedspace** [comment]
Actually, I've already made a [start](https://github.com/webbedspace/compat-table/commit/34972b481456cfb48ee13181cdefd48b79349848) on one - although I'm not 100% intimate with the workings of it and the behaviour it checks may not be fully relevant.

**Comment by jdalton** [comment]
Oh rad! PRs away :rocket:!
