### ISSUE TITLE
ES7: Add Array#contains test

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#230]
http://esdiscuss.org/topic/array-prototype-contains
https://github.com/domenic/Array.prototype.contains

**Comment by kangax** [comment]
This is already done

**Comment by webbedspace** [comment]
[R.I.P. `contains` support in FF35](http://esdiscuss.org/topic/having-a-non-enumerable-array-prototype-contains-may-not-be-web-compatible) (Just a heads-up.)

**Comment by kangax** [comment]
@webbedspace nah, @jdalton won't let go off mootools that easy :P

**Comment by kangax** [comment]
Btw, the patch is already in — https://github.com/mootools/mootools-core/commit/521471f5c0617edc12c680cdad8346c3eb95776a — so it's a matter of how fast it propagates

**Comment by jdalton** [comment]
\cc @anutron!

**Comment by anutron** [comment]
Thanks for the ping. I'm not really sure what I'm supposed to do with it though. I think @SergioCrisostomo is pushing out the support for `.contains` imminently.
