### ISSUE TITLE
Support should-not-compile 

### ISSUE THREAD

**Issue by johnjbarton** [compat-table/compat-table#236]
The following code should result in a SyntaxError:

``` js
function bar () {
    'use strict';
    {
      function f(){}
    }
    return typeof f === "undefined";
}
```

One way to handle this is to have a property `shouldNotCompile: 'SyntaxError'`.

**Comment by webbedspace** [comment]
This _used_ to result in a syntax error in ES5, but it has been changed in the ES6 spec. (In fact, the purpose of the ES5 syntax error was, I recall, to buy TC39 some extra time to decode how the actual strict mode block function statement semantics should work.)

Incidentally, the current de facto method of testing whether a thing produces a syntax error is to use an explicit `try eval/catch` where the `catch` block sets `passed` (or whatever variable we're going to return) to true.

**Comment by johnjbarton** [comment]
Thanks.

The main remaining problem for traceur is the uses of 'eval()`which don't seem to use the`passed` solution.
