### ISSUE TITLE
Chrome 37 results not accurate

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#239]
A number of features present in Chrome 37 betas have not actually been made available in Chrome stable 37:
- arrows (don't actually change this, just pass #189)
- `String.fromCodePoint`
- `String.prototype.codePointAt`
- for..of

**Comment by webbedspace** [comment]
Also, two quick addenda about Firefox:
- FF 33 has global symbols
- FF 34 has destructuring rest

**Comment by kangax** [comment]
@webbedspace thanks! I noticed FF34 addition today as well (pushed). Will check the rest later.

**Comment by webbedspace** [comment]
Some further discrepancies (done with Opera 24):
- Does not support "Symbol : cannot coerce to string or number" (neither does Opera 23)
- "let : for-loop statement scope (strict mode)" causes the tab to crash (only Opera 24)
- _Does_ support "Symbol.iterator" (but Opera 23 does not)

Cross-reference: #227
