### ISSUE TITLE
Add Phantom 2.0

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#243]
Notable difference being presence of long-awaited `Function#bind`

**Comment by webbedspace** [comment]
I just ran [this unstable build of PJS 2](https://github.com/bprodoehl/phantomjs/releases), and it's just as predicted: all the results are identical to Safari 7.

**Comment by kangax** [comment]
Nice! Thanks. Wonder if we should add it now or wait for more stable builds?

**Comment by webbedspace** [comment]
I imagine it's still possible, though unlikely, for them to upgrade to a slightly later WebKit before release.

**Comment by webbedspace** [comment]
Just a note that Phantom 2.0's release will occur in the next day or two.

**Comment by kangax** [comment]
Nice! Good to know, thanks.
