### ISSUE TITLE
IE does not support Uint8ClampedArray

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#245]
Need to add a footnote mentioning this, and change its TypedArray support to "false".

**Comment by webbedspace** [comment]
Also, in the non-standard table, WebKit now supports the Error "stack" own property.

**Comment by webbedspace** [comment]
Also, note to myself: the IE data for hoisted function declaration is incorrect: it actually passed (i.e was compatible with IE 8) until IE11.
(I'll get around to doing a PR for these once #241 is resolved.)

**Comment by zloirock** [comment]
![...](http://i.imgur.com/VU19xH6.png?1)

**Comment by zloirock** [comment]
Looks like it was added in [this update](https://support.microsoft.com/en-en/kb/2929437).
