### ISSUE TITLE
Fix mixed content issues

### ISSUE THREAD

**Issue by mathiasbynens** [compat-table/compat-table#249]
Now would be a good time to switch to HTTPS. (No reason not to.)

https://kangax.github.io/compat-table/ currently has a few mixed content issues (see DevTools console).

**Comment by Yaffle** [comment]
@mathiasbynens , is there something secret on this page?

Can you please answer me on side question:
How do web browser react if website used one certificate and then changed this certificate to another one - will the show a warning message?
Thanks

**Comment by mathiasbynens** [comment]
> is there something secret on this page?

No, but I don’t see how that’s relevant.

> Can you please answer me on side question:
> How do web browser react if website used one certificate and then changed this certificate to another one - will the show a warning message?

There won’t be a warning message unless there is a certificate error. Certificates get renewed all the time. But again I don’t see how this is relevant to this issue – please elaborate?

**Comment by Yaffle** [comment]
> But again I don’t see how this is relevant to this issue – please elaborate?

Sorry, this is not relevant to that project.
May be I should read more about HTTPS.
Thanks for you answers.

The change is good.
