### ISSUE TITLE
iOS 8 may not support single-var multi-destructuring

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#253]
Take a look at [this commit](https://github.com/kangax/compat-table/commit/d943998bb2701928b84bc5f00ec2c869ce6beb12). Prior to this, I'd added a note to WebKit's destructuring results, which read as follows:

> WebKit fails to support multiple destructurings in a single `var` or `let` statement - for example, `var [a,b] = [5,6], {c,d} = {c:7,d:8};`

Now, WebKit has since fixed that, so I removed that in that commit. **BUT** iOS 8's codebase derives from a WebKit version prior to that one (as evidenced by the fact that it doesn't support `Math.sign`), so I believe the destructuring bug yet remains inside iOS 8.

I need someone to verify this by checking if this evaluates to true on iOS 8: 
`var [a,b] = [5,6], {c,d} = {c:7,d:8}; a === 5 && b === 6 && c === 7 && d === 8;`

**Comment by kangax** [comment]
You're right. I just checked that line on iPad running iOS8 on jsconsole.com and it returns `false`.

**Comment by webbedspace** [comment]
In that event, the note removed in that commit ought to be reinstated and attached to iOS 8's results.

Another thing I just remembered: the Map and Set note for WebKit (that it doesn't support `new Map([[key, val]])` or `new Set([obj1, obj2])`) surely also applies to iOS 8. You can check this with these lines (which both return true in FF Nightly):
- `(new Map([[Math, 1]])).has(Math)` (throws in current WK)
- `(new Set([Math])).has(Math)` (false in current WK)

(I'm using `Math` just as a convenient named object value in those examples.)
