### ISSUE TITLE
Partial results

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#275]
I'm giving this a shot:
![](http://i.imgur.com/fM4UYph.png)
Obviously I'll also have a fold-down button that reveals the sub-tests on click (with them hidden by default).

More info as it develops.

**Comment by kangax** [comment]
Looks amazing, thanks @webbedspace! Perhaps one thing that'd make sense is to also better visually separate titles of subtests and tests. Dim them a little? Smaller font size? Something else? What do you think? Indentation is already good; I just feel like something else is needed.

**Comment by webbedspace** [comment]
Question: what should partial results mean for the feature tally atop the browser columns? Should full conformance be the criterion for adding 1 to the feature tally? Partial conformance? 50/50? (Currently I've set it to the former, but maybe the latter is more informative.)

**Comment by kangax** [comment]
Hm, how about we just sum up all the numbers? Yes, partial tests will then have the same weight as singular-top-level ones, but... I think it's fine. What do you think?

**Comment by kornelski** [comment]
That's great. It would solve noise and imbalance that trivial Math features bring. 

For a grand total sum I suggest using only top-level groups, and count each group's score as percentage of sub-features it has (so if a browser supports half of all Math functions that's 0.5 point for the Math group).
