### ISSUE TITLE
ES6 spec incompatibility miscellany

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#284]
Considering ES5 now has the `parseInt` test, we might as well add some checks for these:
- [x] Duplicate property names are now permitted in strict mode: `(function(){'use strict';0,{a:1,a:1}}())`.
- [x] `new Date(NaN).toString()` yields `"Invalid Date"`
- <del>`[-1,0,1,NaN].sort(function(a){return a})` yields `[-1,0,NaN,1]` (Note that `[-1,0,1,NaN].sort()` still yields `[-1,0,1,NaN]`.</del>
- [x] A semicolon is no longer required at the end of a do-while statement.
- [x] The `= 0` bit of `for(var i = 0 in {})` is now illegal.
- <del>The `var e` bit of `try{}catch(e){var e;}` is now illegal.</del>
- [x] `Object.freeze`, `Object.seal`, `Object.preventExtensions`, `Object.getOwnPropertyDescriptors`, `Object.getPrototypeOf`, `Object.isExtensible`, `Object.isSealed`, `Object.isFrozen` and `Object.keys` no longer throw TypeError when passed a primitive.
- [x] `Boolean.prototype`, `Number.prototype`, `RegExp.prototype`, `Array.prototype`, `String.prototype` and `Date.prototype` no longer behave like instances of their constructors (hence, `Boolean.prototype.valueOf()` should throw, as should `RegExp.prototype.exec("")` and `Array.prototype.push(0)`).

**Comment by kangax** [comment]
Duplicate property names are now permitted in ES6 even under strict?!

**Comment by webbedspace** [comment]
https://esdiscuss.org/topic/duplicate-property-names-was-re-new

**Comment by anba** [comment]
Some minor corrections:

> [-1,0,1,NaN].sort(function(a){return a}) yields [-1,0,NaN,1] (Note that [-1,0,1,NaN].sort() still yields [-1,0,1,NaN].

This isn't actually correct, both, `[-1,0,NaN,1]` and `[-1,0,1,NaN]`, are valid return values for this case. It really depends on the underlying search algorithm (cf. InsertionSort for v8/SpiderMonkey, MinSort for JavaScriptCore, BinarySort for Nashorn, etc.). 

> The var e bit of try{}catch(e){var e;} is now illegal.

B.3.5 in Annex B allows this syntax.

> Boolean.prototype, Number.prototype, RegExp.prototype, Array.prototype, String.prototype and Date.prototype no longer behave like instances of their constructors (hence, Boolean.prototype.valueOf() should throw, as should RegExp.prototype.exec("") and Array.prototype.push(0)).

`Array.prototype.push(0)` does not throw in ES6.

**Comment by webbedspace** [comment]
> This isn't actually correct, both, `[-1,0,NaN,1]` and `[-1,0,1,NaN]`, are valid return values for this case. It really depends on the underlying search algorithm (cf. InsertionSort for v8/SpiderMonkey, MinSort for JavaScriptCore, BinarySort for Nashorn, etc.).

By "this case" do you mean `[-1,0,1,NaN].sort(function(a){return a})` and/or `[-1,0,1,NaN].sort()` ?

**Comment by anba** [comment]
> By "this case" do you mean [-1,0,1,NaN].sort(function(a){return a}) and/or [-1,0,1,NaN].sort() ?

I mean `[-1,0,1,NaN].sort(function(a){return a})`.
