### ISSUE TITLE
easier way to edit "tables"

### ISSUE THREAD

**Issue by tomByrer** [compat-table/compat-table#29]
What is the easiest & fastest way to add a column (eg new browser version) for your tables please?  I was about to add FF14 for you, & I looked at it,  & said, "Table layouts = cool, not cool I have to hand- edit a new column."  What tools do you use/recommend, or can this be automated please?  New browser versions are added every few months now.

**Comment by kangax** [comment]
I do it manually and yes it's painful. I'm open to suggestions if anyone knows anything.

**Comment by tomByrer** [comment]
I'm not sure either, but I found a great website where one can ask these kinds of topics, have you ever heard of it?
http://stackoverflow.com/questions/10249939/tools-to-collum-rows-on-html5-tables
;P

**Comment by Skalman** [comment]
I would probably prefer to generate the whole table in JavaScript. Are you interested in such a solution if I create one?

**Comment by kangax** [comment]
If we do it with Node.js, sure.

**Comment by Skalman** [comment]
With Node.js it couldn't be hosted on Github. Is a client-side table generation out of the question?

**Comment by kangax** [comment]
I meant to precompile it with Node.js before pushing to github.

**Comment by Skalman** [comment]
So do I hear you correctly in saying that client-side table generation is not ok and that Node.js must be used?

Alright. How would that work though? Is it even possible to prevent anybody from pushing without having precompiled first?

**Comment by kangax** [comment]
Well, since it's about the same effort, I don't see a need to rely on JS
here. Is something wrong with "precompiling" table with Node.js before
pushing to github?

**Comment by Skalman** [comment]
That means that you cannot make a pull request via Github, such as the one I did before, where you just change a single value. That said, Node.js works too. I'll look into it.

**Comment by kangax** [comment]
For pull requests, you would need to change single value followed by `node
build.js` (or whatever). Shouldn't be much trouble. What do you think?

**Comment by Skalman** [comment]
Not a big problem, but it means that I have to download everything to my own computer and run it. The pull request I did was only through Github, no running node, no cloning it to a local repository. I'm going with Node, though. :-)

**Comment by kangax** [comment]
I see what you mean. I don't recall ever using web interface for pull
requests so completely forgot about that :)

**Comment by kangax** [comment]
Fixed in https://github.com/kangax/es5-compat-table/commit/e9ff07aa803972b425fdc04828664b8420db4b2e
