### ISSUE TITLE
Categorising the ES6 tests

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#292]
How does this sound?

Optimisation:
- proper tail calls

New bindings:
- let
- const
- block-level function

New function constructs:
- arrows
- generators
- class
- super

Literal extensions:
- rest
- object literal extensions
- octal and binary
- unicode code point escapes

Assignment / call extensions:
- defaults
- destructuring
- template strings

Iterator consumers:
- for-of loops
- spread

New standard built-ins:
- Map
- Set
- WeakMap
- WeakSet
- Typed Arrays
- Promise
- Proxy
- Reflect

Built-in extensions:
- Object static methods
- Function 'name'
- Function#toMethod
- String static methods
- String proto methods
- Array static methods
- Array proto methods
- RegExp y/u flags
- RegExp proto methods
- Number properties
- Math methods

These labels don't need to appear on the table itself.

"Iterator consumers" is maybe a bit of a misnomer because `yield *`, `Array.from`, `Map`/`Set`/`WeakMap`/`WeakSet` constructors, `Promise.all` and `Promise.race` also consume iterators.

**Comment by kangax** [comment]
I'm not opposed to the idea. Would this make things convenient in code or to have a better overview for a user?

**Comment by kangax** [comment]
@webbedspace related question: should we perhaps move "super" under "class"? I think it could make sense.

**Comment by webbedspace** [comment]
I've kept `super` separate because technically it's usable outside of class syntax (just write it in a normal function and then call Function#toMethod() to bind it to an object and its prototype hierarchy) and also because it has its own subtests... but then, all of those currently require the presence of class syntax to pass, so I _guess_ it may be more sensible to move it. (Or rewrite the tests to fallback to #toMethod, even though nobody will implement it before class anyway.)

**Comment by kangax** [comment]
I see. Didn't know it's usable outside of `class`. In that case I'm more or less indifferent to whether we should have it separate or not.
