### ISSUE TITLE
incorrect border on non-standard table

### ISSUE THREAD

**Issue by michaelficarra** [compat-table/compat-table#3]
Because of the [two separate script tags](https://github.com/kangax/es5-compat-table/blob/7e937366dec6ebb562d1/non-standard/index.html#L516-529) in the row marked `let`, the css selector `td:nth-child(3) { outline: #AAF solid 3px; }` is not being applied to the "this browser" column for that row.

**Comment by Skalman** [comment]
I believe that this was corrected a while back. This bug should be closed.

**Comment by kangax** [comment]
@Skalman thanks

**Comment by michaelficarra** [comment]
Yep, it looks like the CSS was changed to

``` css
td:nth-of-type(2) {
  outline: #aaf solid 3px;
}
```
