### ISSUE TITLE
Explicit [Symbol.iterator] method tests

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#318]
The following have iterator methods (keyed to Symbol.iterator):
- arguments (as own property, = Array#values)
- String
- Map (= #entries)
- Set (= #values)
- Array (= #values)
- TypedArrays (= #values)

Currently these are checked indirectly - the tests for `for..of`, spread, and so forth all imply Array#[Symbol.iterator], and spread's tests inply String#[Symbol.iterator]. (#304 asserts that all iteration tests should check at least Array (iterable object), String (iterable primitive), and generic iterables (iterable user-made object).) But, maybe explicit tests for each are necessary.

arguments's own property can be a separate single test, and the others fit in under their classes. As noted above, some are specced to be identical (`===`) to their #values methods, but this needn't be necessary to check, as it's fairly insignificant an aspect.

**Comment by zloirock** [comment]
``` js
// %IteratorPrototype%[Symbol.iterator]:
ArrayIterator#[Symbol.iterator]
StringIterator#[Symbol.iterator]
SetIterator#[Symbol.iterator]
MapIterator#[Symbol.iterator]
EnumerateIterator#[Symbol.iterator]
```

?

**Comment by ljharb** [comment]
@webbedspace imo the === requirement is something that should be checked, and that some engines definitely violate - nothing in the spec is insignificant :-)
