### ISSUE TITLE
Add Facebook's jstransform

### ISSUE THREAD

**Issue by appsforartists** [compat-table/compat-table#319]
[jstransform](https://github.com/facebook/jstransform/tree/master/visitors) powers the transformer that's built-in to React's toolset.  Given React's popularity and the ease of adding the `harmony` flag to the workflow of a React project, it'd be nice if it was listed along with the other transpilers.

[Here's a list of the features it supports](https://github.com/facebook/jstransform/tree/master/visitors).

**Comment by webbedspace** [comment]
I'm not sure whether jstransform's ES6 transformations are exactly the same as the ones React uses - if anything should be listed, it should specifically be [react-tools](https://www.npmjs.org/package/react-tools), which is based off jstransform.

**Comment by appsforartists** [comment]
React just [passes through jstransform](https://github.com/facebook/react/blob/master/vendor/fbtransform/visitors.js).

**Comment by kangax** [comment]
Wait, is this different from JSX (which @webbedspace just added earlier)?

**Comment by appsforartists** [comment]
Nope, that's it.
