### ISSUE TITLE
spread test in es6 seems wrong

### ISSUE THREAD

**Issue by ianb** [compat-table/compat-table#32]
Here's the spread(...) test:

``` javascript
test((function () {
          try {
            return eval('(function(args) { return typeof args !== "undefined"; })()');
          } catch(error) {
            return false;
          }
        })())
```

Maybe you meant `eval('(function(args) { return typeof args !== "undefined"; })(...[1])');` ?

**Comment by kangax** [comment]
Thanks! Fixed in https://github.com/kangax/es5-compat-table/commit/d8523fc2ad8f0b53e1fb23af8c04fce3ef8bae23
