### ISSUE TITLE
String#contains -> String#includes

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#323]
https://github.com/domenic/Array.prototype.includes/commit/4b6b9534582cb7991daea3980c26a34af0e76c6c

**Comment by kangax** [comment]
thanks to @mathiasbynens for the [heads up](http://twitter.com/mathias/status/535350698918297600)

**Comment by zloirock** [comment]
- https://bugzilla.mozilla.org/show_bug.cgi?id=1101817

**Comment by webbedspace** [comment]
OK, this is done now.

**Comment by kangax** [comment]
Hey @webbedspace, I gave you access to the repo, so you can close/reopen/etc. things as you see fit. I'm just asking to please still open PR's for any non-trivial changes for me (and others) to look through. And as always, thanks for all the help!

**Comment by webbedspace** [comment]
Thanks, will do.
