### ISSUE TITLE
Incorrect "generic iterables" tests when native generators are present

### ISSUE THREAD

**Issue by anba** [compat-table/compat-table#329]
The following test cases are invalid:
- for..of loops - with instances of generic iterables
- generators - yield *, instances of iterables
- destructuring - with instances of generic iterables
- spread (...) operator - with instances of iterables, in calls
- spread (...) operator - with instances of iterables, in arrays

The test case failure can be reduced to:

``` javascript
var iterable = __createIterableObject(1, 2, 3);
var iterator = Object.create(iterable)[Symbol.iterator]();
iterator.next(); // <- throws a TypeError
```

The TypeError gets emitted because the `iterator` does not pass the tests in 25.3.3.2 GeneratorValidate.

**Comment by jorendorff** [comment]
Yeah, the complaint is correct. The test is invalid; per spec it should throw a TypeError.

**Comment by webbedspace** [comment]
OK, just to clarify: it's not possible, as currently specced, to create a user-defined inheritable iterator without access to `Symbol.iterator`?

**Comment by anba** [comment]
Hmm, it depends on what needs to be tested here.

Inheritable _iterators_ can be tested with:

``` javascript
let iterator = function*() { yield 1; yield 2; yield 3; }();
iterator.next = iterator.next.bind(iterator);
let inherited = Object.create(iterator);
for (let v of inherited) print(v); // Prints 1, 2, 3
```

For inheritable _iterables_ it depends on the type of iterables. For example array and argument object don't need any special set-up since the array iterator type does perform any internal type checking:

``` javascript
let iterable = [1, 2, 3]; // Or: let iterable = (function(){ return arguments })(1, 2, 3);
let inherited = Object.create(iterable);
for (let v of inherited) print(v); // Prints, 1, 2, 3
```

For string objects it's only necessary to bind `toString`.

``` javascript
let iterable = new String("123");
iterable.toString = iterable.toString.bind(iterable); // Or: Provide own toString method on inherited
let inherited = Object.create(iterable);
for (let v of inherited) print(v); // Prints "1", "2", "3"
```

The other built-in iterables (Set, Map, TypedArrays, Module namespace objects? [bug 3381](https://bugs.ecmascript.org/show_bug.cgi?id=3381)) are non-generic, so creating derived object through `Object.create` and then simply calling `Symbol.iterator` on that object won't work. Unless you bind `Symbol.iterator`, of course:

``` javascript
let iterable = new Set([1, 2, 3]);
iterable[Symbol.iterator] = iterable[Symbol.iterator].bind(iterable);
let inherited = Object.create(iterable);
for (let v of inherited) print(v); // Prints 1, 2, 3
```

**Comment by webbedspace** [comment]
The primary thing I want the test to check is "can the syntax access the iterable's `Symbol.iterator` method from the prototype chain". To that end, I guess it'll fail implementations that don't support `Symbol.iterator`. (#335 currently does that, albeit somewhat indirectly.)
