### ISSUE TITLE
More non-standard features

### ISSUE THREAD

**Issue by mathiasbynens** [compat-table/compat-table#33]
Check this out: http://mxr.mozilla.org/mozilla-central/source/js/src/tests/ecma_5/extensions/extension-methods-reject-null-undefined-this.js#18

E.g. `String#quote`, `toJSON` on most objects, `toSource` on most objects, etc.

**Comment by kangax** [comment]
Ah, interesting.

I suppose we can add `String#quote`.

`toSource` — we're already testing it on both Object's and Function's (the
test is: `test('toSource' in (function(){}) && 'toSource' in ({}))`)

`toJSON` on all objects — I guess it can be called non-standard. AFAIR,
spec encourages objects to have `toJSON`, and `JSON.stringify` invokes
those methods on objects when available. Mozilla must be taking advantage
of it?

On Mon, Jul 2, 2012 at 1:29 PM, Mathias Bynens <
reply@reply.github.com

**Comment by mathiasbynens** [comment]
So no `String#quote` in the table after all?

**Comment by kangax** [comment]
Sure why not, added a separate issue for that —
https://github.com/kangax/es5-compat-table/issues/49
