### ISSUE TITLE
Invalid test case for TDZ in default function parameters with var-declaration

### ISSUE THREAD

**Issue by anba** [compat-table/compat-table#330]
The third test case in "default function parameters - temporal dead zone" is incorrect.

``` javascript
(function(a=function(){ return b; }){ var b = 1;}())
```

The default parameter is never executed and even if the code is changed to:

``` javascript
(function(a=function(){ return b; }()){ var b = 1;}())
```

It will only try to resolve the global variable "b", which will most likely result in a ReferenceError, but that's not TDZ related.

**Comment by webbedspace** [comment]
OK, I'll rewrite it like so and make it a separate test ("separate scope"):

``` js
(function(a=function(){ return typeof b === 'undefined'; }){ var b = 1; return a(); }())
```
