### ISSUE TITLE
Invalid tests in: function "name" property

### ISSUE THREAD

**Issue by anba** [compat-table/compat-table#332]
There are multiple issues for the 'function "name" property' tests.

Subtest: object methods (function)
- The name for `o.qux` is the empty string instead of "qux" (IsIdentifierRef(o.qux) is false, cf. 12.14.4 step 1.e)

Subtest: accessor properties
- Missing mandatory parameter for accessor function
- Typo when accessing `o.set`

Subtest: symbol-keyed methods
- The name for `o[sym].name` is empty instead of "[foo]" (IsIdentifierRef(o[sym]) is false, cf. 12.14.4 step 1.e)

Subtest: object methods (class)
- The name for `o.qux` is the empty string instead of "qux" (IsIdentifierRef(o.qux) is false, cf. 12.14.4 step 1.e)

Subtest: isn't writable, is configurable
- Anonymous function expressions don't have an own "name" property in ES6

``` diff
--- a/data-es6.js
+++ b/data-es6.js
@@ -3407,16 +3407,16 @@ exports.tests = [
         o.qux = function(){};
         return o.foo.name === "foo" &&
                o.bar.name === "baz" &&
-               o.qux.name === "qux";
+               o.qux.name === "";
       */},
       res: {},
     },
     'accessor properties': {
       exec: function() {/*
-        var o = { get foo(){}, set foo(){} };
+        var o = { get foo(){}, set foo(x){} };
         var descriptor = Object.getOwnPropertyDescriptor(o, "foo");
         return descriptor.get.name === "get foo" &&
-               descriptor.get.name === "set foo";
+               descriptor.set.name === "set foo";
       */},
       res: {},
     },
@@ -3439,7 +3439,7 @@ exports.tests = [
         o[sym] = function(){};
         o[sym2] = function(){};

-        return o[sym].name === "[foo]" &&
+        return o[sym].name === "" &&
                o[sym2].name === "";
       */},
       res: {},
@@ -3477,7 +3477,7 @@ exports.tests = [
         o.qux = class {};
         return o.foo.name === "foo" &&
                o.bar.name === "baz" &&
-               o.qux.name === "qux";
+               o.qux.name === "";
       */},
       res: {},
     },
@@ -3498,9 +3498,7 @@ exports.tests = [
     'isn\'t writable, is configurable': {
       exec: function () {/*
         var descriptor = Object.getOwnPropertyDescriptor(function(){},"name");
-        return descriptor.enumerable   === false &&
-               descriptor.writable     === false &&
-               descriptor.configurable === true;
+        return descriptor === void 0;
       */},
       res: {},
     },
```

**Comment by webbedspace** [comment]
Thanks. However your fix for 'isn't writable, is configurable' I think misses the original point of the test. I'll instead do this:

``` diff
-         var descriptor = Object.getOwnPropertyDescriptor(function(){},"name");
+         var descriptor = Object.getOwnPropertyDescriptor(function f(){},"name");
```

Also I'll replace the symbol-keyed methods test with this:

``` js
        var sym1 = Symbol("foo");
        var sym2 = Symbol();
        var o = {
          [sym1]: function(){},
          [sym2]: function(){}
        };

        return o[sym].name === "[foo]" &&
               o[sym2].name === "";
```

(I was loathe to do this originally because I tried not to unduly tie this test to the existence of computed properties, but according to your findings, these features are unavoidably connected.)

**Comment by anba** [comment]
> (I was loathe to do this originally because I tried not to unduly tie this test to the existence of computed properties, but according to your findings, these features are unavoidably connected.)

Yes, computed properties are necessary to test symbols as inferred function names.
