### ISSUE TITLE
ES7: Add object rest destructuring

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#337]
https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-09/sept-25.md#58-object-rest-destructuring-and-spread-properties

**Comment by kangax** [comment]
I've heard Babel (ex-6to5) implements them (but didn't check myself). Just fyi.

**Comment by flying-sheep** [comment]
1. [facebook/jstransform supports them](https://github.com/facebook/jstransform/blob/master/visitors/es7-rest-property-helpers.js).
2. [babel does too](https://github.com/babel/babel/issues/200) ([demo](https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=false&loose=false&spec=false&code=let%20{tags%2C%20dropDownLabel%2C%20...other}%20%3D%20this.props%3B))

**Comment by kangax** [comment]
@zloirock would be awesome if you could add this as well ^_^

**Comment by zloirock** [comment]
@kangax added, #471 :)
