### ISSUE TITLE
Chrome 22 doesn’t seem to support callable regex

### ISSUE THREAD

**Issue by mathiasbynens** [compat-table/compat-table#34]
The “CH 7-10” column says callable regex is supported, but I’m getting a “NO” in the “this browser” column when using Chrome Canary v22.0.1187.0. I’m not sure if this is a typo, a false positive in the test, or a regression in Chrome. I haven’t tested other Chrome versions.

**Comment by kangax** [comment]
This is a deliberate change in webkit. They removed callable regexes recently, together with Mozilla as one of those non-standard, hazardous, hard-to-optimize (and [hairy in other ways](http://whereswalden.com/2011/03/06/javascript-change-in-firefox-5-not-4-and-in-other-browsers-regular-expressions-cant-be-called-like-functions/)) features.

We'll need to update table with newer Chrome results.
