### ISSUE TITLE
Io.js

### ISSUE THREAD

**Issue by topaxi** [compat-table/compat-table#351]
Any plans to add the node fork io.js?

As far as i know, they're using a newer v8 version which should support a lot of new es features :)

**Comment by topaxi** [comment]
https://github.com/iojs/io.js

**Comment by kangax** [comment]
+1 from me. Curious to see just how much it's ahead of current Node.

**Comment by teppeis** [comment]
This is result of io.js v0.12 (vs. node v0.10 vs. node v0.11)
- https://gist.github.com/teppeis/afe8858ac9d43615a66c
- https://docs.google.com/spreadsheets/d/1NM_zGzTODZt6pCW4mCB8c74KuyZLXhxUnGfQIHh5KD4/edit#gid=0

**Comment by kangax** [comment]
That's great, thanks @teppeis! Would you be able to submit a PR?

**Comment by ruimarinho** [comment]
@kangax, added a PR (#387) with the results from io.js upcoming 1.0.0 release.
