### ISSUE TITLE
Destructuring nested-rest is illegal

### ISSUE THREAD

**Issue by Swatinem** [compat-table/compat-table#353]
You have nested-rest listed as one destructuring feature. Although it is illegal per the ES6 spec. I must know, I fell into the same trap when actually implementing destructuring-rest in spidermonkey. :-D

See the discussion here: https://bugzilla.mozilla.org/show_bug.cgi?id=933276#c27

**Comment by webbedspace** [comment]
My source for adding this test was [the final line in this section](https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-11/nov-18.md#41-es6-draft-status-update). Is that an inaccurate reading @rwaldron ?

**Comment by Swatinem** [comment]
Well the draft 28 still disallows it. And it does not even make sense to have, haha…

So, need some clarification there.

**Comment by webbedspace** [comment]
It actually makes sense if you consider the example:

``` js
var a = [1, 2, 3], first, last;
[first, ...[a[2], last]] = a;
return first === 1 && last === 3 && (a + "") === "1,2,2";      
```

If the second line was just `[first, a[2], last] = a;`, then the `a[2]` set in the middle would modify `a` in-place, causing `last` to become 2 instead of 3. It would "desugar" to:

``` js
first = a[0]; // 1
a[2] = a[1]; // 2
last = a[2]; // 2
```

Whereas, with this syntax, it becomes:

``` js
first = a[0]; // 1
_temp = a.slice(1); // [2,3]
a[2] = _temp[0]; // 2
last = _temp[1]; // 3
```

Now, whether this distinction is really a big deal or not is another question.

**Comment by Swatinem** [comment]
Certainly an interesting case…

**Comment by rwaldron** [comment]
Here's the relevant change: 

![AssignmentRestElement[Yield] : ... DestructuringAssignmentTarget](http://i.gyazo.com/3683dec54a9376ca7665e3bad8f23b1c.png)

Under: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-iteratordestructuringassignmentevaluation

**Comment by Swatinem** [comment]
Thanks for clarifying. I see jorendorffs online version was updated to draft 29 in the meantime.
