### ISSUE TITLE
ES I18n API

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#358]
Inspired by https://whereswalden.com/2014/12/11/introducing-the-javascript-internationalization-api/ — and considering that Chrome has some support for that as well — I'm thinking perhaps we can include it somewhere in compat tables (non standard? es7? another table?)

**Comment by keithamus** [comment]
I've been looking into the i18n api quite in depth recently, and today came here looking for a nice table about compat. I'm happy to implement this (I think is should be a new table) based on your existing work. If you give the say so I'll get working on a preliminary PR for this.

**Comment by kangax** [comment]
That would be great! Definitely go for it.

**Comment by ruimarinho** [comment]
Great idea. FYI, node 0.12 will ship with `Intl` support by default while io.js may or may not ship it on 1.0.0.
