### ISSUE TITLE
Remove "existence not conformance" message?

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#361]
```
"Please note that some of these tests represent existence, not functionality or full conformance."
```

Should we remove this message now that we have quite extensive tests? Doesn't seem to serve any purpose now.

/cc @webbedspace

**Comment by webbedspace** [comment]
Well, at least several tests for new class methods only test for existence (String static methods, Function#toMethod, most of the Array methods, all of the Math methods*) so it should probably stay for now.

*(I tried a [pullreq](https://github.com/kangax/compat-table/pull/263) to add functionality checks for those but I fear I don't have the expertise to ensure it was actually correct)
