### ISSUE TITLE
Is EchoJS a compiler or a runtime?

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#362]
@toshok Does EchoJS actually compile ES6 code to ES5? The repo's readme does not say, beyond describing it as a "compiler and runtime for EcmaScript".

**Comment by toshok** [comment]
EchoJS compiles ES6 directly to native code.

**Comment by webbedspace** [comment]
OK then, I guess it should be classified under "server-ish" because its compiled output isn't usable in the browser.
