### ISSUE TITLE
IE supports Error .stack on thrown errors

### ISSUE THREAD

**Issue by simevidas** [compat-table/compat-table#367]
The feature test for Error .stack is broken in IE as this browser only provides a "stack" property if the error is actually thrown:

![capture](https://cloud.githubusercontent.com/assets/716405/5428075/440dabe2-83b6-11e4-8bee-bad869799378.PNG)

![capture](https://cloud.githubusercontent.com/assets/716405/5428093/b75988a0-83b6-11e4-939b-7d7ac602c2c2.PNG)

**Comment by kangax** [comment]
Thanks @simevidas, good catch! PR is definitely welcome.

**Comment by simevidas** [comment]
Hm, couldn’t get the build script to run. (I did `npm install`, then tried `node build.js` and `node ./`.) I committed the edit in case you want to pull it. I know, it’s not much ^_^ https://github.com/simevidas/compat-table/commit/62f9496a37d2e13f4742a59fd01de57bea6bb3cc

**Comment by kangax** [comment]
Fixed manually, thanks!
