### ISSUE TITLE
Add destructuring to ES6 compat table

### ISSUE THREAD

**Issue by juandopazo** [compat-table/compat-table#37]
Hi! A test for destructuring (see http://wiki.ecmascript.org/doku.php?id=harmony:destructuring) is missing. Maybe something like this could work:

``` JavaScript
test((function () {
  try {
    return eval('(function() { var { foo } = { foo: 5 }; ; return typeof foo === "number" })()');
  } catch(error) {
    return false;
  }
})())
```

**Comment by kangax** [comment]
Sounds good! I'll get to it when I get a chance, unless someone makes pull request first :)
