### ISSUE TITLE
add Facebook's regenerator

### ISSUE THREAD

**Issue by jokeyrhyme** [compat-table/compat-table#370]
https://github.com/facebook/regenerator

It would be interesting to see how regenerator compares to traceur, etc.

Love your work! <3

**Comment by webbedspace** [comment]
Regenerator isn't, I feel, worth a column by itself because it only polyfills one feature (generators). In fact, 6to5 has it as a single dependency.

**Comment by jokeyrhyme** [comment]
Ah, okay. I misunderstood the purpose of regenerator. Cheers!
