### ISSUE TITLE
6to5 class extends support

### ISSUE THREAD

**Issue by jamiebuilds** [compat-table/compat-table#379]
``` js

class C extends Array {}
var c = new C();
return c instanceof Array
  && Array.isPrototypeOf(C)
  && Array.prototype.isPrototypeOf(C.prototype);
```

[This is returning true](https://6to5.org/repl.html#?code=class%20C%20extends%20Array%20%7B%7D%0Avar%20c%20%3D%20new%20C%28%29%3B%0Aconsole.log%28%0A%20%20c%20instanceof%20Array%0A%20%20%26%26%20Array.isPrototypeOf%28C%29%0A%20%20%26%26%20Array.prototype.isPrototypeOf%28C.prototype%29%0A%29%3B&experimental=true&playground=true&evaluate=true), I'm not sure why it's being reported incorrectly by compat-table.

**Comment by sebmck** [comment]
The note refers to `Requires native support for Object.prototype.__proto__` which is valid in my opinion.

**Comment by webbedspace** [comment]
All compiler/polyfill support is measured by running the resulting code on IE9, the quintessential "zero native ES6 support" platform.

**Comment by Yaffle** [comment]
```
class C extends Array {}
var c = new C();
c.push(1);
c.length = 0;
alert(c[0]);
```

**Comment by sebmck** [comment]
@Yaffle I get the same in Chrome Canary as 6to5.

**Comment by Yaffle** [comment]
or
```
class C extends Array {}
var c = new C();
c[0] = 0;
alert(c.length);
```
see #105 & #169

**Comment by Yaffle** [comment]
ah, sorry, this test ("extends") is for basic extends support...
May be it is better to change Array to `class Foo {}`

**Comment by webbedspace** [comment]
This test fails in IE10, so the level of support it offers as a polyfill is not comprehensive enough for production purposes. The attached footnote explains the reason.
