### ISSUE TITLE
ES6 Pragmas test?

### ISSUE THREAD

**Issue by rwaldron** [compat-table/compat-table#38]
I'm not sure I understand the ES6 "pragmas" test, as there is nothing in ES6 that matches:

``` js
use strict;
```

(not to be confused with the string version of the same words)

**Comment by kangax** [comment]
This was part of the initial contribution by @paulmillr, IIRC. Has [this proposal](http://wiki.ecmascript.org/doku.php?id=harmony:pragmas) never made it to ES6?

**Comment by rwaldron** [comment]
This proposal was dropped implicitly when ES6 committed to 1JS: https://mail.mozilla.org/pipermail/es-discuss/2011-December/019112.html

**Comment by rwaldron** [comment]
Also, `typeof null === "null"` is gone too, for the same reason

**Comment by kangax** [comment]
Gotcha! Thanks, Rick. I'll remove in a bit, when I have some time.

**Comment by rwaldron** [comment]
I can send a patch, I have some other updates for you :)

**Comment by paulmillr** [comment]
gh-39
