### ISSUE TITLE
accuracy of Math.cbrt, Math.expm1, Math.log1p

### ISSUE THREAD

**Issue by Yaffle** [compat-table/compat-table#392]
```
var error = function (x, value) {
  return Math.abs(1 - x / value) / 2.220446049250313e-16; // error in number of ulps (http://en.wikipedia.org/wiki/Unit_in_the_last_place)
};
```
## Firefox < 48 on Windows:

https://bugzilla.mozilla.org/show_bug.cgi?id=933257
https://bugzilla.mozilla.org/show_bug.cgi?id=897634
```
error(Math.log1p(0.0006516748007717887), 0.0006514625529548382) > 500;
error(Math.expm1(0.00001), 0.000010000050000166668) > 43000;
error(Math.cbrt(-3.9355663969868275e+307), -3.401489081587483e+102) > 50;
error(Math.asinh(-0.0005), -0.000499999979166669) > 100; // (caused by issues with `expm1` and `log1p` on Windows)
error(Math.atanh(-0.0005), -0.0005000000416666729) > 100; // (caused by issues with `expm1` and `log1p` on Windows)
```

## Firefox
```
Math.exp(1) !== Math.E
```

## Chrome < 54 on Windows:

https://code.google.com/p/v8/issues/detail?id=3468
https://code.google.com/p/v8/issues/detail?id=3509

```
error(Math.exp(-707.9999999999998), 3.30755300363916e-308) > 250;
Math.acosh(1e+308) === Infinity;
Math.asinh(1e+300) === Infinity;
Math.atanh(1e-300) === 0;
```
## Konqueror 4.13 (Ubuntu):

https://github.com/KDE/kjs/blob/master/src/kjs/math_object.cpp

```
   Math.expm1 == undefined && Math.exmp1 != undefined
   Math.LOG10E !== 0.4342944819032518 // 0.43429448190325176
   Math.abs(+0) === 0 && 1 / Math.abs(+0) < 0
   Math.hypot.length === 0
   Math.hypot(1e200, 1e200) === 1 / 0 // overflow and underflow issues

   Math.asinh == undefined;
   Math.clz32 == undefeined;
   Math.imul() == undefined;
```
## buggy `Math.round` in Safari 10 / Mobile Safari 10  / IE 11 / Edge 13 / Opera 12 / Konqueror 4.13:

```
Math.round(0.49999999999999994) !== 0
```
## `Math.pow` issue in Firefox, Chrome, Safari, Edge when the second argument is an integer:

 https://code.google.com/p/v8/issues/detail?id=3599
 https://bugzilla.mozilla.org/show_bug.cgi?id=618251

```
error(Math.pow(10, 305), 1e+305) > 2;
error(Math.pow(10, 308), 1e+308) > 2;
error(Math.pow(9767, 77), 1.627839019440664e+307) > 8
error(Math.pow(1 + Math.pow(2, -27), Math.pow(2, 31) - 1), 8886109.924647752) > Math.pow(2, 28)
```
## Chrome Mobile 52 (Android 5.1):

```
Math.pow(11, Math.pow(11, 9)) === 0;
```
## Mobile Safari 10 (iOS 9.2):

```
Math.expm1(709.782712893384) === -1;
// note: Math.expm1(709.7827128933839) === 1.7976931348620688e+308
```
## [es6-shim](https://github.com/paulmillr/es6-shim/blob/master/es6-shim.js):

```
nothing
```
## [core-js](https://github.com/zloirock/core-js/tree/master/library/modules):

```
error(Math.acosh(1 + Number.EPSILON), 2.1073424255447017e-8) > 1e+7;
Math.asinh(1e-300) === 0;
Math.asinh(1e+300) === Infinity;
Math.atanh(1e-300) === 0;
error(Math.cbrt(1e-300), 1e-100) > 50;
Math.cosh(710) === Infinity;
error(Math.expm1(1e-6), 0.0000010000005000001665) > 1e+5;
error(Math.log1p(1e-8), 9.999999950000001e-9) > 1e+7;
+ Math.sinh, Math.tanh (because of expm1)
```
## [Traceur](https://github.com/google/traceur-compiler/blob/master/src/runtime/polyfills/Math.js) AND [MDN's polyfills](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math):

```
Math.acosh(1e+308) === Infinity;
error(Math.acosh(1 + Number.EPSILON), 2.1073424255447017e-8) > 1e+7;
Math.asinh(1e-300) === 0;
Math.asinh(1e+300) === Infinity;
Math.atanh(1e-300) === 0;
error(Math.cbrt(1e-300), 1e-100) > 50;
Math.cosh(710) === Infinity;
Math.sinh(710) === Infinity;
Math.sinh(1e-300) === 0;
Math.tanh(1e-300) === 0;
Math.tanh(1e+300) !== Math.tanh(1e+300);
Math.expm1(1e-300) === 0;
Math.log1p(1e-300) === 0;
```
## [Closure](https://github.com/google/closure-compiler/tree/master/src/com/google/javascript/jscomp/js/es6/math):

```
Math.acosh(1e+308) === Infinity;
error(Math.acosh(1 + Number.EPSILON), 2.1073424255447017e-8) > 1e+7;
Math.asinh(1e-300) === 0;
Math.asinh(1e+300) === Infinity;
error(Math.cbrt(1e-300), 1e-100) > 50;
Math.cosh(710) === Infinity;
Math.sinh(710) === Infinity;
Math.sinh(1e-300) === 0;
Math.tanh(1e-300) === 0;
Math.hypot(0, 0) !== Math.hypot(0, 0)
Math.hypot(1, Infinity) !== Math.hypot(1, Infinity)
```

**Comment by ljharb** [comment]
Nothing in the spec defines the implementation or epsilon of the Math functions ( https://people.mozilla.org/~jorendorff/es6-draft.html#sec-function-properties-of-the-math-object ) It specifically says "For other argument values, these functions are intended to compute approximations to the results of familiar mathematical functions, but some latitude is allowed in the choice of approximation algorithms."

What compatibility is necessary to test here?

**Comment by Yaffle** [comment]
@ljharb , possibly, spec authors should update spec, otherwise it is not very useful to have Math.XXX without accuracy guaranties AND some browsers have good results.

Although, I am not using those particular functions, but I am interesting in accuracy for others.

**Comment by kangax** [comment]
@Yaffle you should bring it up on es-discuss

**Comment by Yaffle** [comment]
@kangax 
Every discussion of this on es-discuss ends with "Need to bring in experts."
https://mail.mozilla.org/pipermail/es-discuss/2014-August/038634.html

**Comment by Yaffle** [comment]
more bugs for ES3:

`Math.round(0.49999999999999994) === 1` in FF 34 (fixed in FF 35), IE 11, Opera 12

precision of `Math.exp` is not good in Chrome - https://code.google.com/p/v8/issues/detail?id=3468

**Comment by Yaffle** [comment]
@ljharb, 

I checked:

Chrome 39.0
Windows XP 

Chrome 39.0
Android 5.0

Chrome 39.0
Android 4.4

Chrome 39.0
Windows 8 

Chrome 39.0
Mac OS X 10.10

Chrome 39.0
Linux 

Chrome Mobile 39.0
Android 5.0

Chrome Mobile iOS 39.0

Mobile Safari 8.2
iOS 8.1 

Firefox 35.0
Windows 7 

Firefox 35.0
Windows 8 

Firefox 35.0
Windows XP

Safari 8.0
Mac OS X 10.10 

And cannot see such big "latitude" results for `Math.sinh`, `Math.acos`, `Math.log1p`, `Math.expm1` and `Math.hypot`, as in es6-shim and core-js.

**Comment by zloirock** [comment]
@Yaffle You can propose better implementation.

**Comment by Yaffle** [comment]
I'm sorry for wasting your time

**Comment by zloirock** [comment]
@Yaffle I'm serious. I'm not specialist in math. You can propose your implementation math functions for these libraries.

**Comment by Yaffle** [comment]
@zloirock 
https://bugs.ecmascript.org/show_bug.cgi?id=309#c16
this comment suggest to use for `Math.log1p`:
```
Math.log1p = function (x) {
  x = Number(x);
  return (1 + x) - 1 === 0 ? x : x * (Math.log(1 + x) / ((1 + x) - 1));
};
```
my tests shows, that result is almost same as for native `log1p` in Chrome

**Comment by Yaffle** [comment]
Math.tanh:
```
Math.tanh = function (x) {
  x = Number(x);
  var a = Math.expm1(x);
  var b = Math.expm1(-x);
  if (a === Infinity) {
    return +1;
  }
  if (b === Infinity) {
    return -1;
  }
  return (a - b) / (Math.exp(x) + Math.exp(-x));
};
```

Math.acosh - almost same as https://github.com/google/traceur-compiler/blob/92112b031a3c8d37bc7e19857467a21eb5f38166/src/runtime/polyfills/Math.js#L136, but with division by Math.E to avoid bug for Math.acosh(Number.MAX_VALUE)
```
Math.acosh = function (x) {
  x = Number(x);
  if (x < 1) return NaN;
  if (x !== x || 1 / x == 0) return x;
  return Math.log(x / Math.E + Math.sqrt(x + 1) * Math.sqrt(x - 1) / Math.E) + 1;
};
```

**Comment by zloirock** [comment]
@Yaffle Thanks for `Math.tanh` and `Math.acosh`. I fixed them (but not forced for v8) and `Math.hypot`.

**Comment by Yaffle** [comment]
More implementations almost correct on my test values (WARNING: I do not know how wrong are those functions, And only `log1p` is smart and from https://bugs.ecmascript.org/show_bug.cgi?id=309#c16 ):

```

Math.round = function (x) {
  x = Number(x);
  if (Math.abs(x) < 0.5) {
    return x === 0 ? x : (x < 0 ? -0 : +0);
  }
  var y = Math.floor(x + 0.5);
  return y - x === 1 ? x : y;
};

Math.log1p = function (x) {
  x = Number(x);
  if (x === 1 / 0) {
    return x;
  }
  return (1 + x) - 1 === 0 ? x : x * (Math.log(1 + x) / ((1 + x) - 1));
};

Math.expm1 = function (x) {
  if (x !== x || x === 0) {
    return x;
  }
  if (Math.abs(x) > 1 / 2) {
    return Math.exp(x) - 1;
  }
  var t = x;
  var s = 0;
  var n = 1;
  while (s + t !== s) {
    s += t;
    n += 1;
    t *= x;
    t /= n;
  }
  return s;
};

Math.sinh = function (x) {
  x = Number(x);
  if (Math.abs(x) < 1) {
    return (Math.expm1(x) - Math.expm1(-x)) / 2;
  }
  return (Math.exp(x - 1) - Math.exp(-x - 1)) * (Math.E / 2);
};

Math.cosh = function (x) {
  x = Number(x);
  return (Math.exp(x - 1) + Math.exp(-x - 1)) * (Math.E / 2);
};

Math.tanh = function (x) {
  x = Number(x);
  var a = Math.expm1(x);
  var b = Math.expm1(-x);
  if (a === Infinity) {
    return +1;
  }
  if (b === Infinity) {
    return -1;
  }
  return (a - b) / (Math.exp(x) + Math.exp(-x));
};

```

**Comment by ljharb** [comment]
Thanks - can you provide some specific examples for each one that I can use as failing tests?

**Comment by Yaffle** [comment]
@ljharb , seems, you have found some.

P.S.
Seems, Safari 8.0 on Mac OS X 10.10 is very good for all Math.XXX, except `Math.round`.

**Comment by ljharb** [comment]
`Math.round` is ES5, not ES6, so please do file an `es5-shim` issue about that one :-) ES6 has `Math.fround`, which may have similar issues.

**Comment by zloirock** [comment]
Thanks!

**Comment by Yaffle** [comment]
Also, try ` Math.log10(0.9999)` in Chrome 41-43.

**Comment by Yaffle** [comment]
@ljharb , @zloirock , what about `Math.asinh`, `Math.acosh`, `Math.atanh`, `Math.cbrt` ?

I have updated my comment with some implementations, which can pass my tests.

**Comment by ljharb** [comment]
@Yaffle PRs with the tests to `es5-shim`/`es6-shim`, and probably also `compat-table`, would be very helpful - the implementations are great but the tests are the important part :-)

**Comment by Yaffle** [comment]
@ljharb 

```
// Firefox -37+
var isExpm1OK = Math.expm1(0.00002) >= 0.000020000200001333 &&
                Math.expm1(0.00002) <= 0.000020000200001334;
var isLog1pOK = Math.log1p(0.0002) >= 0.0001999800026662667 &&
                Math.log1p(0.0002) <= 0.0001999800026662668;

var isAcoshOK = Math.acosh(1.7976931348623157e+308) !== Infinity; // Chrome -41+

// Chrome -41+, Firefox -37+
var isAsinhOK = Math.asinh(0.0002) >= 0.0001999999986666666 && 
                Math.asinh(0.0002) <= 0.0001999999986666668;
var isAtanhOK = Math.atanh(0.0002) >= 0.0002000000026666667 &&
                Math.atanh(0.0002) <= 0.0002000000026666668;
                
// Firefox -37+
var isCbrtOK = Math.cbrt(Math.pow(2, 340 * 3)) >= Math.pow(2, 340) * (1 - 2 * Number.EPSILON) &&
               Math.cbrt(Math.pow(2, 340 * 3)) <= Math.pow(2, 340) * (1 + 2 * Number.EPSILON);
```

**Comment by Yaffle** [comment]
Note:
as `Math.exp` is not accurate in Chrome, all those methods also not very accurate.

see https://code.google.com/p/v8/issues/detail?id=3468

Chrome fails `Math.exp` tests in `test262`:

S15.8.2.8_A6	Checking if Math.exp is approximately equals to its mathematical values on the set of 64 argument values; all the sample values is calculated with LibC
( https://github.com/tc39/test262/blob/master/test/built-ins/Math/exp/S15.8.2.8_A6.js )

**Comment by ljharb** [comment]
@Yaffle thanks!

`isExpm1OK`, `isLog1pOK`, `isAcoshOK`, and `isCbrtOK` are already true in shimmed Firefox 37, Chrome 41, and Safari 8.

`isAsinhOK` and `isAtanhOK` are the only falses, and only in Chrome 41, they pass in FF/Safari.

I've filed an `es6-shim` issue for those two.

**Comment by Yaffle** [comment]
@ljharb 
This may be OS-dependent.
I have  `[ false, false, true, false, false, false ]` in FF 38 on Windows 7 with and without without es6-shim
And     `[ true, true, true, false, false, true ]` in Chrome 43 on Windows 7 without es6-shim
            `true, true, false, false, false, true]` in Chrome 43 on Windows 7 with es6-shim

**Comment by Yaffle** [comment]
Some EDGE cases:
```
Math.hypot(Infinity, {valueOf: function () {throw new Error("")}}) === Infinity; // Chrome 43
isNaN(Math.min(NaN, {valueOf: function () {throw new Error("")}})) === true; // IE 11
isNaN(Math.max(NaN, {valueOf: function () {throw new Error("")}})) === true; // IE 11
```

**Comment by ljharb** [comment]
Ah - new PRs welcome, let's make sure the comments include both the OS and browser version.

**Comment by Yaffle** [comment]
I have added some Konqueror's issues if someone is interested

**Comment by ljharb** [comment]
@Yaffle thanks - it's hard to see what the problem is, could you perhaps indicate what the value _should_ be, and what it is in the browser that deviates?

**Comment by Yaffle** [comment]
@ljharb ,

1)   `Math.expm1` is undefined, but there is `Math.exmp1` instead, which does what `expm1` should do;
2)  `Math.LOG10E` has a little wrong value - 0.43429448190325176, not  0.4342944819032518.
3) `Math.abs(+0)` return `-0`.
4) `Math.hypot` has length equal to `0`
5) for  `Math.hypot` the specification says "Implementations should take care to avoid the loss of precision from overflows and underflows that are prone to occur in naive implementations when this function is called with two or more arguments." - but `Math.hypot` in Konqueror is a "naive" (sqrt(a*a+b*b+...).

6) cube root is a monotonic function, so `Math.cbrt(x1)` should be not less than `Math.cbrt(x0)` if `x1 >= x0` in case of a good implementation.

**Comment by ljharb** [comment]
Thanks, I filed #724 - if you could add comments with other Konqueror issues that'd be great, since I don't have a way to test it.

**Comment by kangax** [comment]
I would consider removing Konqueror. Seems like an ancient browser with very specific audience. I'm struggling to figure out who would still be using it.

**Comment by ljharb** [comment]
That's also a fair point - there may not be any value in including it.

**Comment by Yaffle** [comment]
Mobile Safari 9.0 (iOS 9.2):
`Math.expm1(709.782712893384)  === -1`
note:
`Math.expm1(709.7827128933839) === 1.7976931348620688e+308`

`Math.round(0.5 - Number.EPSILON / 4) === 1`

**Comment by Yaffle** [comment]
es6-shim:
---------
```
error(Math.acosh(1 + Number.EPSILON), 2.1073424255447017e-8) > 1e+7;
Math.asinh(Number.MAX_VALUE) === Infinity;
Math.atanh(1e-300) === 0;
var EXP_NO_OVERFLOW = 709.782712893384; // Math.log(Number.MAX_VALUE)
Math.cosh(EXP_NO_OVERFLOW + 1 / Math.LOG2E - 0.5) === Infinity;
Math.sinh(EXP_NO_OVERFLOW + 1 / Math.LOG2E - 0.5) === Infinity;
```
core.js:
--------
```
error(Math.cbrt(1e-300), 1e-100) > 50;
error(Math.acosh(1 + Number.EPSILON), 2.1073424255447017e-8) > 1e+7;
Math.asinh(Number.MAX_VALUE) === Infinity;
Math.atanh(1e-300) === 0;
var EXP_NO_OVERFLOW = 709.782712893384; // Math.log(Number.MAX_VALUE);
Math.cosh(EXP_NO_OVERFLOW + 1 / Math.LOG2E - 0.5) === Infinity;
error(Math.log1p(1e-8), 9.999999950000001e-9) > 1e+7;
error(Math.expm1(1e-6), 0.0000010000005000001665) > 1e+6;
+ Math.sinh, Math.tanh (because of expm1)
```
Traceur:
--------
```
error(Math.cbrt(1e-300), 1e-100) > 50;
Math.acosh(Number.MAX_VALUE) === Infinity;
Math.asinh(Number.MAX_VALUE) === Infinity;
Math.atanh(1e-300) === 0;
var EXP_NO_OVERFLOW = 709.782712893384; // Math.log(Number.MAX_VALUE)
Math.cosh(EXP_NO_OVERFLOW + 1 / Math.LOG2E - 0.5) === Infinity;
Math.sinh(EXP_NO_OVERFLOW + 1 / Math.LOG2E - 0.5) === Infinity;
Math.sinh(1e-300) === 0;
Math.tanh(1e-300) === 0;
Math.expm1(1e-300) === 0;
Math.log1p(1e-300) === 0;
Math.tanh(1e+300) !== Math.tanh(1e+300);
```

**Comment by Yaffle** [comment]
`Math.pow(11, Math.pow(11, 9))` returns `0` on Chrome Mobile 48 (Android 5.1)

**Comment by ljharb** [comment]
It would be helpful if you could indicate what the correct/best answer should be in all these cases as well

**Comment by Yaffle** [comment]
@ljharb , every line of https://github.com/kangax/compat-table/issues/392#issuecomment-193802184 contains JavaScript expression, which returns `true` for a browser without ES6 support, it should return false. You can calculate relate errors by yourself.

**Comment by ljharb** [comment]
@Yaffle lol wat? why did you delete all your comments?

**Comment by Yaffle** [comment]
@ljharb , I have merged everything into the first comment.

**Comment by Yaffle** [comment]
```
  Math.log2 = function (x) {
    x = Number(x);
    return Math.log(x) * Math.LOG2E;
  };
  Math.log10 = function (x) {
    x = Number(x);
    return Math.log(x) * Math.LOG10E;
  };

  Math.hypot = function (x, y) {
    // https://bugzilla.mozilla.org/show_bug.cgi?id=896264#c28
    var max = 0;
    var s = 0;
    for (var i = 0; i < arguments.length; i += 1) {
      var z = Number(arguments[i]);
      var a = Math.abs(z);
      if (a === 1 / 0) {
        return a;
      }
      if (a !== 0) {
        if (a > max) {
          s *= (max / a) * (max / a);
          max = a;
        }
        s += (a / max) * (a / max);
      }
    }
    return max * Math.sqrt(s);
  };
  Math.cbrt = function (x) {
    x = Number(x);
    // http://en.wikipedia.org/wiki/Cube_root#Numerical_methods
    if (x !== x || x === 0 || x === -1 / 0 || x === +1 / 0) {
      return x;
    }
    var s = x < 0 ? -1 : +1;
    var a = Math.abs(x);
    var y0 = Math.exp(Math.log(a) / 3);
    return s * (a / (y0 * y0) + 2 * y0) / 3;
  };

  Math.log1p = function (x) {
    x = Number(x);
    // https://bugs.ecmascript.org/show_bug.cgi?id=309#c16
    if (x !== x || x === 0 || x === +1 / 0) {
      return x;
    }
    var x0 = 1 + x;
    var y0 = Math.log(x0);
    return x0 > 0 ? y0 + (1 - x0 + x) / x0 : y0;
  };
  Math.expm1 = function (x) {
    x = Number(x);
    // https://en.wikipedia.org/wiki/Newton%27s_method
    if (x !== x || x === 0) {
      return x;
    }
    var y0 = Math.exp(x);
    var x0 = Math.log(y0);
    return y0 - 1 + (x0 === -1 / 0 || x0 === +1 / 0 ? 0 : (x - x0) * y0);
  };

  Math.acosh = function (x) {
    x = Number(x);
    if (x < 1) {
      return 0 / 0;
    }
    if (x < 2) {
      return Math.log1p(x - 1 + Math.sqrt(1 - 1 / (x * x)) * x);
    }
    return Math.log1p(x / 2 + Math.sqrt(1 - 1 / (x * x)) * x / 2 - 1) + 1 / Math.LOG2E;
  };
  Math.asinh = function (x) {
    x = Number(x);
    if (x !== x || x === 0) {
      return x;
    }
    var s = x < 0 ? -1 : +1;
    var a = Math.abs(x);
    if (a < 1) {
      return s * Math.log1p(a + a * a / (Math.sqrt(a * a + 1) + 1));
    }
    return s * (Math.log1p(a / 2 + Math.sqrt(1 + 1 / (a * a)) * a / 2 - 1) + 1 / Math.LOG2E);
  };
  Math.atanh = function (x) {
    x = Number(x);
    if (x !== x || x === 0) {
      return x;
    }
    var s = x < 0 ? -1 : +1;
    var a = Math.abs(x);
    return s * Math.log1p(2 * a / (1 - a)) / 2;
  };
  Math.cosh = function (x) {
    x = Number(x);
    if (x !== x) {
      return x;
    }
    var a = Math.abs(x);
    var t = Math.expm1(a - 1) + 1;
    return (t + 1 / (t * Math.E * Math.E)) * (Math.E / 2);
  };
  Math.sinh = function (x) {
    x = Number(x);
    if (x !== x || x === 0) {
      return x;
    }
    var s = x < 0 ? -1 : +1;
    var a = Math.abs(x);
    if (a < 1) {
      var u = Math.expm1(a);
      return s * u * (1 + 1 / (u + 1)) / 2;
    }
    var t = Math.expm1(a - 1) + 1;
    return s * (t - 1 / (t * Math.E * Math.E)) * (Math.E / 2);
  };
  Math.tanh = function (x) {
    x = Number(x);
    if (x !== x || x === 0) {
      return x;
    }
    var s = x < 0 ? -1 : +1;
    var a = Math.abs(x);
    if (a < 1) {
      var u = Math.expm1(2 * a);
      return s * u / (u + 2);
    }
    var t = Math.expm1(2 * a) + 1;
    return s / (1 + 2 / (t - 1));
  };


```
