### ISSUE TITLE
Incorrect tests in "destructuring - defaults, temporal dead zone"

### ISSUE THREAD

**Issue by anba** [compat-table/compat-table#421]
These two tests from "destructuring - defaults, temporal dead zone" are incorrect:

``` javascript
try {
  eval("var {c = c} = {c:1};");
  return false;
} catch(e){}
try {
  eval("var {c = d, d} = {d:1};");
  return false;
} catch(e){}
```

TDZ does not apply to var-declared bindings. And even when the first test is changed to `let {c = c} = {c: 1}`, no runtime will be issued because the default initializer doesn't get executed. Did you intend to write `let {c = c} = {}`?

**Comment by webbedspace** [comment]
Ah, yes, of course. >_< Exactly right.
