### ISSUE TITLE
Incorrect test for parameter defaults

### ISSUE THREAD

**Issue by zenparsing** [compat-table/compat-table#422]
This test is incorrect:  when running the output of a transpiler on an engine that does not support default parameters, it will output true, because the `eval` will be parsed raw by the engine and throw.

``` js
return (function(x = 1) {
  try {
    eval("(function(a=a){}())");
    return false;
  } catch(e) {}
  try {
    eval("(function(a=b,b){}())");
    return false;
  } catch(e) {}
  return true;
}());
```

**Comment by webbedspace** [comment]
build.js is explicitly coded to [not compile tests containing eval](https://github.com/kangax/compat-table/blob/gh-pages/build.js#L480). In these cases you just have to work out the actual support yourself.
