### ISSUE TITLE
Update Node to 0.12

### ISSUE THREAD

**Issue by UltCombo** [compat-table/compat-table#427]
The current Node.js version used in the [ES6 Compatibility table](http://kangax.github.io/compat-table/es6/) is 0.11.14. I believe the same holds true for the other compat tables. Can these be updated to Node 0.12?

**Comment by kangax** [comment]
Yep, we should. If you can send PR, that would be great!

**Comment by robertrossmann** [comment]
What needs to be done in order for the html files in the repo to be updated?

I tried `node ./`, which gives me the test results, but does not update anything, and `node build.js` says that no files were modified... I guess I am missing some intermediate step here.

**Comment by UltCombo** [comment]
Yep, some contributing instructions regarding this would be nice.

**Comment by UltCombo** [comment]
How are the `data-*.js` files generated/updated?

**Comment by UltCombo** [comment]
Oh my bad, those are to edited manually if I'm reading the [README](https://github.com/kangax/compat-table#editing-the-tests) correctly.
