### ISSUE TITLE
Arcane Test Code

### ISSUE THREAD

**Issue by gsklee** [compat-table/compat-table#443]
This test code is being used for "class - implicit strict mode":

``` javascript
class C {
  static method() { return this === undefined; }
}

return (0,C.method)();
```

What does `(0,C.method)()` mean?

**Comment by webbedspace** [comment]
It's like [the (1,eval) trick](http://perfectionkills.com/global-eval-what-are-the-options/). It's calling the method as a function expression, not a method. See #435 for more information.

**Comment by gsklee** [comment]
@webbedspace Wow, thanks!
