### ISSUE TITLE
Detect asm.js support?

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#447]
.. now that IE announced its upcoming support — http://blogs.msdn.com/b/ie/archive/2015/02/18/bringing-asm-js-to-the-chakra-javascript-engine-in-windows-10.aspx

Probably in non-standard table.

**Comment by webbedspace** [comment]
(Since I have contributor privileges with this repo, I receive notifications for all opened issues.)

What I want to know is how a test would be written to verify this: asm.js is, by design, a subset of ES3, so the runtime behaviour would be identical but slower in non-conforming platforms.

**Comment by kangax** [comment]
Good question.

My first thought was that it might simply not be possible. However, looking into it a little more, and after reading [Luke's post](https://blog.mozilla.org/luke/2015/02/18/microsoft-announces-asm-js-optimizations/), I stumbled upon [ValidateModule](http://asmjs.org/spec/latest/#validatemodule-f). I tried running a piece of code that doesn't validate according to that production but which still includes "use asm" and I see that Firefox throws error!

``` js
(function(){"use asm"})(); // TypeError: asm.js type error: expecting return statement
```

Bingo.

I'm not sure how reliable this behavior is. Spec says:

_"This explicit directive allows JavaScript engines to avoid performing pointless and potentially costly validation on other JavaScript code, and to **report validation errors** in developer consoles only where relevant."_

So the error reporting doesn't look mandatory (I don't see RFC 2119-esque MUST or SHOULD) but perhaps that's something to catch onto.

**Comment by evilpie** [comment]
This console output is a bit confusing, but the "TypeError" is actually just a warning that is not catchable from JS. It just shows up in the webconsole.

**Comment by kangax** [comment]
Bummer...

**Comment by webbedspace** [comment]
Closing this because it's unlikely to be ever sufficiently observable (and the standard itself is waning in favour of WASM).

**Comment by ljharb** [comment]
The former is a good reason to close it - but WASM will be for the medium term implemented _in_ asm.js, so the two are complementary.
