### ISSUE TITLE
Significance circle character is missing

### ISSUE THREAD

**Issue by monk-time** [compat-table/compat-table#448]
On my Win7x64 machine I can't see any of significance circles on the page. According to [fileformat.info](http://www.fileformat.info/info/unicode/char/2b24/browsertest.htm) none of my fonts support this character (⬤, U+2B24). A quick check on SO [confirms](http://stackoverflow.com/a/12982461) that it might be better to use something else.

Chrome: ![chrome](http://i.imgur.com/K1oV3w8.png)
Firefox: ![firefox](http://i.imgur.com/Rr0dfSi.png)

**Comment by kangax** [comment]
Hm, perhaps just a &middot; (&middot;) of different size?

**Comment by monk-time** [comment]
I can see both U+25CF (● BLACK CIRCLE) and U+26AB (⚫ MEDIUM BLACK CIRCLE) in Firefox v35, but only the first one in Chrome v39. So maybe U+25CF?

**Comment by monk-time** [comment]
I'm not sure what has changed on my end, but this is no longer an issue for me. If nobody else has encountered this issue, I think it can be closed. :no_mouth:

**Comment by JeffJacobson** [comment]
I am currently seeing the same issue. I am also on Windows 7 (64-bit).

Firefox Developer Edition
![firefox developer edition](https://cloud.githubusercontent.com/assets/713754/16967981/dd8e8a4a-4dc0-11e6-9379-191922360bb9.png)
Chrome
![chrome](https://cloud.githubusercontent.com/assets/713754/16967988/e16ec1f2-4dc0-11e6-931c-c17316df6c3b.png)
