### ISSUE TITLE
Add Babel playground syntax to the non-standard table?

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#449]
http://babeljs.io/docs/usage/playground/

I'm worried that doing this might create a precedent where any old JS-superset transpiler's feature would be allowed to clutter up the table...

**Comment by zloirock** [comment]
Be better at first fully add Babel experimental ES7 features - for example, object rest / spread, abstract references, `String#at`.

**Comment by webbedspace** [comment]
Playground syntax has now been removed, so... _iris out_
