### ISSUE TITLE
Add Haxe Toolkit

### ISSUE THREAD

**Issue by StEvUgnIn** [compat-table/compat-table#450]
Hello,
I noticed Haxe doesn't take part of ECMAscript list. It would be great it to be present.

Haxe is a toolkit used to transpile ECMAscript compatible code to a lot of different platforms allowing implement a same core.

Haxe's syntax is mainly based on ActionScript and C#.

What do you think about ? I love using Haxe to implement JavaScript Objects. It would be nice to check its compatibility with ECMAscript 6.

http://haxe.org

**Comment by kangax** [comment]
According to wikipedia:

> The Haxe language is similar to ECMAScript, although almost no ECMAScript code will run on Haxe without modifications. Unlike ECMAScript, Haxe is a compiled language. The Haxe language is inspired by ActionScript and C#, supporting features of both.

So... if it's a language **similar** to ECMAScript and **not** an implementation of ECMAScript 3/5/6/7, I don't think it applies here.

Please correct me if I'm wrong.

**Comment by kangax** [comment]
Now that I think about it, you probably meant to check Haxe's compiled JS output for compatibility with ES5/6/7, but that also doesn't seem to apply to our tables. First of all, we've never included any of such compilers (CoffeeScript is an obvious example that comes to mind), and second — I don't see why someone would be interested to see if Haxe's compiled output complies with ES5/6/7. If anything, one would probably want to know if output doesn't comply with, say, ES6+ _exclusively_, and so runs on older platforms. But it seems very unlikely that they'd do something like this. And it would still not apply to our table (which is meant to show level of support of ES5/6/7 implementations)

**Comment by StEvUgnIn** [comment]
No at all, I meant Haxe and not its JavaScript output because it is not interested.

DOM is useable but only with a library to import. 

It's fine for me, thanks.
