### ISSUE TITLE
Symbol.iterator in iterables

### ISSUE THREAD

**Issue by zloirock** [compat-table/compat-table#455]
Current tests not checked `Symbol.iterator` in iterables. For check iterables used `__createIterableObject`. But now some libraries try to use `iterable[Symbol.iterator]()`. I don't propose change current tests, but i think shoud be added tests for `Symbol.iterator` in all iterables:

``` javascript
Array#[Symbol.iterator]
Arguments#[Symbol.iterator]
String#[Symbol.iterator]
Set#[Symbol.iterator]
Map#[Symbol.iterator]

ArrayIterator#[Symbol.iterator]
StringIterator#[Symbol.iterator]
SetIterator#[Symbol.iterator]
MapIterator#[Symbol.iterator]
EnumerateIterator#[Symbol.iterator]
```

**Comment by webbedspace** [comment]
Duplicate of #318
