### ISSUE TITLE
Add ES5 relaxed reserved words test

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#456]
```
var abstract, boolean, byte, char, double, final, float, goto, int, long,
    native, short, synchronized, transient, volatile;
return true;
```

Also, a test for the new strict mode reserved words:

```
var words = ['implements','package','protected','static','interface','private','public'];
var passed = words.every(function(word) { "use strict"; try { eval("var " + word); } catch(e) { return true; }});
passed &= words.every(function(word) { try { eval("var " + word); return true; } catch(e) {}});
return passed;
```

`await` is only reserved inside modules, so that can't be tested.

**Comment by webbedspace** [comment]
Tests confirm that Firefox 3, Safari 5.1 and IE 7 support the first test, Firefox 4 supports the second test (and IE <10 doesn't support strict mode). But, without legacy Safari and Chrome results, I can't fill in the rest of the table.

**Comment by kangax** [comment]
I get 0 in Safari 4.0.5

**Comment by kangax** [comment]
1 in Chrome 15, 18, 21, 25

**Comment by kangax** [comment]
0 in Chrome 5

**Comment by kangax** [comment]
Chrome 7, 8, 9, 11, 12, 14 that I have don't seem to open anymore (crashing right after start) :/

**Comment by webbedspace** [comment]
Which test are these results for?

Actually, I forgot that the second test requires the separate functionality of Array#every. Fortunately, everything on the table except IE < 9 coincidentally supports it.
