### ISSUE TITLE
Object.defineProperty is supported only by Firefox  properly

### ISSUE THREAD

**Issue by ghost** [compat-table/compat-table#464]
``` js
function test(label){
    console.log("test "+ label);
    if (b.x != 1)
        console.error("it does not keep the inherited value");
    for (var prop in b)
        if (prop == "x")
            console.error("it is still enumerable despite the flag");
    console.log("test completed");
}

var a = {x: 1};
var b = Object.create(a);
Object.defineProperty(b, "x", {
    enumerable: false,
    configurable: true
});

test("Object.defineProperty in combination with Object.create");

Object.defineProperty(a, "x", {
    enumerable: false,
    configurable: true
});
delete(b.x);

test("with the workaround");
```

The "it does not keep the inherited value" fails in every environment. The "it is still enumerable despite the flag" fails in every environment, but Firefox. I already reported these as bugs, no response yet after a week (except by node.js, they told me that this is a known chromium bug). So the first one might be a bad feature, the second one is a clear bug.

note:
If you set new value to the property, then it turns back to `enumerable: true`, which is bad feature again. So this `enumerable: false` is useless in this form, if you want to write a stable code.

**Comment by ghost** [comment]
(My English still sux.)

**Comment by claudepache** [comment]
For the "it does not keep the inherited value" test: it's not a bug. When you define the new own property, you cannot just define its "enumerable" and "configurable" attributes: you must also provide either a value or a getter/setter; and the default is "value: undefined", not "value: inherited".

For the "it is still enumerable despite the flag" test: It is an issue with for/in enumeration, not specific to ES5 features (the notion of enumerability existed already in ES1). Some implementations have indeed a bug, see Issue #675.

**Comment by ghost** [comment]
@claudepache As far as I can remember I reported this inconsistency to many browser manufacturers and all of them claimed that their implementation meets with the standard and the others implemented it buggy... :D Maybe you could test the feature in different browsers and add some comments about the browsers, which do not implement it the way described in the standard.
