### ISSUE TITLE
String.prototype.replace third argument

### ISSUE THREAD

**Issue by zcorpan** [compat-table/compat-table#465]
See https://github.com/w3c/web-platform-tests/pull/1671

Apparently Gecko supports a third argument to String.prototype.replace.

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/3447

**Comment by zcorpan** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=481738

**Comment by kangax** [comment]
We already have a test for it — http://kangax.github.io/compat-table/non-standard/#String.prototype.replace_flags
