### ISSUE TITLE
Wrong results for Array.isArray() 

### ISSUE THREAD

**Issue by Lambdac0re** [compat-table/compat-table#466]
The jQuery on the site seems to create a polyfill which is then used by the test.
Therefore the test for Array.isArray() in IE9 reports a false positive.
This may also be the case for other functions.

http://kangax.github.io/compat-table/es5/#Array.isArray

**Comment by webbedspace** [comment]
Uh, no it doesn't?

**Comment by webbedspace** [comment]
Evidence:
![](http://i.imgur.com/Z4tZRCU.png)

**Comment by Lambdac0re** [comment]
Found my mistake: I was in quirks mode.
Thanks!
