### ISSUE TITLE
Extra argument tests for certain built-ins

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#476]
[Via](https://github.com/kangax/compat-table/pull/475#issuecomment-83861177)
- [x] `String#startsWith` and `String#endsWith` throw when argument 1 is a RegExp
- [x] `Math.hypot` accepts 3+ arguments
- [x] Reflect methods should throw when argument 1 is primitive.

**Comment by zloirock** [comment]
@webbedspace I added fixed `Math.hypot` test before.

**Comment by webbedspace** [comment]
Ah yes, my apologies.

**Comment by kangax** [comment]
(turned into real checkboxes and checked off 2nd)
