### ISSUE TITLE
IDs that match global names conflict - add a prefix?

### ISSUE THREAD

**Issue by ljharb** [compat-table/compat-table#477]
`<td id="SIMD">` will shadow the global `SIMD` object. Either the test needs refinement, or the ID needs to not be "SIMD"

**Comment by kangax** [comment]
Ugh, the [age-old problem](http://kangax.github.io/domlint/) strikes again... We should probably prefix all ids with some token or "wrap" them into something.

**Comment by ljharb** [comment]
Prefixing all IDs with a token makes sense to me.

**Comment by webbedspace** [comment]
This has been indirectly fixed by subtly renaming the SIMD test, but of course the problem itself remains.
