### ISSUE TITLE
Babel is supporting "extends" for classes

### ISSUE THREAD

**Issue by slavede** [compat-table/compat-table#489]
It says that babel is not supporting "extends" for classes, but I just tested it in Chrome 41 with babel 4.7.8 and it worked perfectly fine. Following code works in compiled code:

```
    class Vehicle {
        constructor(color, numberOfWheels) {
            this.vehicleColor = color;
            this.numberOfWheels = numberOfWheels;
        }
 }

    class Bicycle extends Vehicle{
        constructor(color) {
            super(color, 2);
        }
    }
```

**Comment by webbedspace** [comment]
The compiled code works in Chrome but not IE 10. For more information, consult the results' footnotes.
