### ISSUE TITLE
ES7 features proposals from tc39/ecma262

### ISSUE THREAD

**Issue by thomasfosterau** [compat-table/compat-table#490]
I've been taking a look at [tc39/ecma262](https://github.com/tc39/ecma262) and comparing it with the ES7 Compatability Table. Virtually all proposals for ES7 are linked to in the tc39/ecma262 repo, but only around half of these are represented on the compatibility table. I'm not sure about the status of some of the proposals (e.g. I though Parallel JavaScript was dismissed years ago).

Anyway, I'd be willing to write/cleanup the tests for ES7 features, but I thought I might as well see if anyone thinks some tests should be merged (e.g. Object spread/rest properties might as well be sub-tests of one feature) or if it's worth adding tests for all of the proposals.

| Feature | In [tc39/ecma262](https://github.com/tc39/ecma262) | On [Compat-Table](http://kangax.github.io/compat-table/es7/) |
| --- | --- | --- |
| [Exponentiation operator](https://gist.github.com/rwaldron/ebe0f4d2d267370be882) | :+1: | :+1: |
| [Array comprehensions](http://wiki.ecmascript.org/doku.php?id=harmony:array_comprehensions) |  | :+1: |
| [Generator comprehensons](http://wiki.ecmascript.org/doku.php?id=harmony:array_comprehensions) |  | :+1: |
| [Descructuring comprehensions](https://bugzilla.mozilla.org/show_bug.cgi?id=980828) |  | :+1: |
| [Object rest properties](https://github.com/sebmarkbage/ecmascript-rest-spread) | :+1: (as [Rest/Spread Properties](https://github.com/sebmarkbage/ecmascript-rest-spread)) | :+1: |
| [Object spread properties](https://github.com/sebmarkbage/ecmascript-rest-spread) | :+1: (as [Rest/Spread Properties](https://github.com/sebmarkbage/ecmascript-rest-spread)) | :+1: |
| [Async functions](https://github.com/lukehoban/ecmascript-asyncawait) | :+1: | :+1: |
| [Arrow async functions](https://github.com/lukehoban/ecmascript-asyncawait) | :+1: (as [Async Functions](https://github.com/lukehoban/ecmascript-asyncawait)) | :+1: |
| [Typed objects](https://github.com/dslomov-chromium/typed-objects-es7) | :+1: | :+1: |
| [Object.observe](http://wiki.ecmascript.org/doku.php?id=harmony:observe) | :+1: (as [arv/ecmascript-object-observe](https://github.com/arv/ecmascript-object-observe)) | :+1: |
| [Object.getOwnPropertyDescriptors](https://gist.github.com/WebReflection/9353781) | :+1: | :+1: |
| [Array.prototype.includes](https://github.com/tc39/Array.prototype.includes/blob/master/spec.md) | :+1: | :+1: |
| [String.prototype.at](https://github.com/mathiasbynens/String.prototype.at) | :+1: | :+1: |
| [Reflect.Realm](https://gist.github.com/dherman/7568885) |  | :+1: |
| [SIMD](https://github.com/johnmccutchan/ecmascript_simd) | :+1: | :+1: |
| [Parallel JavaScript](http://wiki.ecmascript.org/doku.php?id=strawman:data_parallelism) | :+1: |  |
| [Async generators](https://github.com/jhusain/asyncgenerator) | :+1: |  |
| [Trailing commas in function call expressions](https://github.com/tc39/tc39-notes/raw/master/es6/2014-09/trailing_comma_proposal.pdf) | :+1: |  |
| [ArrayBuffer.transfer](https://gist.github.com/lukewagner/2735af7eea411e18cf20) | :+1: |  |
| [Class and Property Decorators](https://github.com/wycats/javascript-decorators/blob/master/README.md) | :+1: |  |
| [Defensible classes](http://wiki.ecmascript.org/doku.php?id=strawman:defensible_classes) | :+1: |  |
| [Relationships](http://wiki.ecmascript.org/doku.php?id=strawman:relationships) | :+1: |  |
| [String padding](http://wiki.ecmascript.org/doku.php?id=strawman:string_padding) | :+1: |  |
| [Structured Clone](https://github.com/dslomov-chromium/ecmascript-structured-clone) | :+1: |  |
| [Weak References](http://wiki.ecmascript.org/doku.php?id=strawman:weakreferences) | :+1: |  |
| [Set/Map.prototype.toJSON](https://github.com/DavidBruant/Map-Set.prototype.toJSON) | :+1: |  |
| [Class property decorators](https://gist.github.com/jeffmo/054df782c05639da2adb) | :+1: |  |

**Comment by webbedspace** [comment]
Object rest and object spread should _not_ be considered the same feature: one is an extension to object literals, and one is an extension to ES6 object destructuring. Granted, destructuring is syntactically designed to mirror "structuring" (literals) as much as possible, but their semantics are the opposite: one is a shorthand for "flattening" an object, and another is a shorthand for "inflating" one.

**Comment by thomasfosterau** [comment]
@webbedspace Very true - spread/rest are separate features in the es6 table as well, so subtests wouldn't make as much sense given the precedent. My only concern was that they are mostly the inverse of each other (at least as far as the proposal's examples go).

**Comment by kangax** [comment]
> Anyway, I'd be willing to write/cleanup the tests for ES7 features,

That would be great, so +1 from me!

One thing I have in mind is to separate ES7 table into sections by es-proposal-stage (1,2,3,4), perhaps with 4 being on top (most "ready" ones) and going down from there.

**Comment by thomasfosterau** [comment]
@kangax I've been splitting features into categories for the ES7 tests (syntax, functions, builtins, builtin extensions, miscellaneous), but I could add the proposal stages using a 'stage' key in the test files. Perhaps sorting features by proposal stage could be an alternative to grouping by category (or even with the addition of sorting by implementations)?

**Comment by kangax** [comment]
Hm, perhaps... I just feel like stage is of more significance for ES7 at the moment (unlike with ES6 where it's all finalized and _everything_ will be implemented). Some ES7 proposals might never see the light of day, so I feel like it's almost useless to show them among "others" that have strong support behind them.

@webbedspace what do you think?

**Comment by thomasfosterau** [comment]
Perhaps stage could be shown in a similar way to how feature significance is shown in ES6?

**Comment by zloirock** [comment]
How do you propose "cleanup" tests for ES7 features? Missing in `tc39/ecma262` features? :) IIRC, comprehensions and `Reflect.Realm` were a parts of ES6, but were delayed to ES7.

Add sections with stage is a good idea.

**Comment by thomasfosterau** [comment]
@zloirock "cleanup" meaning organise them - either by stage or category.

**Comment by zloirock** [comment]
BTW, from this list:
- [babel](http://goo.gl/Ggd6G9) & [traceur](http://goo.gl/ZnxVOk) supports property initialisers
- [babel](http://goo.gl/McrNCN) supports decorators, traceur uses this syntax for annotations

Relationships replaced by the [abstract references](https://github.com/zenparsing/es-abstract-refs). Abstract references replaced by the [bind operator](https://github.com/zenparsing/es-function-bind) and [private fields](https://github.com/zenparsing/es-private-fields).

Some features like [`Map#toJSON`](https://github.com/DavidBruant/Map-Set.prototype.toJSON/issues/1) are not viable in its current form.

**Comment by webbedspace** [comment]
Since ES7 has nowhere near the amount of features as ES6 (and will never do so as long as it remains a humble "annual" revision as TC39 has promised), I believe using the `category` value to organise tests by stages (`"Stage 4: finished"`, `"Stage 3: candidate"`, `"Stage 2: draft"`, `"Stage 1: proposal"`, `"Stage 0: strawman"`) would be appropriate throughout ES7's development lifetime.

**Comment by thomasfosterau** [comment]
Alright, I've given most features a category, which is one of `strawman`, `proposal`, `draft`, `candidate` or `finished`. Array comprehensions, Generator comprehensions and Destructing in comprehensions aren't in a category, but I'd assume they would all be either stage 2 or 3?
