### ISSUE TITLE
Built-in extensions, function "name" property, class statements for babel fails.

### ISSUE THREAD

**Issue by visualjeff** [compat-table/compat-table#492]
I'm using babel 5.0.8

My test is: 

describe('function "name" property', function() {
    it('class statements', function() {
        class foo {};
        class bar { static name() {} };
        return foo.name === "foo" && typeof bar.name === "function";
    });
});

Fails with this message:

1) function "name" property class statements:
     TypeError: Cannot redefine property: name
      at Function.defineProperties (native)

The compatibility chart shows that its suppose to be passing?

BTW, It passes when "static" is removed.

**Comment by visualjeff** [comment]
Same with the following "class expressions" test.

**Comment by zloirock** [comment]
In actual environment (exclude IE) functions `name` property can't be redefined. Looks like this test was passed in IE.

**Comment by visualjeff** [comment]
So are the two tests documented here incorrect?
https://kangax.github.io/compat-table/es6/#function_name_property_function_statements

**Comment by zloirock** [comment]
Yep. I did not add these results when added support functions `name` property in `core-js` / `babel` to the table :)

**Comment by visualjeff** [comment]
Ok.  Makes sense to me now.  Thanks.
