### ISSUE TITLE
Chrome 43 supports classes now

### ISSUE THREAD

**Issue by paulirish** [compat-table/compat-table#498]
The table indicates `flag` but it's shipped nowadays.

**Comment by webbedspace** [comment]
I don't think so?
![](http://i.imgur.com/YJRHaSZ.png)
(Unless it actually became re-flagged in 44 Canary.)

**Comment by paulirish** [comment]
Hmm my apologies. 
It appears they're all behind strict mode. 

That's different than a flag, though.

**Comment by kangax** [comment]
Hm, let's add a note? But then... what to show as a result? Introduce 3rd type — "Strict" (meaning only works under strict mode)? Feels iffy. On the other hand, it would also simplify `let` tests, which are essentially broken into 2 sets of strict/non-strict right now, and maybe others. There would also be cases of having "Strict + Flag", like TDZ in Babel. Maybe it's not a bad idea. @webbedspace what do you think?

**Comment by paulirish** [comment]
Yeah I'd be super happy with that, especially since a developer can choose for users to run their JS in strict mode whereas they can't with a flag.
