### ISSUE TITLE
Add get and set in ES5 standard table

### ISSUE THREAD

**Issue by DavidBruant** [compat-table/compat-table#5]
ES5 defines getter and setter initializers: http://es5.github.com/#x11.1.5
Information on support can be found here: http://robertnyman.com/javascript/javascript-getters-setters.html#regular-getters-and-setters
Likewise on MDN: 
- https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/set
- https://developer.mozilla.org/en/JavaScript/Reference/Operators/Special/get

**Comment by kangax** [comment]
This is already in.
