### ISSUE TITLE
Would it be possible to add PhantomJS2 to the ES6 compat table

### ISSUE THREAD

**Issue by aackerman** [compat-table/compat-table#500]
It looks like PhantomJS2 is supported for the ES5 table but not ES6

Is anything other than time and energy preventing that from happening?

**Comment by kangax** [comment]
I remember there were issues with getting it to run on the latest OS X and I'm not sure if they're resolved yet. @webbedspace might know more.

**Comment by webbedspace** [comment]
Actually, the ES6 table entry _is_ PhantomJS2.
![](http://i.imgur.com/hsCyhy2.png)
It has exactly the same ES6 support as Safari 6.
