### ISSUE TITLE
ES6 modules

### ISSUE THREAD

**Issue by silverwind** [compat-table/compat-table#501]
These are part of the spec, can we add them?

From what I gathered, Babel seems to support them: https://babeljs.io/docs/learn-es6/#modules

**Comment by silverwind** [comment]
Been trying to write a test for this, but it seems impossible as I get a uncatchable `SyntaxError` in `babel-node` when trying to wrap the `import`:

``` js
> try {import * as a from "b"} catch(e) {console.log(typeof e)};
SyntaxError: repl: 'import' and 'export' may only appear at the top level (1:5)
```

**Comment by zloirock** [comment]
![script / module](https://pbs.twimg.com/media/CCkQC9hW4AI5coy.png:large)
`import` forbidden outside of modules. All `babel` output uses modules syntax. How do you propose test it within this table? I think, only manually check.

**Comment by kangax** [comment]
Duplicate of #316

**Comment by silverwind** [comment]
Whoops, sorry I missed that issue.

**Comment by silverwind** [comment]
> How do you propose test it within this table?

I suppose one could inject a `<script type="module">` and inside of it, test for `self === undefined` in a browser. On the server, it seems impossible so far.
