### ISSUE TITLE
Test object enumerability order (`for .. in`)

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#504]
Now that ES6 actually defines it

**Comment by webbedspace** [comment]
It only [sort-of defines it](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-ordinary-object-internal-methods-and-internal-slots-enumerate):

> The mechanics and order of enumerating the properties is not specified but must conform to the rules specified below.

[And for Object.keys:](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-enumerableownnames)

> Order the elements of names so they are in the same relative order as would be produced by the Iterator that would be returned if the [[Enumerate]] internal method was invoked on O.

From the looks of it, the order of entries in individual objects is specified to use (the ordering of) [OwnPropertyKeys](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys), (minus Symbol keys), but the order of entries in separate tiers in the prototype chain is _not_ guaranteed anywhere.

...

I believe the following things directly call OwnPropertyKeys:
- Object.assign
- Object.defineProperties (fires a proxy's "getOwnPropertyDescriptor" trap for each element returned by OwnPropertyKeys (unless "ownKeys" is trapped))
- Object.getOwnPropertyNames
- Object.getOwnPropertySymbols
- Reflect.ownKeys
- Object.freeze/Object.seal/Object.isFrozen/Object.isSealed (fires a proxy's "defineProperty" trap for each element returned by OwnPropertyKeys (unless "ownKeys" is trapped))
- JSON.parse (calls the reviver callback on each object element in OwnPropertyKeys order).
- JSON.stringify

**Comment by webbedspace** [comment]
I added/modified tests for several of the above (assign, getOwnPropertyNames, getOwnPropertySymbols, ownKeys, parse, stringify) and decided the rest weren't useful or relevant enough.

**Comment by kangax** [comment]
Thanks @webbedspace, you are excellent as always!

**Comment by zloirock** [comment]
@webbedspace Hmm. Maybe leave 1 `Reflect.ownKeys` test with the main logic w/o order? Also, `es6-shim` not adds symbols, but second `Reflect.ownKeys` test marked as "`for-in` order".

**Comment by zloirock** [comment]
IE11 result (in table 5/6):
![ie11 enum](http://habrastorage.org/files/f31/4ab/ec1/f314abec1ba44b909cfb0387ab4bbb49.png)

**Comment by Yaffle** [comment]
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-type : 

```
An integer index is a String-valued property key that is a canonical numeric String (see 7.1.16) and whose numeric value is either +0 or a positive integer ≤ 253−1. An array index is an integer index whose numeric value i is in the range +0 ≤ i < 232−1.
```

```
var object = {};
object[Math.pow(2, 53).toString()] = 0;
object[(Math.pow(2, 53) + 2).toString()] = 1;
object[(Math.pow(2, 53) - 1).toString()] = 2;
console.log(Object.keys(object));

```
