### ISSUE TITLE
Make it easier to select/copy test contents

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#507]

**Comment by bterlson** [comment]
:+1: :+1: :+1:

**Comment by bzbarsky** [comment]
Maybe make it so a click on the question mark in a circle locks the tooltiip in place so it doesn't disappear?

**Comment by kangax** [comment]
@bzbarsky That's a nice idea. Not sure how discoverable it would be (for those who don't know). I guess it's way better than what we have now, even if not perfect solution.
