### ISSUE TITLE
Add Firefox Nightly

### ISSUE THREAD

**Issue by silverwind** [compat-table/compat-table#524]
Currently, only **Release**, **Beta** and **Aurora** are included. To keep up with Mozilla's latest developments, I'd love to see a column for **Nightly** too (Currently 40).

**Comment by kangax** [comment]
The latest version listed on compat table is usually the one from nightly. We just haven't had a chance to update it yet (and I noticed that it went down couple points but didn't check where exactly).

**Comment by silverwind** [comment]
Ah, nevermind then!

**Comment by webbedspace** [comment]
The point discrepancy has to do with the `class` tests - I've marked them as `true` even though they actually require a `constructor()` to be present in all class expressions. I should probably mark them `flag` or something.

Incidentally, there were actually several features in the past which have been "nightly build only" - that is, they are disabled when the FF version proceeds to Aurora. So, Nightly can sometimes be an inaccurate representation of the future FF version.
