### ISSUE TITLE
Update io.js to v2.0.0

### ISSUE THREAD

**Issue by ChALkeR** [compat-table/compat-table#535]
io.js v2.0.0 got released today, with v8 updated to 4.2.77.18, see https://github.com/iojs/io.js/blob/master/CHANGELOG.md.

> - **V8**: upgrade to 4.2.77.18, see the [ChangeLog](https://chromium.googlesource.com/v8/v8/+/refs/heads/4.2.77/ChangeLog) for full details. Notable items:
>   - Classes have moved out of staging; the `class` keyword is now usable in strict mode without flags
>   - Object literal enhancements have moved out of staging; shorthand method and property syntax is now usable (`{ method() { }, property }`)
>   - Rest parameters (`function(...args) {}`) are implemented in staging behind the `--harmony-rest-parameters` flag
>   - Computed property names (`{['foo'+'bar']:'bam'}`) are implemented in staging behind the `--harmony-computed-property-names` flag
>   - Unicode escapes (`'\u{xxxx}'`) are implemented in staging behind the `--harmony_unicode` flag and the `--harmony_unicode_regexps` flag for use in regular expressions

**Comment by webbedspace** [comment]
A reminder: currently we only list `flag` results for those features which are enabled by the flag `--harmony (enable all completed harmony features)`.

**Comment by ChALkeR** [comment]
https://github.com/kangax/compat-table/blob/9da1b1e4fc32b9e250e5bfb472e0d1f9ea62802a/data-es6.js#L337 — this is still wrong
