### ISSUE TITLE
Not correctly detecting "let" support?

### ISSUE THREAD

**Issue by tjconcept** [compat-table/compat-table#536]
From the console I got the impression that my FF39 supports `let` but the table seems to tell otherwise?

![ff](https://cloud.githubusercontent.com/assets/801895/7469485/5871ec60-f314-11e4-8128-c3e25bbe3fb8.png)

**Comment by webbedspace** [comment]
`let` is supported in the console but not in web pages (unless the condition specified by the `let` result's footnote is fulfilled).
