### ISSUE TITLE
SIMD.%type%.bool is not specified for floats

### ISSUE THREAD

**Issue by Elchi3** [compat-table/compat-table#537]
`typeof SIMD.float32x4.bool === 'function';`
should be
`typeof SIMD.int32x4.bool === 'function';`

(or int8x16, int16x8, but not float types, see the [spec/polyfill implementation](https://github.com/johnmccutchan/ecmascript_simd))

**Comment by Elchi3** [comment]
Updated to recent spec with https://github.com/kangax/compat-table/commit/3d36840f36ab86e2077992b717121be783e6f3a1

**Comment by ljharb** [comment]
Thanks, I didn't realize this was open :-)
