### ISSUE TITLE
Add a column in ES6 for node run with `--harmony` flag

### ISSUE THREAD

**Issue by faridnsh** [compat-table/compat-table#54]

**Comment by kangax** [comment]
Just ran with --harmony. Same result.

**Comment by faridnsh** [comment]
The reason I realized there's a difference, is that normal node doesn't have `Proxy`, but node with `--harmony` does have:

```
$ node --harmony -pe Proxy
> { create: [Function], createFunction: [Function] }
```

**Comment by faridnsh** [comment]
Maybe you haven't run the tests with the latest.

**Comment by kangax** [comment]
Updated to 0.8.15 and I see some changes now — Proxies, Block-level function declaration, Maps

**Comment by kangax** [comment]
Fixed in https://github.com/kangax/es5-compat-table/commit/8441774cc2b6cc376b4f78b53f6cf6dae0903f14

**Comment by faridnsh** [comment]
Cool. You're awesome :D
