### ISSUE TITLE
The "destructuring nested rest" does not represent a spec'd concept

### ISSUE THREAD

**Issue by caitp** [compat-table/compat-table#545]
https://kangax.github.io/compat-table/es6/#destructuring_nested_rest

``` js
var a = [1, 2, 3], first, last;
// The following does not parse as an ArrayAssignmentPattern
[first, ...[a[2], last]] = a;
return first === 1 && last === 3 && (a + "") === "1,2,2";   
```

Per https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-assignment

**Comment by caitp** [comment]
erk, pressed enter to soon =)

**Comment by caitp** [comment]
It's more likely that you want to test something like this:

``` js
var [first, [firstElementOfSubArray, ...nestedRest], ...otherRest]
    = [0, [1, 2, 3, 4], 5, 6, 7, 8];
// first = 0
// firstElementOfSubArray = 1
// nestedRest = [2, 3, 4]
// otherRest = [5, 6, 7, 8]
```

**Comment by webbedspace** [comment]
Not true: take a look at [12.14.5.3](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-iteratordestructuringassignmentevaluation), specifically the production 

_AssignmentRestElement[Yield] : ... DestructuringAssignmentTarget_

and steps 6 and 7.

**Comment by caitp** [comment]
This is patently false. You're conflating rest and spread

**Comment by caitp** [comment]
ok, you're right, arv walked me through it, and this is a thing that exists. But I maintain that it should not exist, and we're going to hurt a lot of peoples brains allowing this =)
