### ISSUE TITLE
Objects with `iterator` property should not be iterable

### ISSUE THREAD

**Issue by domenic** [compat-table/compat-table#55]
Although it's not finalized how users can create iterable objects, it's definitely _not_ going to be through a simple `iterator` property. Right now you're just testing against Firefox's nonstandard implementation.

I can't really see a good test for this, however, given that TC39 hasn't decided exactly how it will work. Probably via a symbol that you import from a standard module, but not clear.

**Comment by kangax** [comment]
I wrote this based on:

<blockquote>An object is iterable if it has an iterator() method.
for-of simply calls the iterator() method to produce an iterator, then repeatedly calls the iterator’s .next() method to produce values.</blockquote>

from http://wiki.ecmascript.org/doku.php?id=harmony:iterators

Is the wiki outdated or did I miss something?

**Comment by domenic** [comment]
Yes, as it now says at the top of that page,

> This proposal has progressed to the Draft ECMAScript 6 Specification, which is available for review here: specification_drafts.

In particular the current mechanism involves a "intrinsic symbol" `@@iterator`, as can be seen e.g. [for arrays](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-15.4.4.26) or [maps](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-15.14.5.12).

**Comment by kangax** [comment]
I see. Then we'll need to change the test.

**Comment by kangax** [comment]
@domenic if you have a test for this, I would love a pull request!

**Comment by domenic** [comment]
OK, can do! Recent TC39 meetings concluded that you'll be able to get the intrinsic symbol `@@iterator` via `Symbol.iterator`, so it should be a pretty quick test. Will try to do this weekend.

**Comment by kangax** [comment]
Awesome, thanks!
