### ISSUE TITLE
Time zone detection

### ISSUE THREAD

**Issue by mattjohnsonpint** [compat-table/compat-table#551]
The ECMAScript Internationalization API supports the following:

```
Intl.DateTimeFormat().resolvedOptions().timeZone
```
- Some browsers (such as Chrome) implement the spec completely, and return the IANA time zone id, such as `"America/Los_Angeles"`.
- Some browsers return `undefined`, as they don't implement the time zone portion of the spec.
- Some browsers do not have `Intl` at all.

Please add a line to the table indicating which browsers will return a time zone id.  Thanks.

**Comment by kangax** [comment]
A PR would be super welcome!

**Comment by mattjohnsonpint** [comment]
Completed with #552.
