### ISSUE TITLE
Add a test for the the correct [[Prototype]] of bound functions

### ISSUE THREAD

**Issue by claudepache** [compat-table/compat-table#553]
ES6 introduces a breaking change in `Function.prototype.bind`.

In ES5, the [[Prototype]] of `f.bind(null)` was `Function.prototype`. In ES6, it is `f.[[Prototype]]`.

None of the three browsers that I've tested implements the new semantics.

Reference, steps 2 and 8 of [BoundFunctionCreate()](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-boundfunctioncreate) 
Justification of the change: [es:bug3829](https://bugs.ecmascript.org/show_bug.cgi?id=3819#c0)

Here is a proposed test:

``` javascript
function getProtoBound(proto) {
    var f = Object.setPrototypeOf(function() { }, proto)
    var boundF = Function.prototype.bind.call(f, null)
    return Object.getPrototypeOf(boundF)
}

var success = [ Function.prototype, function(){}, [], null ].every(function(proto) {
    return getProtoBound(proto) === proto
})

return success
```

**Comment by kangax** [comment]
Hm, interesting. `getProtoBound` looks reasonable to me. As far as testing multiple [[Prototype]] values — I'd be OK with just one (say, `function(){}`) to see that behavior is implemented, but I guess the more the better (just in case).

**Comment by kangax** [comment]
@claudepache if you could send a PR that would be great or one of us will get to it sometime soon
