### ISSUE TITLE
Map/Set "iterator closing" test

### ISSUE THREAD

**Issue by ljharb** [compat-table/compat-table#562]
First of all, I don't see how this test is valid - https://github.com/kangax/compat-table/blob/gh-pages/data-es6.js#L3609-L3616 - it does not produce an iterable with a "return" method at all, in fact, the object with the "return" method is simply the second "value" the iterable produces.

Next, according to https://people.mozilla.org/~jorendorff/es6-draft.html#sec-map-iterable, when there is no error, `IteratorClose` is **not** called. Thus, I'm not sure how or why babel/core-js has these tests passing, since they're invalid.

The same applies to Set.

Is it alright if I delete these two tests entirely?

**Comment by zloirock** [comment]
Emm? `__createIterableObject` with second argument produce iterator with `.return`, `Map` throws on primitive during iteration and call `IteratorClose`.

**Comment by ljharb** [comment]
Ah, so this test is testing the close behavior on error, that makes sense. Perhaps I've got an out of date es6.html on my local machine - this issue may be invalid, thanks.

**Comment by ljharb** [comment]
Ah - https://github.com/kangax/compat-table/blob/c472eab6ee263e3d2e3292771b7fc441dab99071/es6/compiler-skeleton.html#L15-L29 and https://github.com/kangax/compat-table/blob/8803b1162a192697b22e7fb94a19b961e4e073b1/es6/skeleton.html#L15-L31 are not in sync.
