### ISSUE TITLE
Reflect.enumerate() iterator prototype tests

### ISSUE THREAD

**Issue by webbedspace** [compat-table/compat-table#563]
I want to write a test for the iterator returned by `Reflect.enumerate()`, but there's a problem: [the object is underspecified](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-ordinary-object-internal-methods-and-internal-slots-enumerate). It's not clear whether %IteratorPrototype% needs to be its direct prototype, or merely on the chain, and it's also not clear whether `next()` must be an own-property or not. So, writing a test for this seems difficult, especially given that %IteratorPrototype% has no identifying qualities apart from its [Symbol.iterator] method.

**Comment by ljharb** [comment]
I believe `var iteratorPrototype = Object.getPrototypeOf([].keys()); Reflect.enumerate().next() instanceof iteratorPrototype` needs to be true? The spec says "The Iterator object must inherit from %IteratorPrototype%" which doesn't care about the inheritance chain except that `%IteratorPrototype%` is in it.

**Comment by zloirock** [comment]
@ljharb `Object.getPrototypeOf([].keys())` -> `%ArrayIteratorPrototype%`

**Comment by ljharb** [comment]
Ah, right, so `Object.getPrototypeOf(Object.getPrototypeOf([].keys()))` then?

**Comment by zloirock** [comment]
@ljharb also `instanceof iteratorPrototype` %) In not most recent environments `%IteratorPrototype%` is absent and `Object.getPrototypeOf(Object.getPrototypeOf([].keys()))` returns `%ObjectPrototype%`. Also, IIRC, in some environments was buggy iterators prototype chain.

**Comment by zloirock** [comment]
@webbedspace I think checking `.next` and `[Symbol.iterator]` in result + results of iteration enough for this test.

**Comment by ljharb** [comment]
That in most recent environments `%IteratorPrototype%` is absent is a great reason to test it. The whole point of the compatibility table imo is to expose spec compliance failures in as many places as possible so that devs know the quirks, and engines know to fix them :-)

**Comment by zloirock** [comment]
@ljharb I never mind  :) But missed a lot of much more important tests.

**Comment by zloirock** [comment]
[`Reflect.enumerate` removed from the spec.](https://github.com/tc39/ecma262/pull/367)
