### ISSUE TITLE
Break down language features between runtime features and new syntax

### ISSUE THREAD

**Issue by rbuckton** [compat-table/compat-table#565]
Continuing the discussion from #557:

This proposes a possible bifurcation of the compatibility table into two groups:
- New or modified syntactic forms, static semantics, or runtime semantics - Primarily features that would require a specialized transpiler to support in older host environments.
- New or modified runtime behavior of built-ins - Primarily features that could be implemented in a polyfill library.

This would allow for more flexibility when comparing compatibility results between various host environments, polyfill libraries, and transpiler.

_Original discussion:_ 

@kangax [wrote](https://github.com/kangax/compat-table/pull/557#issuecomment-110874560):

> Hm, now that we'll be adding TypeScript + polyfill (in addition to Babel + polyfill), it makes me remember a feature of combining engines that I've been meaning to add for a long time. For example, to see support of Firefox + Babel vs. Edge + Traceur. I'm not yet sure exactly how to make it work UI-wise, but this way we can have polyfill as a separate column as well! Then you'd be able to select, say, just Babel or Babel + core.js or Babel + core.js + Firefox. Granted, browser + compiler combo seems slightly less useful (it's more of a curiosity kind of thing) than compiler + polyfill, but few people asked for it and I think it could make sense to have that.

@rbuckton [wrote](https://github.com/kangax/compat-table/pull/557#issuecomment-110876094):

> In general what might be best is a way to delineate features that require runtime support (e.g. those that can be polyfilled) vs. features that use or derive from new syntactic forms (e.g. those that can be transpiled), though there may be cases where there is overlap.

**Comment by chicoxyzzy** [comment]
Follow #581 please
