### ISSUE TITLE
Test `const ... in ...`

### ISSUE THREAD

**Issue by mgol** [compat-table/compat-table#571]
ES6 supports the following construct:

``` js
var keys = [];
for (const i in {a: 2, b: 3}) {
    setTimeout(function () {
        keys.push(i);
    });
}
console.assert(keys.indexOf('a') > -1);
console.assert(keys.indexOf('b') > -1);
```

This seems to be the only situation where `const` is allowed without explicit initializer so it might be worth checking it.

Chrome 43 passes the test, IE11 & Edge don't.

P.S. A cleaner test would use `for-of` but that's yet another feature I didn't want to mix in.

**Comment by ljharb** [comment]
Why would `const something;` not work? That'd be a non-reassignable variable containing `undefined`.

Also, your setTimeout callback will suffer from the common "last" bug with loops (http://www.mennovanslooten.nl/blog/post/62/) - you'd need to do `(function (i) { setTimeout(function () { keys.push(i); }); }(i))` to avoid that.

**Comment by mgol** [comment]
`const sth;` is disallowed by the spec; I don't imagine a lot of cases where an undefined constant is needed so this seems reasonable.

And no, wrapping in a closure is not necessary. :) That's the whole point, the variable has a fresh binding per iteration we each `setTimeout` will have a separate binding passed. That's also one of the things I wanted to test here.

**Comment by ljharb** [comment]
aha, fair point :-) i'm so used to that kneejerk reaction with loops and "var" that I didn't think it through.

Where in the spec is that disallowed? Chrome (stable and canary) allows it currently, although Firefox Nightly and Babel don't.

This does look like a useful test indeed.

**Comment by mgol** [comment]
I'm AFK right now but you need to test it in strict mode. Chrome's sloppy
const is not spec-compliant (it's a pre-ES6 implementation, Firefox also
has one) and let currently doesn't work in sloppy at all.

## 

Michał Gołębiowski

**Comment by mgol** [comment]
Note that this repo already has a similar test for let. I think it'd be
useful to test it for const as well, though, since in the let case some
let-supporting browsers just give incorrect results whereas they reject the
const variant in the parse phase.

## 

Michał Gołębiowski

**Comment by getify** [comment]
Note: this test (which is needed!) doesn't need `setTimeout(..)`, just like it doesn't need that in the `let` case. It's cleaner to show it synchronously.

**Comment by mgol** [comment]
Sure. I checked how it's done for let (just pushing functions using the
variable to the stack & invoking later) and I agree this is a better way to
test.

## 

Michał Gołębiowski

**Comment by claudepache** [comment]
Currently, there exists a subtest for `let` called "for-loop iteration scope".
It seems to me that that test would be appropriate, replacing occurences of `for(let` with `for(const`.

**Comment by mgol** [comment]
@claudepache 

> Currently, there exists a subtest for let called "for-loop iteration scope".
> It seems to me that that test would be appropriate, replacing occurences of `for(let` with `for(const`.

:+1: 

EDIT: that is, the second part of this test (checking `let i in`) would be useful, the first part won't work due to iterating via `i++`.

**Comment by mysticatea** [comment]
+1 Firefox also fails this test: https://bugzilla.mozilla.org/show_bug.cgi?id=1094995

**Comment by klimashkin** [comment]
Firefox 45,

```
for (const i of [1,2]) {
    console.log(i);
}
==> SyntaxError: invalid for/in left-hand side 
```

```
for (let i of [1,2]) {
    setTimeout(function () {
        console.log(i);
    })
}
==> 2,2 (Must be 1,2)
```

@kangax , number of firefox stars in Table for `const` and `let` must be reduced, otherwise this is really misleading

**Comment by webbedspace** [comment]
Firefox already has only 8/10 for `let` as that behaviour ("for loop iteration scope") is already tested.

**Comment by bellbind** [comment]
+1 Request for adding the case `for (const v of  [1,2,3]) v;` check

(even if a root of the reason is same as a scope problem as `let`)

**Comment by klimashkin** [comment]
Yeah, for Firefox 48 table says `const 10/10`, but const still doesn't work with `for of` loop:
`SyntaxError: missing = in const declaration`

**Comment by mgol** [comment]
I've just created a PR fixing this issue: #758.
