### ISSUE TITLE
meta library

### ISSUE THREAD

**Issue by nickdesaulniers** [compat-table/compat-table#573]
it would be neat to abstract away the compatibility testing and charting so that it could be used for all kinds of web/DOM APIs, not just es6 features.  For example, I'd like to plot info on MSE codec support, which is messy.  http://nickdesaulniers.github.io/netfix/#/5/1  I can write the code to test for each, it would be neat & useful to have a library where I could supply the unit tests and have a nice chart that I could share.  caniuse.com might be more appropriate...but just a thought.

**Comment by chicoxyzzy** [comment]
Follow #711 please
