### ISSUE TITLE
Some additional let/const tests

### ISSUE THREAD

**Issue by domenic** [compat-table/compat-table#58]
Here are some additional semantics you can test for `let` and `const`. All of them should only be run if the basic tests succeed (i.e. `const x = 5;` and `let x = 5;` do not produce errors when `eval`ed).
### `const` must have an initializer

``` js
try {
  eval('const x;');
} catch (e) {
  return e instanceof SyntaxError;
}
return false;
```
### Cannot occur twice with the same identifier within a block

``` js
try {
  eval('let x; let x;');
} catch (e) {
  return e instanceof SyntaxError;
}
return false;
```

``` js
try {
  eval('const x = 5; const x = 5;');
} catch (e) {
  return e instanceof SyntaxError;
}
return false;
```
### Temporal dead zone (use before declaration)

``` js
try {
  eval('x; const x = 5;');
} catch (e) {
  return e instanceof ReferenceError;
}
return false;
```

``` js
try {
  eval('x; let x;');
} catch (e) {
  return e instanceof ReferenceError;
}
return false;
```
### Temporal dead zone still works with shadowing

``` js
try {
  eval('const x = 2; { x; const x = 5; }');
} catch (e) {
  return e instanceof ReferenceError;
}
return false;
```

``` js
try {
  eval('let x; { x; let x; }');
} catch (e) {
  return e instanceof ReferenceError;
}
return false;
```
### Fresh per-loop iteration

``` js
var a = [];
for (let i = 0; i < 3; ++i) {
  a[i] = function () { return i; };
}

return typeof i === "undefined" && a[1]() === 1;
```

**Comment by ghost** [comment]
If you attempt to run anything with `let` in V8 without it being strict, it throws

```
SyntaxError: Illegal let declaration outside extended mode
```

leading to a false positive.

`const` works however. But the double declaration test does not throw a `SyntaxError`. Instead it throws

```
TypeError: const 'x' has already been declared
```

Which I think is probably the right kind of error (vs. your test looking for `SyntaxError`).

**Comment by ghost** [comment]
Additionally, you should check that the deadzone errors are ReferenceErrors as per spec. For example `x; let x = 5;` Continuum throws:

```
ReferenceError: x is not initialized
```

**Comment by domenic** [comment]
Double declarations [should be a syntax error](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-14.1), but yes, you're right on `ReferenceError`s.

**Comment by kangax** [comment]
@domenic @Benvie Thanks!

However, I would prefer to stick to simple tests, checking basic functionality and/or pure presence (in case of objects/properties).

2 reasons for that:
- It's hard to tell when to stop (adding additional checks). For a full-blown conformance, there's something like [test262](http://test262.ecmascript.org/) (although nothing for ES6 at the moment, right?)
- It's simpler to get the gist of a feature from a test code that we display in a popup, when hovering over a "?".

Alternatively, we can have 2 tests in the future — basic and extensive. And maybe divide cells into half, showing presence / conformance.

**Comment by domenic** [comment]
Yeah, that makes perfect sense. I am just sad when browsers get credit for implementing something, but implement it incorrectly. But the simplicity angle is probably more important.

**Comment by rauschma** [comment]
@domenic Nice tests, http://test262.ecmascript.org/ might be a better fit for them.

**Comment by domenic** [comment]
@rauschma unfortunately I believe test262 can only accept submissions from Ecma members.
