### ISSUE TITLE
Object.keys are behave different in Chrome and Safari

### ISSUE THREAD

**Issue by extempl** [compat-table/compat-table#585]
Please, add to the footnotes that Safari's version of `Object.keys` works only with objects and returns `TypeError: Requested keys of a value that is not an object.` for any other types.
Chrome works with any types and returns different result according to types. For example:

```
false -> []
[2, 3, 1] -> [1, 2, 3]
'string' -> [1, 2, 3, 4, 5]
```

**Comment by zloirock** [comment]
http://kangax.github.io/compat-table/es6/#Object_static_methods_accept_primitives
