### ISSUE TITLE
Chrome has had ES6 classes since v42 (in strict mode)

### ISSUE THREAD

**Issue by dominictobias** [compat-table/compat-table#589]
I noticed that the table says that Chrome has no classes but they have been on by default since v42 but require the 'use strict' statement - is this why it says they are not there?

http://jsfiddle.net/ck8dcu0m/1/

**Comment by ljharb** [comment]
Yes - "requires strict mode" could be said to be almost the same as "doesn't support the feature". You'll note the green triangle in the upper-right corner which denotes this partial support.

**Comment by dominictobias** [comment]
Ah ok thanks
