### ISSUE TITLE
redefine const won't throw an error in iojs

### ISSUE THREAD

**Issue by popomore** [compat-table/compat-table#590]
```
> const a = 1; a = 2; 
2
> a
1
```

It just reject the new value, won't throw an error.

Test on iojs@2.3.3, iojs@1.8.4 and the latest chrome

By the way, Firefox will throw a SyntaxError

> const a = 1; a = 2; now also throws a SyntaxError ("invalid assignment to const a").

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const

**Comment by ljharb** [comment]
@popomore Try in strict mode: `'use strict'; const a = 1; a = 2`

That's just because v8 hasn't implemented a bunch of stuff in sloppy mode yet.

**Comment by popomore** [comment]
:+1:

**Comment by popomore** [comment]
Maybe this case is incorrect without strict mode.

https://github.com/kangax/compat-table/blob/gh-pages/data-es6.js#L716

**Comment by ljharb** [comment]
I don't see "chrome: true" or "iojs: true" there. We could add them as "strict" I suppose, but I don't see anything incorrect?

**Comment by webbedspace** [comment]
Let's all just look at the table again.
![](http://i.imgur.com/XiwF7A5.png)
As you can see, there is no problem.

**Comment by popomore** [comment]
Yeah, really. I got a wrong one, the 'strict' one is just here https://github.com/kangax/compat-table/blob/gh-pages/data-es6.js#L795

Thanks
