### ISSUE TITLE
Proxy test crashes Edge

### ISSUE THREAD

**Issue by bterlson** [compat-table/compat-table#593]
A recently added test (81ca7ced3452eb49b26ff82fce41aad1cf1bc0db) includes the following:

``` js
var p = new Proxy([0,0,0,0,0], {});
p.length = 1;
```

This crashes Edge presently (nice find :+1:). While we are working on a fix I wonder if we can disable this test temporarily? Right now edge users are unable to see their compat score :(

**Comment by webbedspace** [comment]
While I personally regret having to add a special case for any platform, no matter how temporary, I can agree that knowingly crashing the browser is rather bad UX regardless.

**Comment by kangax** [comment]
Back in the days we had a module/import test that would crash Chrome, so I also disabled it at some point, with the note. I think this is a fair decision.

**Comment by bterlson** [comment]
Thanks guys. I personally regret shipping with this crash bug so regret all around! :-P

Will let you know once we have a fix out!

**Comment by zloirock** [comment]
@bterlson also
`Reflect.defineProperty(Object.defineProperty({}, 'x', {value: 1}), 'x', {value: 2})` -> `TypeError`, should be `false`, the same in other cases.

`Reflect.setPrototypeOf.length` -> `3`, should be `2` (wtf?)
`Reflect.get.length` -> `3`, should be `2`
`Reflect.set.length` -> `4`, should be `3`

**Comment by bterlson** [comment]
@zloirock Indeed! I think we are tracking all of these already (thanks to test262) but I will double check.

Anything else I should investigate while I'm at it?
