### ISSUE TITLE
Incorrect Proxy tests

### ISSUE THREAD

**Issue by anba** [compat-table/compat-table#594]
1. "Proxy, internal 'get' calls - ToPrimitive"
   
   The result array is `[ Symbol(Symbol.toPrimitive), "valueOf", "toString", Symbol(Symbol.toStringTag) ]`, `Object.prototype.toString` step 16 performs [[Get]] for `Symbol.toStringTag`
2. "Proxy, internal 'get' calls - HasBinding"
   
   The proxy's target object needs to be `{foo: <some value>}`, the result array is then `[ Symbol(Symbol.unscopables), "foo", "foo" ]`. 8.1.1.2.1 HasBinding(N), step 5. 
3. "Proxy, internal 'get' calls - RegExp constructor"
   
   The result array should be `[ Symbol(Symbol.match), "constructor", "source", "flags" ]`, cf. 21.2.3 The RegExp Constructor, step 1 and 7.2.8 IsRegExp, step 2
4. "Proxy, internal 'get' calls - RegExp.prototype[Symbol.split]"
   
   The proxy target needs to have a valid `flags` property, cf. RegExp.prototype [ @@ split ] ( string, limit ), step 7 and 21.2.3.2.2 Runtime Semantics: RegExpInitialize, step 7. 
   The result array is then going to be `[ "constructor", "flags", Symbol(Symbol.match), Symbol(Symbol.toPrimitive), "toString", Symbol(Symbol.toStringTag) ]`. The last three entries are caused by 21.2.3.2.2 Runtime Semantics: RegExpInitialize, step 2.
5. "Proxy, internal 'get' calls - Array.prototype.concat"
   
   `arr.constructor = void 0` to execute 9.4.2.3 ArraySpeciesCreate step 7, otherwise step 8 throws a TypeError. The result array is then `[ "constructor", Symbol(Symbol.isConcatSpreadable), "length", "0", Symbol(Symbol.isConcatSpreadable), "length", "0" ]`.
6. "Proxy, internal 'get' calls - Array.prototype.splice"
   
   The correct result array should be `[ "length", "constructor", "1", "2", "3", "length", "constructor", "2", "1" ]`.
7. "Proxy, internal 'get' calls - Array.prototype.toString"
   
   The correct result array is: `[ "join", Symbol(Symbol.toStringTag) ]`
8. "Proxy, internal 'get' calls - String.prototype.match"
   
   The call should be `String.prototype.match.call("", p)`.
   The result array is then: `[ Symbol(Symbol.match), Symbol(Symbol.toPrimitive), "toString", Symbol(Symbol.toStringTag) ]`
   Similar issues in "Proxy, internal 'get' calls - String.prototype.replace", "Proxy, internal 'get' calls - String.prototype.search" and "Proxy, internal 'get' calls - String.prototype.split".
9. "Proxy, internal 'get' calls - Date.prototype.toJSON"
   
   The proxy target needs to define a `toISOString` method, cf. 20.3.4.37 Date.prototype.toJSON, step 5. The correct result array is: `[ Symbol(Symbol.toPrimitive), "valueOf", "toString", Symbol(Symbol.toStringTag), "toISOString" ]`
10. "Proxy, internal 'set' calls - Array.prototype.splice"
    
    The correct result array is: `[ "3", "2", "1", "length" ]`. The loop in 22.1.3.25 Array.prototype.splice, step 21 runs backwards.
11. "Proxy, internal 'set' calls - Array.prototype.unshift"
    
    The correct result array is: `[ "5", "3", "2", "0", "1", "length" ]`. See 22.1.3.28 Array.prototype.unshift, step 7
12. "Proxy, internal 'deleteProperty' calls - ArraySetLength"
    
    This test is invalid, the `A` parameter of 9.4.2.4 ArraySetLength is an Array exotic object, not the original receiver object. That means it's not possible to observe the calls to [[Delete]] in step 19b.

**Comment by webbedspace** [comment]
Thank you - I'd been hoping for a second opinion on these.

> "Proxy, internal 'get' calls - Array.prototype.concat"

Shouldn't there be only be one occurrence of `Symbol.isConcatSpreadable, "length", "0"` in the results array? The call only concatenates p with itself once.

**Comment by anba** [comment]
The `items` variable (22.1.3.1 `Array.prototype.concat`, step 6) contains the this value and the arguments. So IsConcatSpreadable is getting called twice for `Array.prototype.concat.call(p,p);`.

**Comment by webbedspace** [comment]
In 19f6846 I modified various tests that unwittingly (as in, as an unanticipated side-effect) called Object#toString, ToPrimitive, etc. so that their proxied objects now have empty own methods that override these, and the observed calls are limited (where feasible) to those unique to the tested internal method. If you see any more problems, then do tell.

**Comment by anba** [comment]
Two tests are still wrong:

```
$ bin/es6draft-dev --timers testscripts/validate-compat.js ../compat-table/data-es6.js
Progress: [----------------------------------------------------------------------------------------------------]
Wrong result in test: 'Proxy, internal 'get' calls - RegExp.prototype[Symbol.split]'
Wrong result in test: 'Proxy, internal 'get' calls - String.prototype.match'
Completed 565 tests successfully [Failures 2 of 567 tests]
```

(The test runner is [this script](https://gist.github.com/anba/fd208f8f0f691c5f0475), in case you want to re-run the tests. )

---

"Proxy, internal 'get' calls - RegExp.prototype[Symbol.split]":

The `string` arguments for `RegExp.prototype [ @@ split ]` is not set, so it defaults to `"undefined"`

``` js
js> {
        var get = [];
        var constructor = Function();
        constructor[Symbol.species] = Object;
        var p = new Proxy({ constructor: constructor, flags: '', exec: function() { return null; } }, { get: function(o, k) { get.push(k); return o[k]; }});
        RegExp.prototype[Symbol.split].call(p);
get }
[ "constructor", "flags", "exec", "exec", "exec", "exec", "exec", "exec", "exec", "exec", "exec" ]
```

I guess you wanted to test the empty string case? (21.2.5.11, step 22)

``` js
js> {
        var get = [];
        var constructor = Function();
        constructor[Symbol.species] = Object;
        var p = new Proxy({ constructor: constructor, flags: '', exec: function() { return null; } }, { get: function(o, k) { get.push(k); return o[k]; }});
        RegExp.prototype[Symbol.split].call(p, "");
get }
[ "constructor", "flags", "exec" ]
```

---

"Proxy, internal 'get' calls - String.prototype.match":

The result array also contains `Symbol.toPrimitive`.

``` js
js> {
        var get = [];
        var proxied = {};
        proxied[Symbol.toPrimitive] = Function();
        var p = new Proxy(proxied, { get: function(o, k) { get.push(k); return o[k]; }});
        "".match(p);
get}
[ Symbol(Symbol.match), Symbol(Symbol.toPrimitive) ]
```
