### ISSUE TITLE
spread/rest backed out from Chrome 45

### ISSUE THREAD

**Issue by mgol** [compat-table/compat-table#595]
Due to [last minute problems](https://code.google.com/p/v8/issues/detail?id=4298#c7) spread & rest have been [backed out](https://chromium.googlesource.com/v8/v8.git/+/8735d38ed6cd44a5dae63047a3ed867f4c8769b6) from Chrome 45 beta.

**Comment by webbedspace** [comment]
Does this mean they should be changed to `false`, or `flag`? (i.e. will the Experimental Javascript flag still enable them in release builds?)

**Comment by mgol** [comment]
IMO `false` for spread & `flag` for rest. The flag will enable both but spread is broken. Maybe it would be worthwhile to add the test that it works correctly to the existing one.

Basically, in Chrome 45 with the flag enabled `[1, 2, ...[3]]` will expand to `[1, 2, <empty slot>, 3]` instead of the expected `[1, 2, 3]`.
