### ISSUE TITLE
Guards and trademarks (alternative to static typing)

### ISSUE THREAD

**Issue by RdeWilde** [compat-table/compat-table#598]
Guards seemed to be planned for ES7, but I can't find them in the compatibility table. Is this functionality still planned? Are there any frameworks that already support it?

http://wiki.ecmascript.org/doku.php?id=strawman:guards
http://wiki.ecmascript.org/doku.php?id=strawman:trademarks

**Comment by zloirock** [comment]
Last modified: 2011/05/25, missing in [tc39/ecma262](https://github.com/tc39/ecma262). Currently any plans maximum about [this](https://github.com/rwaldron/tc39-notes/blob/6d91c21077ea8b0eb0e9eb7e262572c23374f8c7/es6/2014-09/sept-25.md#types).

**Comment by ljharb** [comment]
If it's not on https://github.com/tc39/ecma262, it's not planned for ES7.

Things on the old and outdated ecmascript.org wiki are from when ES6 was still young.
