### ISSUE TITLE
Remove async generators and RegExp.escape test from ES7

### ISSUE THREAD

**Issue by thomasfosterau** [compat-table/compat-table#603]
The async generators proposal has been withdrawn (see [this commit](https://github.com/tc39/ecma262/commit/6f35ca7aa0415e3992af304987380b1f5cbab191)) and probably needs to be replaced by a test for [Observables](https://github.com/zenparsing/es-observable).

Additionally, it seems as though RegExp.escape has been rejected (see [this commit](https://github.com/tc39/ecma262/commit/16ef4b6512bd5a975bb8dce882279212e14ebe1e)) and should be removed.

**Comment by ljharb** [comment]
I'd like to wait until the replacement proposal for "escaping user input to make a regex" arrives - I'm not as convinced that it was rejected "definitively" as-is by the committee.

As for Observables, that would definitely be a good thing to add, as it's at stage 1.

**Comment by thomasfosterau** [comment]
My impressions from reading [this](https://github.com/rwaldron/tc39-notes/blob/master/es7/2015-07/july-28.md#62-regexpescape) and having a general poke around is that RegExp.escape at least needs to be moved back to the 'pre-strawman' phase. It sounds to me as though it will be replaced by a template string-based proposal.

I'll have a session of cross-referencing the ES7 compat-table with the tc39/ecma262 repo and send in a  pull request in a few hours with Observables included (and whatever else has changed).

**Comment by ljharb** [comment]
You're right, I'll drop the stage now.

Please try to make one PR for each change, rather than bunching them up :-)

**Comment by thomasfosterau** [comment]
Will do!

**Comment by zloirock** [comment]
`RegExp.escape` definitely should be removed from the table. I also leave it in `core-js` as a non-standard feature, but `RegExp.escape` in the table can confuse users and they can start to use it as a "part of ES7".

**Comment by zloirock** [comment]
> I'm not as convinced that it was rejected "definitively" as-is by the committee.

https://github.com/zloirock/core-js/issues/116 it's enough for me

**Comment by kangax** [comment]
Does anyone know what kind of template string -based solution `RegExp.escape` was "replaced" with?

**Comment by zloirock** [comment]
https://github.com/mikesamuel/regexp-make-js , but it's still not a proposal.

**Comment by ljharb** [comment]
fwiw, I still believe that a template string approach isn't the right one, and I hope to revisit RegExp.escape in the future.

**Comment by kangax** [comment]
I like `RegExp.escape` because it's easy to grasp and has been used for a while (as shim or in libs, etc.). But then... maybe I'm just clinging on the old concept where new one could bring a more extensible or future-proof or whatever else paradigm. Why don't you like it @ljharb?

**Comment by ljharb** [comment]
I like the original simple `RegExp.escape` - I actually also like the template string approach that the committee has chosen to explore, I just think both are needed.

The simple, polyfillable/shimmable one is something that virtually every lib has implemented, often incorrectly, and I think codifying this version now is more important than providing a "new or whatever else" paradigm (although that's important too).
