### ISSUE TITLE
Add MS Edge preview

### ISSUE THREAD

**Issue by dstorey** [compat-table/compat-table#629]
Edge 10532 was released a little while ago, with a number of ES6 features turned on by default and ES7 features behind a flag https://dev.modern.ie/platform/changelog/desktop/10532/

Would be great to include in both tables.

For version numbers, we agreed on CanIUse… to include the EdgeHTML version number (i.e. Edge 12 for 10240, and Edge 13 for preview builds), as build numbers are long and can't be predicted ahead of time, and the app version (20 and 21 currently) isn't included in the UA string, and could potentially change independent of the platform.

**Comment by kangax** [comment]
So... am I understanding correctly that you suggest to rename Edge to Edge 12 and add Edge 13 (as a "nightly" version of Edge)?

**Comment by dstorey** [comment]
@kangax yes. See for example http://caniuse.com (the star on the browser name explains it). Some discussion in https://github.com/Fyrd/caniuse/issues/1822

**Comment by kangax** [comment]
That's ok with me, feel free to send a PR!

**Comment by deltakosh** [comment]
Done here: https://github.com/kangax/compat-table/pull/633
