### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by marcello3d** [compat-table/compat-table#63]
First off, super useful data source! 

I would like to use this data in an automated fashion in an node.js module, but concerned about licensing. 

I wasn't sure if you intended to put a license on it, but it would be awesome if you released it as open source under something like [zlib](http://opensource.org/licenses/Zlib) or [MIT](http://opensource.org/licenses/MIT).

Cheers!

**Comment by kangax** [comment]
Hi there,

Most of my public code is licensed under MIT, and this is no exception :) Just added LICENSE in the repo.

Feel free to use for whatever, just give attribution, and I'd be curious to see what you come up with.

**Comment by marcello3d** [comment]
Awesome, thanks! I'll post a link once I get somewhere. :-)
