### ISSUE TITLE
Re-enable zooming on mobile devices

### ISSUE THREAD

**Issue by claudepache** [compat-table/compat-table#630]
I've noticed that it is no longer possible to zoom on my iPad (and I guess on many mobile devices). The culprit is that tag:

``` html
<meta name="viewport" content="width=device-width, user-scalable=no">
```

I’m certainly missing something, because I don't understand why such an instruction was added.

**Comment by webbedspace** [comment]
It was added in b568330. @williamboman Comments?

**Comment by williamboman** [comment]
The `user-scalable=no` is completely unnecessary - a bad case of copy/paste. Sorry! I'll open a PR to re-enable scaling
