### ISSUE TITLE
Array.values() support

### ISSUE THREAD

**Issue by a-ursino** [compat-table/compat-table#639]
hi 
according the table the Array.values() method is supported on node 4.0, 
but when i run [1, 2, 3].values() with node 4.1.1

Alessandros-MacBook-Pro:node-es6 killanaca$ node --version
v4.1.1
Alessandros-MacBook-Pro:node-es6 killanaca$ node

> [1, 2, 3].values()
> TypeError: [1,2,3].values is not a function
>     at repl:1:11
>     at REPLServer.defaultEval (repl.js:164:27)
>     at bound (domain.js:250:14)
>     at REPLServer.runBound [as eval](domain.js:263:12)
>     at REPLServer.<anonymous> (repl.js:393:12)
>     at emitOne (events.js:82:20)
>     at REPLServer.emit (events.js:169:7)
>     at REPLServer.Interface._onLine (readline.js:210:10)
>     at REPLServer.Interface._line (readline.js:549:8)
>     at REPLServer.Interface._ttyWrite (readline.js:826:14)

**Comment by zloirock** [comment]
Thanks.

![...](https://habrastorage.org/files/e8c/50b/eca/e8c50becae1d4277be0251a4c44f04cc.png)

[Looks like related.](https://github.com/nodejs/node/wiki/API-changes-between-v0.10-and-v4?utm_source=nodeweekly&utm_medium=email#javascript-arrayvalues-has-been-removed-since-012)
