### ISSUE TITLE
Add Android browsers to compat tables

### ISSUE THREAD

**Issue by restlessdesign** [compat-table/compat-table#64]
I would find it very helpful to see Android browsers at a glance in this table as well. If anyone knows of a existing resource, I’ll happily contribute a PR!

**Comment by kangax** [comment]
Yes, that would be nice. I only have iPhone with iOS 6.1.3 to test.

**Comment by michaelficarra** [comment]
@kangax: You can use the Android emulator: http://developer.android.com/tools/help/emulator.html

**Comment by kangax** [comment]
I tried using Android Emulator but it's horrifically slow on my (not so slow) machine...

**Comment by rick-li** [comment]
You might need intel's Haxm
http://software.intel.com/en-us/android/articles/intel-hardware-accelerated-execution-manager
along with intel x86 images.

**Comment by kangax** [comment]
Found this: http://army8735.me/es5-compat/

**Comment by MetaMemoryT** [comment]
:+1: for android, its confusing with its switch to chrome engine built in.  This table could help clarify everything.

**Comment by zloirock** [comment]
With Sauce Labs testing Android on emulator does not create any serious problems.

Android 4.4+ contains in user agent Chrome version, their results are the same. For hide flagged features I added `ignore_flagged` option.

I can't run 2.3 emulator with any page.

ES6 page crushes 4.4 browser in the emulator, but browser works with ES5 and ES7 pages. Need test it on a real device.

**Comment by zloirock** [comment]
@kangax @webbedspace I think it can be closed. Also need to add results 2.3 to ES5 table. Or something else?

**Comment by kangax** [comment]
I think this could be closed too. Thanks for adding that in @zloirock, nice to finally have those results! I see that caniuse shows 4.1, 4.3, and 4.4.4 so I think we're good without 2.3 for now (unless someone requests it? or if it's still widely used? I have no idea)

**Comment by zloirock** [comment]
I think, it's still enough popular (~0.5% in runet), sometimes I have issues about it in some projects. Need to add it if will be available device with Android 2.3.
