### ISSUE TITLE
new ECMAScript 7 strawman: lookbehinds in regular expressions

### ISSUE THREAD

**Issue by Mithgol** [compat-table/compat-table#646]
The commit tc39/ecma262@639d9660456e2e55b43ad1126341bc96acf4b7e3 has introduced a new ECMAScript 7 strawman: “[RegExp Look-behind](http://www.akenotsuki.com/misc/srell/lookbehind_proposal.html)” (8 days ago).

I don't have time to contribute a corresponding test to the `compat-table` and thus I decided to create a mere issue instead. (To raise awareness.)

**Comment by bterlson** [comment]
Worth noting that while BE is currently listed as champion, that is not the case. This proposal may be removed soon if a new champion is not found :( I really hope someone can pick it up though, I want this baaad.

**Comment by kangax** [comment]
My god, I've been waiting for look-behind for years (so that we no longer need to reverse a string and look-ahead instead). Want this too!

**Comment by Mithgol** [comment]
@bterlson That's horrible. What can be done for a new champion to appear? Should we all try to further raise the awareness by notifying some of the possible concerned third parties? (For example, we could try to reach Mozilla Foundation through their [es-discuss](https://mail.mozilla.org/listinfo/es-discuss) mailing list or jQuery Foundation through their [jquery/standards](https://github.com/jquery/standards/issues) repo.)

**Comment by kangax** [comment]
When I grow up and get rich, I'll be paying people to work on awesome open source projects.

**Comment by Mithgol** [comment]
@bterlson Help me through my initial [denial stage](https://en.wikipedia.org/wiki/K%C3%BCbler-Ross_model#Stages). Why do you think that Brendan Eich is not actually a champion of this proposal?

**Comment by bterlson** [comment]
We had a chat about it at last TC39 meeting.

I am looking for champions, but if you want to search as well the official policy is to take such requests to es-discuss!

**Comment by strings28** [comment]
How could I do take on championing this? I have a project that really needs some regex love in Node.js.

**Comment by Yomguithereal** [comment]
What can one do to help? I would hate to learn that lookbehinds were not added to JavaScript because nothing was done to ensure it.

**Comment by bterlson** [comment]
You need a TC39 champion, that is someone who attends meetings, deeply understands the proposal, responds to feedback, and generally prods the proposal through the process. If you wan to find such a person, es-discuss is a reasonable place to do so. You can also become a dues-paying member of ECMA and start attending TC39 meetings!

I am hoping to get a champion sorted by next week... will let you guys know if I find someone!

**Comment by sholladay** [comment]
This is important to me. I find myself wishing it existed very frequently.

**Comment by kangax** [comment]
For those who don't know, @bterlson found a champion so I suppose we can add this to table now?

**Comment by Mithgol** [comment]
For future references, tc39/ecma262@a9350985dea0a6270a2339da01621435ef7faa77.

P. S.   Thanks for the info.
