### ISSUE TITLE
ES7 stages updated

### ISSUE THREAD

**Issue by sarahkadar** [compat-table/compat-table#652]
- Async is Stage 3 (per https://github.com/tc39/ecma262/commit/2fa3ca4bbc8e9feece0cce363b076a1942e8c6ba)
- Rest/spread is Stage 2 (per https://github.com/tc39/ecma262/commit/c4a04e1c6015a2634877558d2215847403127336)

**Comment by ljharb** [comment]
Thanks for the reminder!
