### ISSUE TITLE
Tail calls on WebKit

### ISSUE THREAD

**Issue by ebraminio** [compat-table/compat-table#655]
WebKit now has tail calls support per https://www.webkit.org/blog/4054/es6-in-webkit/ perhaps it can be reflected somehow.

**Comment by kangax** [comment]
Wow, that's amazing. If this is true, WK is the first browser to get them. However, I can't reproduce it. Just got latest nightly build and not only our 1e6-deep-recursion fails, but it seems to go as high as only ~28K (and the same in Safari 9).

Can anyone else reproduce? /cc @ljharb @zloirock @webbedspace

**Comment by ljharb** [comment]
I see the same thing. @Constellation, is it behind a flag?

**Comment by ebraminio** [comment]
**Update**: It seems it is done now and es6 table is also updated.

I think I should apoligize for this. With more investigation it seems this is still unfinished work http://trac.webkit.org/changeset/189336 as the main issue seems is still open on the bug tracker https://bugs.webkit.org/show_bug.cgi?id=146477 but also many works is done here http://trac.webkit.org/log/branches/jsc-tailcall/Source/JavaScriptCore in order to support it.

**Comment by webbedspace** [comment]
When the current table test eventually passes, we'll be sure to add it to the results.
