### ISSUE TITLE
Add links to six-speed for each (applicable) test

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#656]
http://kpdecker.github.io/six-speed/

/cc @kpdecker

**Comment by afmenez** [comment]
This table was last updated 2 years ago, it only shows results for obsolete browsers.  Is it still relevant?

**Comment by ljharb** [comment]
Given that the last commit there was 2 years ago, I’m inclined to close this until it’s development picks back up.

**Comment by zloirock** [comment]
I agree.
