### ISSUE TITLE
Colorblind friendly

### ISSUE THREAD

**Issue by hyperhtml** [compat-table/compat-table#66]
I know this is probably an odd request, but I am red/green color blind and I am not able to see the difference in the table, beyond the yes/no.  Is there a possibility for colorblind (red/green) friendly colors?

**Comment by michaelficarra** [comment]
A better solution would be to assume everyone has full colourblindness and use some other easily spotted indicator. I recommend crosshatching in the `No` cells.

**Comment by kangax** [comment]
I don't mind of course, as long as it would still be comfortable for color-capable folks. Which red/green colors would work for you?

**Comment by Skalman** [comment]
I slightly modified the colors: http://skalman.github.io/es5-compat-table/

To me it looks like that should be enough: http://colorfilter.wickline.org/?a=1;r=;l=9;j=1;i=1;n=1;u=skalman.github.io/es5-compat-table;t=m

**Comment by kangax** [comment]
@Skalman looks good to me! @hyperhtml @michaelficarra what do you guys think?

**Comment by hyperhtml** [comment]
@kangax: I think this does the job.  

Nice choice @Skalman

**Comment by kangax** [comment]
@hyperhtml Cool. In that case, @Skalman feel free to send PR.

**Comment by jamesplease** [comment]
Accommodating color-blind folks is definitely important, but I think the current color scheme impedes the usability of the document. It's a well-documented fact that really bright complementary colors, like red and green*, are [not nice to look at when next to one another](http://commons.wikimedia.org/wiki/File:Red_and_green_800_%C3%97_600,_horizontal.png). Though this might just apply to any two super-bright colors placed next to one another.

More muted colors, like `.no { rgb(185, 89, 89); }` and `.yes { color: rgb(95, 148, 95); }` put less strain on the retinas, I think, and could make this document nicer on users. But I'm unsure how easy they are to distinguish when color blind.

*So they're not quite complementary in the RGB model, but they're close enough.

**Comment by Skalman** [comment]
Those colors make the table much more dull and seem to make the table lighter, which worsens the contrast with the text (mainly the references like [1]). If we were to make the colors more desaturated I would also prefer to have a slightly darker tone.

If there is an interest in trying this, I can easily make the change.

**Comment by kangax** [comment]
I'm open to ideas. As long as everyone is satisfied.
