### ISSUE TITLE
Update TypeScript

### ISSUE THREAD

**Issue by Gouigouix** [compat-table/compat-table#664]
Hello,

It is possible to update TypeScript to 1.6.2 for really compare ?

Thank you.

**Comment by zloirock** [comment]
Interesting. Passed `extends null`, `block-scoped classes`, `super in methods, property access` and `
empty patterns in parameters`. Not passed TDZ tests and `constructor requires new`, but it's not passed in 1.5 too. No ideas why it was enabled in the table.

**Comment by estaub** [comment]
@zloirock   The hover tooltip on TypeScript on http://kangax.github.io/compat-table/es6/#typescript says that it's showing "1.5 alpha".  Checking the tests in your comment, I'd guess the tooltip is stale.

(totally off-topic!!!) While you're in there, you might want to fix the footnote reference on Chrome; it reads "[0]", and of course there's no such footnote.  The footnote should probably refer to chrome://flags/#enable-javascript-harmony .

Many thanks!

**Comment by zloirock** [comment]
@estaub thanks for report.
