### ISSUE TITLE
PhantomJS 1.9.x / 2.0 on the ES5 table

### ISSUE THREAD

**Issue by rconnamacher** [compat-table/compat-table#666]
This project updated its ES5 table with PhantomJS 2.0 back in February, which simply shows that it supports all of ES5. But because there aren't yet official Linux binaries for 2.0, the 'phantomjs' NPM module and test frameworks relying on it are still stuck on version 1.9.18.

It'd be very helpful to see PhantomJS 1.9 re-introduced there, maybe behind that 'obsolete platforms' checkbox.

**Comment by ljharb** [comment]
I definitely agree the data should be kept forever and marked "obsolete" rather than throwing it out. Reconstructing this data manually is always going to get harder and harder as time goes by.

https://github.com/kangax/compat-table/commit/afd609160bc846bbe96b15bb563285bc9d6ba455 is the original commit - we should be able to retrieve the data from there.

**Comment by dcleao** [comment]
Hit this :-( Need compat info for current released version (1.9..)

**Comment by zloirock** [comment]
[Already available official binaries for 2.1.](http://phantomjs.org/releases.html) I think, it should be closed.

**Comment by BillyWM** [comment]
Although PhantomJS proper may be at 2.1, there are still older versions floating around inside other projects and upgrading it there may not be a quick fix. Case in point, I recently tried out mocha-phantomjs for testing our application, which is bundled with Phantom 1.9, and apparently doesn't run some Javascript correctly vs Chrome.

In my particular case I have the option of switching to Phantom proper but it would be helpful to have a table that can tell me at a glance e.g. "oh, 1.9 needs a polyfill for Array.prototype.map"

**Comment by ljharb** [comment]
See https://github.com/kangax/compat-table/issues/666#issuecomment-149423285 - I think we should definitely keep 1.9 in the table as "obsolete" - a PR to restore this is welcome.
