### ISSUE TITLE
Enumeration order in V8

### ISSUE THREAD

**Issue by zloirock** [compat-table/compat-table#670]
``` js
var t = {};
'abcdefghijklmnopqrst'.split('').forEach(_ => t[_] = _);
console.log(Object.getOwnPropertyNames(t).join(''));     // gbhatcfrkeplqnsmojid
console.log(Object.keys(Object.assign({}, t)).join('')); // gbhatcfrkeplqnsmojid
console.log(Object.keys(t).join(''));                    // abcdefghijklmnopqrst
```

but in the table `Object.getOwnPropertyNames` and `Object.assign` V8 enumeration order marked as correct. Related comments [here](https://github.com/kangax/compat-table/commit/afa89886cdf8a954f5572b3c96f50122582c9a08).

@webbedspace can you change tests for cover this case? I don't want to change something here because I can break specific logic some engines.

**Comment by jandem** [comment]
The JSON.stringify test (and maybe others too) is no longer correct after this change landed.

**Comment by zloirock** [comment]
@webbedspace `Object.assign` test also has a bug and with the current way (getters) I can't reproduce V8 problem.

**Comment by zloirock** [comment]
Setters-based solution cover this case.
