### ISSUE TITLE
Edge 13 data out of date

### ISSUE THREAD

**Issue by Studio384** [compat-table/compat-table#671]
According to the table, Edge 13 supports 80% of all ES6 features but with flags disabled Edge 13.10576 reports to support 84%. This is what has to be updated:

spread (...) operator: 12 -> 15
for..of loops: 6 -> 7
template strings: 4 -> 5
RegExp "y" and "u" flags: 2 -> 4
arrow functions: 12 -> 13
generators: 0 -> 25
Map: 16 -> 17
Set: 16 -> 17
Reflect: 16 -> 17
Symbol: 9 -> 10
String.prototype methods: 7 -> 8
Array static methods: 8 -> 10
Array.prototype methods: 9 -> 10
prototype of bound functions: 4 -> 5
Proxy, internal 'get' calls: 18 -> 19
Proxy, internal 'ownKeys' calls: 2 -> 3
RegExp.prototype.compile: No -> Yes

**Comment by zloirock** [comment]
Can you add PR?

**Comment by kangax** [comment]
Is there a virtual image for Edge 13 somewhere?

**Comment by sarahkadar** [comment]
I've been working on this, (Edge 13 + ES7, flagged + unflagged) but I have yet to find the time to finish this. The ES6 scores also need to be adjusted IIRC

Edit: ahem, the issue was about ES6 scores, eh, sorry.

**Comment by sarahkadar** [comment]
As for a virtual image, unfortunately no, there is Remote.IE but it seems to lag behind in builds, the last time I checked it

**Comment by sarahkadar** [comment]
All done, creating PR #677
