### ISSUE TITLE
let tests score 0 when tests complete

### ISSUE THREAD

**Issue by olvlvl** [compat-table/compat-table#672]
Hi,

It looks like the `let` tests are not running properly. I'm using Firefox 40, and when I run the tests the `let` tests goes to "8/10" then when all the tests complete the score goes to "0/10". What's surprising is that _basic support_, for instance, **is** supported by Firefox 40:

``` js
let foo = 123;
return (foo === 123);
```

**Comment by zloirock** [comment]
You didn't saw the [note](http://kangax.github.io/compat-table/es6/#fx-let-note)? `let` available in console or in scripts with the special type, but not in a usual scripts. Before the full page loading you saw `Traceur` results.

**Comment by olvlvl** [comment]
Still that doesn't explain why the test fails, does it?

Also, where is this note supposed to be?

<img width="437" alt="screen shot 2015-10-26 at 10 52 09" src="https://cloud.githubusercontent.com/assets/155998/10725893/af8349d8-7bcf-11e5-8ab8-8b8a1e55059c.png">

**Comment by zloirock** [comment]
Because they are running from the script without special type? :)

**Comment by olvlvl** [comment]
In that case the test is misleading, all I see is that tests are failing. Why don't you test these features in the appropriate context?

**Comment by zloirock** [comment]
So you propose try to run tests also with `javascript 1.8` type in all engines just because `let` not supported in FF? Maby also add special cases for all other notes? I don't think it's a good idea.

**Comment by zloirock** [comment]
Hmm, by idea tests builder [already has code for that](https://github.com/kangax/compat-table/blob/gh-pages/build.js#L680-L687).

**Comment by olvlvl** [comment]
There's no need to run every test in every JavaScript version, but when a feature is clearly targeting a specific version it should run in that version. I don't know your implementation, so I can't imagine how easily/difficult it is to implement. If it's too complicated at least mark the _not really falling_ test with a neutral color, like grey, because the note is out of view and all we can see is _red failing tests_.

**Comment by olvlvl** [comment]
Comment at the same time ;) So, does it mean that it would be trivial to implement?

**Comment by zloirock** [comment]
Makes sense only show it as flagged also in the results of the current browser.

cc @kangax @webbedspace @ljharb your opinion?

**Comment by webbedspace** [comment]
The "current browser" column is not really designed to provide an identical level of detail as the fixed results columns - for one thing, it's not even possible for it to see whether Chrome's or Edge's "Experimental Javascript" flag is enabled, let alone change it and rerun the tests. It's designed to be run in versions of browsers beyond those listed on the table, so that the latest releases can be checked without assuming anything about them or their level of support. Interpreting these results is generally the burden of the reader.

(I suppose a note to this effect should be added to accompany the Current Browser column.)

**Comment by olvlvl** [comment]
FF41, FF42, FF43 columns display that `let` is not implemented, which is not true.

**Comment by webbedspace** [comment]
Here's what the columns say:
![](https://i.imgur.com/AL71T9F.png)
As you can see, the results are marked as `Flag`, meaning that the implementation is inaccessible to normal JS usage in the platform, but requires a special pragma, user-side preference or command-line flag. That is to say, it violates the ES6 specification by placing a non-compliant implementation restriction. The presence of these `Flag` results is denoted by the coloured corner of the `0/10` cells. I don't see what else needs to be added.

**Comment by olvlvl** [comment]
But you need to unfold the row to see these flags. Also, they are not in the "My browser" column, and since the table is so wide, flags in FF columns are mostly out of view. I understand that it's not easy to provide the same level of information for "My browser", but maybe you could duplicate the corresponding column (e.g. FF 41) and place them side by side, that would make for easy comparison.

**Comment by kangax** [comment]
>  Also, they are not in the "My browser" column, and since the table is so wide

Hm, we could mark "flag" the same way in "current browser" column, but only if flag is currently enabled in your browser. Problem is — I'm not sure we can test programmatically if the flag is enabled in your browser AND even if we can and the flag is not enabled, it will still be confusing, don't you think?

**Comment by olvlvl** [comment]
"My browser" is testing the features of the browser as it is, whether magical flags are enabled or not, and that's a good thing. What do you think about adding the corresponding column after "My browser"? e.g. "FF 41" when I'm running Firefox 41. That way I can check what features are actually available for my browser by comparing the two columns, flags and notes won't be that easily missed.

**Comment by kangax** [comment]
If you select "FF 41" column it gets highlighted and you can compare current with selected. There's been some talk about improving this particular part of UI, e.g. hiding everything else except current and selected column. I'm not a fan of such solution (or the one where selected column jumps next to the current one) but I'm open to explore more options.

**Comment by olvlvl** [comment]
Thanks for your message @kangax, I'll click on the column title in the mean time.
