### ISSUE TITLE
Data Edge and Firefox switched when sorting on features

### ISSUE THREAD

**Issue by Studio384** [compat-table/compat-table#673]
When you sort on features, I noticed that Edge and Firefox which have the first 2 collums, switch data. The numbered scores (like 12/15) are correct, however the individual features are switched between the twoo.

**Comment by sarahkadar** [comment]
Not just the first two... all of them...

**Comment by Studio384** [comment]
This is still not fixed.

**Comment by sarahkadar** [comment]
I have a PR waiting for review @kangax :)
