### ISSUE TITLE
ES1(!) test: inherited properties shadowed by non-enumerable properties should not be enumerated by for-in loop

### ISSUE THREAD

**Issue by claudepache** [compat-table/compat-table#675]
Hi,

There is a longstanding bug in both WebKit ([bug 38970](https://bugs.webkit.org/show_bug.cgi?id=38970)) and V8 ([issue 705](https://code.google.com/p/v8/issues/detail?id=705)), still not yet resolved, that inherited enumerable properties shadowed by non-enumerable properties are incorrectly enumerated by for/in loops.

Here is a test case using only ES1 features:

``` js
Object.prototype.length = 42;
for (var i in Array.prototype) {
    if (i == 'length') {
        delete Object.prototype.length;
        return false;
    }
}
delete Object.prototype.length;
return true;
```

It may be worth to add a test in the ES5 table, although there is nothing specific to ES5: I have just checked that this case is already clearly specified back in the first edition of ECMAScript; but we don’t have an ES1 compatibility table...

**Comment by ljharb** [comment]
``` js
(function () {
Object.prototype.length = 42;
for (var i in Array.prototype) {
    if (i == 'length') {
        delete Object.prototype.length;
        return false;
    }
}
delete Object.prototype.length;
return true;
}())
```

Indeed the previous function returns `false` for me in Safari and Chrome, but `true` in Firefox and IE.

I added a few more people to the webkit bug - and I'll bring it up to some v8 folks at the meeting next month.

This definitely seems like something that should go in the ES5 tests.
