### ISSUE TITLE
Object.observe is dead

### ISSUE THREAD

**Issue by mgol** [compat-table/compat-table#680]
`Object.observe` is dead: https://mail.mozilla.org/pipermail/es-discuss/2015-November/044684.html

Should it be removed from the es7 list?

**Comment by ljharb** [comment]
Just in case, I think we should wait for the next TC39 meeting, which is in 3 weeks. However, assuming it's withdrawn, we absolutely should remove it then.

**Comment by mgol** [comment]
Sounds good.

## 

Michał Gołębiowski

**Comment by rambo-panda** [comment]
Do not want to remove!

**Comment by ljharb** [comment]
Object.observe is definitively withdrawn.
