### ISSUE TITLE
Add desctructuring + default value test

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#688]
I think we're missing a case where default value is used in destructuring (which at least FF is currently failing):

``` js
let { x = 1, y } = { }
```

**Comment by webbedspace** [comment]
Hmm? Isn't this test sufficient?
![](https://i.imgur.com/IACYlUN.png)

**Comment by kangax** [comment]
Oh, it is. I looked through all of them but missed `z:c = 3` at the end. Thanks.
