### ISSUE TITLE
add Function.prototype.toString preserving comments

### ISSUE THREAD

**Issue by redchair123** [compat-table/compat-table#69]
A recently-explored hack to pass multiline strings in javascript is to use comments (e.g. http://tomasz.janczuk.org/2013/05/multi-line-strings-in-javascript-and.html) This technique only works if Function.prototype.toString preserves the original content (and not some stripped version).  This technique does not work in firefox 16

**Comment by kangax** [comment]
Function decompilation is non-standard, unspecified, so it never worked consistently. I actually wrote about it 4 years ago (wow, time flies...) — http://perfectionkills.com/those-tricky-functions/

**Comment by redchair123** [comment]
Heh next time I will be sure to search your site.

OT: have you considered collecting these bits of wisdom and writing a book?

**Comment by kangax** [comment]
Anything related to DOM scripting gets outdated quick, so paper book would become irrelevant. Also hard to update. 

e-book makes more sense. But my blog is already like an e-book, so what's the point? :)

As for non-DOM stuff, there's already few great paper books out there (I reviewed some of them).
