### ISSUE TITLE
Add stage numbers to ES7 sections

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#694]
As suggested by @rauschma https://twitter.com/rauschma/status/665916146256896001

**Comment by ljharb** [comment]
Very good idea!

I don't think we need pre-stage-zero, but most of those are old harmony proposals from before the current process. If those proposals ever got picked up (like string padding, object.values/entries, etc), their result data would still be useful, so I think it's a good idea to keep the current ones, but not add anything new unless it's stage 0 or higher.
