### ISSUE TITLE
RegExp copy constructor

### ISSUE THREAD

**Issue by abozhilov** [compat-table/compat-table#696]
According to `21.2.3.1` point 5, RegExp constructor can be used to copy existing regex object. 

``` javascript
let r = /abc/g;
new RegExp(r) !== r; // true
```

As well in this form of copying can be set/reset flags: 

``` javascript
let r = /abc/g;
let r1 = new RegExp(r, 'i');
let r2 = new RegExp(r, r.flags + 'i');

r1.flags; // i
r2.flags; //gi
```

Hope all of the engines will implement that feature as just copying existing NFA instead of recompiling the regex again.

**Comment by zloirock** [comment]
I don't exactly understand this issue. [You mean that?](http://kangax.github.io/compat-table/es6/#test-miscellaneous_RegExp_constructor_can_alter_flags)

AFAIK from actual engines first example will be `false` only in the old `WebKit` like `PhantomJS`. I don't think makes sense extend this test for the second example.

**Comment by abozhilov** [comment]
Totally makes sense your comment! Thanks.
