### ISSUE TITLE
missing test - spread operating in destructing

### ISSUE THREAD

**Issue by spokorski** [compat-table/compat-table#698]
the compatibility table appears to be missing at least one of the use-cases for the spread operator:
`var [a, b, ...iter] = [1, 2, 3, 4, 5];`

according to the MDN documentation, this feature is not supported in chrome,
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator#Browser_compatibility
but the compatibility table lists chrome as passing 15/15 tests for the spread operator

**Comment by zloirock** [comment]
~~spread~~ [rest](http://kangax.github.io/compat-table/es6/#test-destructuring_rest)
