### ISSUE TITLE
Nitpicking: Correct/Preferred abbreviation of Firefox is Fx not FF

### ISSUE THREAD

**Issue by jnachtigall** [compat-table/compat-table#738]
See:
- https://news.ycombinator.com/item?id=7803666
- FAQ at the bottom of http://website-archive.mozilla.org/www.mozilla.org/firefox_releasenotes/en-US/firefox/releases/1.0.6.html or http://website-archive.mozilla.org/www.mozilla.org/firefox_releasenotes/en-US/firefox/releases/1.5.html: 

> How do I capitalize Firefox? How do I abbreviate it? Only the first letter is capitalized (so it's Firefox, not FireFox.) The preferred abbreviation is "Fx" or "fx".

**Comment by zloirock** [comment]
If I will see `Fx`, I just will not understand that this is Firefox. Previously, I did not see this reduction (at least - not often) but `FF` - constantly.

**Comment by mkurz** [comment]
I think `FF` is more understandable.

**Comment by ljharb** [comment]
-1 from me as well - regardless of what Mozilla says, everyone else abbreviates it as "FF"

**Comment by chicoxyzzy** [comment]
Closing as won't fix
