### ISSUE TITLE
IE9 and IE10 are now obsolete

### ISSUE THREAD

**Issue by graingert** [compat-table/compat-table#739]
"IE 10+" should be IE11 with IE9 and IE10 marked as obsolete

**Comment by zloirock** [comment]
[Why do you think so?](https://support.microsoft.com/en-en/lifecycle#gp/Microsoft-Internet-Explorer)

**Comment by graingert** [comment]
Windows Vista SP2 is out of Mainstream Support

**Comment by zloirock** [comment]
But still supported. And IE10+ includes IE11.

**Comment by graingert** [comment]
under that argument IE8 was still supported on January 11th...

**Comment by ljharb** [comment]
In this case "obsolete" to me feels more like "an engine most people don't use anymore". IE 9 and 10 don't fall into that bucket just yet, because official support is unrelated to usage.

**Comment by graingert** [comment]
@ljharb people still use IE6...

**Comment by ljharb** [comment]
@graingert "most". most people do not use IE 6. Let's not be overly pedantic here.

**Comment by graingert** [comment]
closing in favour of #740
