### ISSUE TITLE
Update Closure Compiler

### ISSUE THREAD

**Issue by caridy** [compat-table/compat-table#747]
I suspect compat-table is testing closure compiler with the default options without using externs to rewrite the polyfills (which is equivalent to babel-polyfill), that's why you see all the built-ins and built-ins extensions not supported in closure compiler.

@dimvar and @shicks, can you guys help @teppeis to level up the results of closure compiler?

**Comment by dimvar** [comment]
@shicks just added a command-line flag `--rewrite_polyfills` to use the polyfills. You need to build the compiler from head, it's not in the released compiler yet. See: https://github.com/google/closure-compiler/commit/f2eb08a075c1105423e96cf53c2a0aa1e2f98607

**Comment by teppeis** [comment]
@dimvar Thanks! I'll update compat-table result after next release.

**Comment by caridy** [comment]
:beers:

**Comment by caridy** [comment]
@dimvar I wonder what's going on with the built-in section from the table. I see WeakMap, WeakSet, Promise, Proxy, Reflect, and most symbols not implemented after using `--rewrite_polyfills`. I was expecting a little bit better support.

**Comment by Dominator008** [comment]
@caridy They are not implemented yet: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/RewritePolyfills.java#L239-L241. Proxy will probably not be implemented at all.
