### ISSUE TITLE
Tail calls elimination in non-strict mode

### ISSUE THREAD

**Issue by mgol** [compat-table/compat-table#750]
Currently the TCE test is only done in strict mode. WebKit Nightly supports it but only in strict mode. It'd be worthwhile to add a non-strict test similarly to ones for `const`/`let.

**Comment by zloirock** [comment]
[AFAIK TCO should be available only in strict mode.](http://www.2ality.com/2015/06/tail-call-optimization.html#tail_call_optimization_can_only_be_made_in_strict_mode)

**Comment by mgol** [comment]
Ah, I haven't though about it; it makes sense that those are strict-only. Sorry for the fuss!
