### ISSUE TITLE
`WeakSet.has(undefined)` will throw in some browsers (e.g.: android 5.1)

### ISSUE THREAD

**Issue by caridy** [compat-table/compat-table#754]
262 spec allows arbitrary arguments:
http://www.ecma-international.org/ecma-262/6.0/#sec-weakset.prototype.has

Step 5 of that algo returns false for any non-object value, and test-262 also verify that behavior. We should add that as another test for WeakSet.

**Comment by zloirock** [comment]
[Not only `WeakSet`, not only on `undefined`](https://github.com/zloirock/core-js/blob/v2.1.4/modules/_collection.js#L45-L46).

**Comment by caridy** [comment]
:clap:
