### ISSUE TITLE
Proxy internal [[DefineOwnProperty]] test seems wrong

### ISSUE THREAD

**Issue by saambarati** [compat-table/compat-table#757]
The test in question is:

```
// [[Set]] -> [[DefineOwnProperty]]
var def = [];
var p = new Proxy({foo:1, bar:2}, { defineProperty: function(o, v, desc) { def.push(v); Object.defineProperty(o, v, desc); return true; }});
p.foo = 2; p.bar = 4;
return def + '' === "foo,bar";
```

I don't know why this calls into Proxy.[[DefineOwnProperty]] instead of Proxy.[[Set]].
My reading of the spec, is that the `p.foo = 2`, etc, assignments will be evaluated
using PutValue(.). Then, PutValue(.) will call into Proxy.[[Set]]. Is that a correct interpretation?
If I'm totally wrong here, can somebody point out to me why?

**Comment by saambarati** [comment]
The same question can be asked of this test:

```
// [[Set]] -> [[GetOwnProperty]]
var gopd = [];
var p = new Proxy({},
  { getOwnPropertyDescriptor: function(o, v) { gopd.push(v); return Object.getOwnPropertyDescriptor(o, v); }});
p.foo = 1; p.bar = 1;
return gopd + '' === "foo,bar";
```

It looks like these tests assume that `p.foo = 1` goes trough OrdinarySet(.). Is that true?

**Comment by webbedspace** [comment]
> It looks like these tests assume that `p.foo = 1` goes trough OrdinarySet(.). Is that true?

Uh, why do you think it doesn't?

[AssignmentExpression runtime semantics](https://tc39.github.io/ecma262/#sec-assignment-operators-runtime-semantics-evaluation) -> [PutValue](https://tc39.github.io/ecma262/#sec-putvalue) -> [[[Set]]](https://tc39.github.io/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots-set-p-v-receiver) -> [OrdinarySet](https://tc39.github.io/ecma262/#sec-ordinaryset) -> [[GetOwnProperty]] and [CreateDataProperty](https://tc39.github.io/ecma262/#sec-createdataproperty) -> [[DefineOwnProperty]]

**Comment by saambarati** [comment]
Because p is a Proxy and Proxy has its own [[Set]] internal method. Am I missing something?

**Comment by zloirock** [comment]
> Because p is a Proxy and Proxy has its own [[Set]] internal method.

[Steps 6-7.](https://tc39.github.io/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-set-p-v-receiver)

**Comment by Constellation** [comment]
@saambarati:

Ah, yup. `Proxy.[[Set]]` is actually called. But the given proxy does not have any `set(...) { }` handler.
So, as described in 9.5.9-6 and 9.5.9-7, we call `target.[[Set]]`.
`Return ? target.[[Set]](P, V, Receiver).`

And this will call `OrdinarySet`. So the sequence is,

`AssignmentExpression runtime semantics` -> `PutValue` -> `Proxy's [[Set]]` -> `target's [[Set]]` -> `OrdinarySet(target, ...)` -> `[[GetOwnProperty]]` and `CreateDataProperty` -> `[[DefineOwnProperty]]`
