### ISSUE TITLE
"stage 4" Tab

### ISSUE THREAD

**Issue by brianblakely** [compat-table/compat-table#759]
Under the "next" tab, support for completed features is combined with that of proposals and strawmen, but it is a little confusing, and potentially misleading, to put those all together.

It might make sense to have a "stage 4" tab between 6 and next, where support can be measured for fully-qualified, completed features in ES2016/17/18/etc.

**Comment by webbedspace** [comment]
This already exists, but since there are zero stage 4 proposals currently, it is not included in the compiled HTML. Unless you think there should be a vacant row?

**Comment by brianblakely** [comment]
As I understand it, any feature that is completed, and will be included in ES as-is, is technically a "stage 4 proposal."
Semantics aside, the point is that support percentages for finished features should not be lumped in with features of varying stability. As the latter may go away or change radically, it isn't a useful way to track ES in the context of platform support. 

```
_____________________________
```

**Comment by ljharb** [comment]
Publication doesn't matter, so there are still two stage 4 proposals - exponentiation and `Array#includes` - since the stage process started applying post-ES6.

**Comment by webbedspace** [comment]
> Semantics aside, the point is that support percentages for finished features should not be lumped in with features of varying stability.

Alternative idea: maybe the support percentages should be removed from the Next page for a few years. They don't really have much meaning in the context of Next compared to the monolithic ES6 – supporting "100% of ES2016" or "ES2016 + ES2017" doesn't carry much weight when it only comprises two features and half a handful of miscellany (and likely to only increase by two-to-six features per year).

(I vaguely recall suggesting a long time ago that the percentages also be removed from Non-standard, but I never got around to that.)

**Comment by ljharb** [comment]
It might indeed make sense to remove it from Next for the time being.

**Comment by tapsboy** [comment]
Now that ES2016 is approved (http://www.ecma-international.org/ecma-262/7.0/index.html), shouldn't ES7/ES2016 get its own tab? Although the release being so minor, ES7/ES2016 features could also be merged into ES6/ES2015 Tab. That will correctly reflect the ESnext percentages.

**Comment by ljharb** [comment]
(It's not technically approved until tomorrow, despite being published on the ecma website)

**Comment by chicoxyzzy** [comment]
we have ES2016+ tab now
