### ISSUE TITLE
Add `Math.imul`

### ISSUE THREAD

**Issue by redchair123** [compat-table/compat-table#76]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul

**Comment by kangax** [comment]
Already have this

**Comment by redchair123** [comment]
It was raised on August 19 and it appears you pushed it to gh-pages on August 20 with https://github.com/kangax/es5-compat-table/commit/8acf4313c7a267ab12883546f91d941b31fea92e

**Comment by kangax** [comment]
@Niggler heh, ok :)
