### ISSUE TITLE
Feature: Error is subclassable

### ISSUE THREAD

**Issue by rauschma** [compat-table/compat-table#767]
It’d be nice to have an entry for that in the table.

**Comment by webbedspace** [comment]
What exactly does subclassing Error do, though? Error objects don't have exotic behaviour or special internal methods that require its `this` value have a certain internal slot, unlike Map, Set, Promise, RegExp, Array, etc. I quote: _Error instances are ordinary objects that inherit properties from the Error prototype object and have an [[ErrorData]] internal slot [...]. The only specified uses of [[ErrorData]] is to identify Error and NativeError instances as Error objects within Object.prototype.toString._

**Comment by ljharb** [comment]
They have an internal slot, which implementations use for their unspecified `stack` property.

At the least, a proper Error subclass should have `Object.prototype.toString.call` produce `[object Error]` without the use of `Symbol.toStringTag`.
