### ISSUE TITLE
Better Annex B.1.3 (HTML-like Comments) test

### ISSUE THREAD

**Issue by jeisinger** [compat-table/compat-table#768]
I'd argue that features described in Annex B should be green on all browsers by definition. It seems that IE and Edge don't support HTML-style comments in the function constructor which arguably makes sense. An alternative would be to create an iframe with an inline script tag that has HTML comments in it, and check whether the script correctly runs (it could postMessage something back to its opener), or whether a syntax error is thrown (should be visible on the iframe's error handler even if cross origin)

**Comment by ljharb** [comment]
Annex B doesn't mean all browsers have it - it just means enough browsers have it that the legacy behavior is codified.

**Comment by webbedspace** [comment]
"arguably makes sense"? [The spec orders](https://tc39.github.io/ecma262/#sec-html-like-comments) that it should be allowed anywhere ordinary comments are allowed, except in modules. The end.
