### ISSUE TITLE
Array.prototype.sort for ES5 test is wrong

### ISSUE THREAD

**Issue by davityavryan** [compat-table/compat-table#773]
http://kangax.github.io/compat-table/es5/#test-Miscellaneous_Array.prototype.sort:_compareFn_must_be_function_or_undefined

Shouldn't Array.prototype.sort ES5 test be like

```
function () {
    try {
        return [ 2, 1 ].sort(null)[0] === 1;
    } catch (enull) {}
    try {
        return [ 2, 1 ].sort(true)[0] === 1;
    } catch (etrue) {}
    try {
        return [ 2, 1 ].sort({})[0] === 1;
    } catch (eobj) {}
    try {
        return [ 2, 1 ].sort([])[0] === 1;
    } catch (earr) {}
    try {
        return [ 2, 1 ].sort(/a/g);
    } catch (eregex) {}
    try {
        return [ 2, 1 ].sort(function (a, b) { return a > b; })[ 0 ] === 1;
    } catch (efunction) {}
    try {
        return [ 2, 1 ].sort()[0] === 1;
    } catch (eundefined) {}
    return false;
}
```

Note: you had return true on try pass and return false at the end (So that Latest Chrome has considered as non supporting)

**Comment by zloirock** [comment]
Nope. `Array#sort` should allow only functions or `undefined`, it's tested here.

**Comment by ljharb** [comment]
The latest Chrome is indeed violating the spec on `sort`. The bug is that it _doesn't_ throw, and every single test case needs to be checked. In your code, the first example that passes will exit the test early.

**Comment by davityavryan** [comment]
@ljharb so there is a bug for latest Chrome version right? because this URL test shows that my browser (latest Chrome) does not support array sort :/
http://kangax.github.io/compat-table/es5/#test-Miscellaneous_Array.prototype.sort:_compareFn_must_be_function_or_undefined

**Comment by ljharb** [comment]
@idavit yes that's correct. Run http://rawgit.com/es-shims/es5-shim/master/tests/native.html in latest chrome, you'll see 15 failures - 8 of which relate to `Array#sort` non-function non-undefined comparator values.

**Comment by mathiasbynens** [comment]
Note that this test has nothing to do with ES5. #1176
