### ISSUE TITLE
Tail calls elimination available behind a flag in Chrome 51

### ISSUE THREAD

**Issue by cyberixae** [compat-table/compat-table#774]
Chrome status site says tail calls elimination is behind a flag in Chrome 51.
Compat-table does not recognize this. Which one is wrong?

See https://www.chromestatus.com/features/5516876633341952
and https://kangax.github.io/compat-table/es6/#chrome51

**Comment by zloirock** [comment]
Looks like in actual Chrome 51 build it's still not supported with `--harmony` flag.

![default](https://cloud.githubusercontent.com/assets/2213682/14340316/639076b0-fcb0-11e5-828e-3c1d1d34eec1.png)
