### ISSUE TITLE
Unhandled rejections

### ISSUE THREAD

**Issue by chicoxyzzy** [compat-table/compat-table#775]
https://github.com/domenic/unhandled-rejections-browser-spec

Despite the fact that this is mostly [environment-specific feature](https://github.com/whatwg/html/pull/224) it was [landed](https://github.com/tc39/ecma262/pull/76) into [spec](https://tc39.github.io/ecma262/#sec-host-promise-rejection-tracker). Can and should we test it in compat-table?

I can submit PR if it does make sense.

**Comment by ljharb** [comment]
The _hooks_ were landed into the JS spec. There is _no_ defined behavior attached to these hooks in the language itself, and no specification that requires any engine or browser to attach behavior to them.

**Comment by chicoxyzzy** [comment]
Does it mean we still can check if ECMAScript engine provides such hooks (to be compatible with spec)?

**Comment by ljharb** [comment]
It's impossible to determine if the hooks exist until an engine has implemented observable behavior from it.

**Comment by zloirock** [comment]
Duplicate #745.
