### ISSUE TITLE
Simd.js tests for Esnext checks for builtins outside the latest SIMD specification.

### ISSUE THREAD

**Issue by arunetm-zz** [compat-table/compat-table#776]
The Simd.js tests for Esnext comat-table contain the following builtin functions that are not part of the latest SIMD specification (http://tc39.github.io/ecmascript_simd/)
1. SIMD.%type%.selectBits
2. SIMD.%type%.shiftRightLogicalByScalar
3. SIMD.%type%.shiftRightArithmeticByScalar

(2 and 3 are replaced with SIMD.%type%.shiftRightByScalar for Simd int types. )

Can these three functions be removed to be spec compliant?

**Comment by zloirock** [comment]
https://github.com/kangax/compat-table/commit/77089b7f83faa6c4709eb126b94d78a601189548
