### ISSUE TITLE
New Reflect.construct test for promise subclassing appears to be incorrect

### ISSUE THREAD

**Issue by kmiller68** [compat-table/compat-table#791]
The test checks that calling `Promise.prototype.then()` with `this` equal to a `Reflect`-constructed `Promise` object returns an instance of the `Reflect` constructed object. If my reading of the spec is correct, however, since F does not have a `Symbol.species` property the default `Promise` constructor should be used to construct the result.

**Comment by ljharb** [comment]
What is `Reflect.prototype.next`?

**Comment by kmiller68** [comment]
Sorry, that should be Promise.prototype.then. I'll edit the original post.

**Comment by zloirock** [comment]
Agree.
