### ISSUE TITLE
Update es6 result for babel + core-js

### ISSUE THREAD

**Issue by kimyu-ng** [compat-table/compat-table#793]
By running babel `6.8.0` with core-js `2.4.0` is around 83%

**Comment by zloirock** [comment]
Are you sure? :) You should run tests in ES5-only engine like IE9 for correct results.

**Comment by kimyu-ng** [comment]
@zloirock 

I was using 

``` bash
node build.js compilers
```

So, what would be the steps in order for me to accomplish what you have said?

**Comment by zloirock** [comment]
You should build test page as you wrote and after that open it in IE9.
