### ISSUE TITLE
Add support for "unhandledrejection" event under ES6 Promises

### ISSUE THREAD

**Issue by Daniel15** [compat-table/compat-table#796]
Test:

```
'onunhandledrejection' in window
```

References:
https://tc39.github.io/ecma262/2016/#sec-host-promise-rejection-tracker
https://html.spec.whatwg.org/#unhandled-promise-rejections
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunhandledrejection

**Comment by zloirock** [comment]
Duplicate #745, #775.
