### ISSUE TITLE
Android >=5  versioning doesn't make sense

### ISSUE THREAD

**Issue by mgol** [compat-table/compat-table#801]
Android >=4.4 have Google Chrome as their default browser which is auto-updatable as opposed to Android <=4.3. Recording results for the initial state of Google Chrome in Android 4.4.4 still makes sense as that's what its WebView uses and it's not auto-updatable; that's not the case with Android >=5, though.

Because of that, I think showing results for Android 5.0, 5.1 etc is misleading as that's not what people will be using. I think those columns should be removed; if Chrome for Android is expected to be tested, it should be tested as "Chrome on Android", not as a specific Android version. If it matters at all as those results will be identical with Chrome for Desktop.

**Comment by mgol** [comment]
Can I Use does sth similar to what I suggested - it records Androids <=4.4.4 and then Chrome for Android versions; see e.g.:http://caniuse.com/#feat=template (click on "Show all").

**Comment by ljharb** [comment]
The data for specific versions is important - "auto-updatable" doesn't erase a version from existence - there's plenty of reasons something might not auto-update, including "not enough storage space" and "a carrier has disabled it". I'm fine hiding them by default, of course.

**Comment by mgol** [comment]
> there's plenty of reasons something might not auto-update, including "not enough storage space"

This could happen at any point of the ownership of the phone so it doesn't necessarily tie the person to the initial OS state.

The thing is, the chart doesn't show the "Android 5.0" score, it shows the "not updated Chrome from stock Android 5.0" score. It's like there was a table titled "Windows 7" that would show the score of IE8 version that came out together with Windows 7.

**Comment by ljharb** [comment]
That information is still useful to keep, forever, no matter what.

I'm pretty convinced it doesn't need to be shown by default - but we should never be deleting data. Disk space is infinite and free, research is expensive.

**Comment by mgol** [comment]
I'm not advocating for deleting data but for hiding it and renaming to something that doesn't sound misleading.

**Comment by kazazor** [comment]
I have to say that for some time this column was misleading for my team and I. I agree with @mgol that the column should be renamed so it would be clearer to others.

@jrvidal - can you rethink about it?No data of your research would be lost that way, it will just be much clearer to everyone
