### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by kangax** [compat-table/compat-table#802]
Got an email about some suggestions:

A few suggestions for improvements.
- In the header cells for "Chrome 50, 51, 52"  there is "[0]"
  but down below there is no 0 footnote.
  I see some text before the first footnote but it does not have a [0] designation.
- The columns for Chrome 50 and 51 have flags but the column for 52 does not.
  Without knowing what that [0] really refers to, its hard to know if this is a mistake
  or not but it looks suspicious as I see some other footnotes are relevant to flag.
- There is no mention of the JS Module system for ES6.
  ie https://bugs.chromium.org/p/v8/issues/detail?id=1569
  Google is lousy at describing what is in or out of one of their releases.
  That's why I use your tool!
  I've seen others on the web confused by this and 
  even mention that your compatibility table doesn't mention it.
  Even if you don't want to include modules in your table,
  having a note about them would help us as it seems like an odd omission.
- The left most column header for "current browser" should tell
  us what the current browser is, ie "Ch 50"
  The way it is is analogous to you asking someone what
  time it is and they say "now".  True but unhelpful.

**Comment by ljharb** [comment]
To these four points - 1 is clearly a bug, 2 may be related. For 3, ES6 modules simply _don't exist yet_, and absent a loader spec, I don't think we should be mentioning it in the table, even if some browsers implement something via flags. I'd, however, love to see some sort of test that `import`s _something_, just to see that it works absent a loader spec (which it should not).

+1000 for 4, we should have fixed that long ago.

**Comment by webxl** [comment]
I think modules need to be mentioned (even if they cannot yet be tested) because they are part of the es6 spec and the purpose of this table is to inform people on each browser's compatibility. The omission has caused an experienced JS developer like myself to question whether or not they really are part of the spec. I can't imagine what it's like for beginners.

**Comment by ljharb** [comment]
@webxl `import` and `export` syntax, and module parsing semantics, are in the spec. However, you can't actually _test_ those things with what's in the spec - so "mentioning" them is fine, if it's just a banner at the top saying "ES modules do not exist yet".

**Comment by webxl** [comment]
Looks like modules got the go ahead over at #316. I really just had a problem with a "100%" rating implying that the browser has every ES6 feature when there's no way to test for it. Hopefully that addition (and reduction in compatibility) will lead to more and more vendors releasing this as an experimental feature, like the Edge team did.

**Comment by chicoxyzzy** [comment]
Remaining issues splitted into #969 and #316
