### ISSUE TITLE
Add JSC bug

### ISSUE THREAD

**Issue by ljharb** [compat-table/compat-table#812]
Per https://bugs.webkit.org/show_bug.cgi?id=158575 & https://esdiscuss.org/topic/can-strict-parameters-shadow-strict-function-names & http://www.ecma-international.org/ecma-262/5.1/#sec-13.1

Specifically, `var foo = function bar(bar) {'use strict'};` should not give a `SyntaxError`. This is likely fixed in the latest Webkit Nightly but it should be indicated as failing in all previous JSC/Safari/Webkit versions.

**Comment by kangax** [comment]
Good idea, I was thinking the same after seeing the thread.
