### ISSUE TITLE
ES2016 / ES7 tab

### ISSUE THREAD

**Issue by chicoxyzzy** [compat-table/compat-table#822]
ES2016 was released recently. Do we need to add new tab and remove ES2016 features from `next` tab?

**Comment by ljharb** [comment]
Each year from 2016 on is going to be relatively small - in N years we'd end up with N more tabs. Perhaps we should have one tab for "stage 4 things" - which would now contain ES2016 (+ misc), and ES2017 (+ misc), and then another for "proposals" with everything else?

**Comment by chicoxyzzy** [comment]
> stage 4 things

IMO "Post-Harmony" sounds better

**Comment by ljharb** [comment]
Technically proposals are post-Harmony too. That name isn't particularly meaningful.

**Comment by chicoxyzzy** [comment]
According to [TC39 Process](https://tc39.github.io/process-document/) ES2016 features are not technically "stage 4 things" as well

**Comment by ljharb** [comment]
@chicoxyzzy that document does not in any way speak to ES2016 features, nor does it say that a feature leaves stage 4 when it is included in a standard revision. Regardless, the term "stage 4 things" was meant to be a broad term to describe, in general terms, finished features.

**Comment by chicoxyzzy** [comment]
I think we can close this because of #827
