### ISSUE TITLE
Use new ECMAScript spec website?

### ISSUE THREAD

**Issue by impressivewebs** [compat-table/compat-table#828]
Do you think it would be beneficial to use the new ECMA spec for the links in your compat tables?

https://tc39.github.io/ecma262/

For example, instead of:

http://www.ecma-international.org/ecma-262/6.0/#sec-generator-function-definitions

You can link to:

https://tc39.github.io/ecma262/#sec-generator-function-definitions

Etc...

Just a thought since the new ECMA spec is much easier to search/navigate/use.

**Comment by ljharb** [comment]
The new one should be linked somewhere prominent (since it's a living spec), but the snapshots on ecma-international.org are both important, and the thing that the tables generally match against.

**Comment by chicoxyzzy** [comment]
This also means we should update `2016+` tab using snapshots of 2016 and 2017 spec

**Comment by bterlson** [comment]
ES2016 is snapshotted here: https://github.com/tc39/ecma262/2016.

**Comment by chicoxyzzy** [comment]
Does it have any differences with www.ecma-international.org/ecma-262/7.0/ ?

**Comment by chicoxyzzy** [comment]
I think we reached a consensus here. We'll use snapshots. So I'll close this issue. Please feel free to re-open it if you think we missed something.

**Comment by bterlson** [comment]
@chicoxyzzy No difference.
