### ISSUE TITLE
Firefox 48 is out, and has better compatibility than reported

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#856]
Firefox 48 is out today, and my tests on Win7 show better compatibility on ECMA6 (91% on mine vs 89% on "FF48") and ECMA2016 (45% on mine vs 39% on "FF48") than reported on the results table.  The current build of FF49 (49.0a2 from 2016-08-01) also has better results on ECMA2016 (47% on mine vs 41% on "FF49") than reported on the results table.
Maybe a rerun of the tests on FF48, FF49 and FF50 (when available) is necessary.

**Comment by zloirock** [comment]
Feel free to add a PR. I added those results in March.

**Comment by afmenez** [comment]
I updated the data tables and rebuild the HTMLs for FF48 and FF49 locally, but github says I am not allowed to push my changes.  How do I proceed?

**Comment by zloirock** [comment]
@afmenez fork and pull request.

**Comment by afmenez** [comment]
My patch contains more than was done in #859:
- Updated FF47 and FF48 status on esnext-browsers.js;
- Added FF50;

I still can't push my changes, how do I get permission to push a new branch?

On a side note, there are currently 16 versions of Firefox and 14 versions of Chrome, how does a version change from obsolete:true to obsolete:very?

**Comment by zloirock** [comment]
One more time: you should fork this repo, create a branch for changes and create a pull request from `afmenez/your-branch-name` to `kangax/gh-pages`. It's not requires any permission.

**Comment by chicoxyzzy** [comment]
@afmenez here is an [article](https://help.github.com/articles/fork-a-repo/) about how to fork repo, keep it in sync with upstream and open Pull Requests

**Comment by afmenez** [comment]
OK @zloirock, #860 is ready for review.

Hey @chicoxyzzy, thanks a lot for the help, this was actually my first Pull Request.
