### ISSUE TITLE
Remove testing on node v0.10.46 on Travis CI

### ISSUE THREAD

**Issue by chicoxyzzy** [compat-table/compat-table#893]
I think we should deprecate node v0.10.46 because it's not supported anymore.

**Comment by ljharb** [comment]
Nothing's really being tested on node 0.10 right now - there's two test jobs; one runs the linter, and one ensures `npm run build` has been ran. We could replace `0.10` with literally anything that resolved to a different version of node and it would be identical.

**Comment by chicoxyzzy** [comment]
There are some warnings from dependencies so I thought it's a good time to update node.js

https://travis-ci.org/kangax/compat-table/jobs/156353682#L145
https://travis-ci.org/kangax/compat-table/jobs/156353682#L176

**Comment by ljharb** [comment]
Fair point - I'll update it.
