### ISSUE TITLE
esintl tests for outdated behavior

### ISSUE THREAD

**Issue by vanwagonet** [compat-table/compat-table#900]
[test262](https://github.com/tc39/test262/blob/master/test/intl402/Collator/10.1.1_1.js) and the v2 & v3 spec call for always returning a new intl object from an intl constructor call, instead of throwing when a prior intl object is passed as `this`.

`calling Collator with Collator instance throws error` is no longer correct behavior.

The same applies to `NumberFormat` and `DateTimeFormat`.

**Comment by chicoxyzzy** [comment]
Duplicate of #467
