### ISSUE TITLE
Update Node 6 results.

### ISSUE THREAD

**Issue by jpickwell** [compat-table/compat-table#901]
According to http://node.green/ Node.js 6.5.0 has the following percentages:
- ES2015 (ES6): 99% (99% w/ flags)
- ES2016: 76% (100% w/ flags)
- ES2017: 33% (41% w/ flags)

The following are supported through a flag:
- ES6: tail call optimization
- 2016: exponentiation operator
- 2017: Object.values
- 2017: Object.entries
- 2017: Object.getOwnPropertyDescriptors (basic support)

It would also be nice if the tooltip for Node 6 indicated which version because there's a difference in the level of support between 6.4.0 and 6.5.0.

**Comment by chicoxyzzy** [comment]
PRs are always welcome =)

**Comment by mgol** [comment]
PR: #913

**Comment by chicoxyzzy** [comment]
@mgol thank you! Let's move discussion there
