### ISSUE TITLE
Maintaining the repo and future plans

### ISSUE THREAD

**Issue by chicoxyzzy** [compat-table/compat-table#903]
I've found that current maintainers don't always have enough time to review PRs and manage issues (some of which can be closed and some need update). So I thought that it'll be better for this repo to add more active collaborators.

Besides that, Babel team have a plan to use some kind of browsers compatibility info. That was discussed [before](https://github.com/kangax/compat-table/issues/785) and there is even [PR](https://github.com/kangax/compat-table/pull/896) which might be a good start but it will get outdated after most of merged PRs. So we need a plan how we can switch to raw data (if we want to have it). I think this is a great direction.

We can improve the whole architecture to introduce some new cool features (https://github.com/kangax/compat-table/issues/779, https://github.com/kangax/compat-table/issues/771, etc) and improve performance.

Also we need to realise if and how we can use https://github.com/tc39/test262 here.

What do you think about these thoughts? @kangax @zloirock @ljharb @webbedspace

**Comment by ljharb** [comment]
All good thoughts - i don't think the commit bit will make a difference here wrt getting the larger and more complex things done any quicker, however.

**Comment by kangax** [comment]
@chicoxyzzy great points, I'd love to have more contributions. I don't have time for compat-table anymore as I'm focusing on Babel and Babili (babel minifier) at the moment. So the show is run by always-excellent @zloirock @ljharb and @webbedspace. I can add you to the repo if everyone else agrees.

**Comment by chicoxyzzy** [comment]
As addition to first point we can create issues with description whats wrong and how to fix it and `Good first bug` label on it for things like https://github.com/kangax/compat-table/issues/906 to engage people in contributing. We also can have a twitter account where we can tweet about searching contributors with these bugs attached and about notable changes also.

**Comment by chicoxyzzy** [comment]
I just started cleaning up issues here. So I'll possibly create separate issue for some points after that
