### ISSUE TITLE
property order of Object.keys is not hard requirement

### ISSUE THREAD

**Issue by shvaikalesh** [compat-table/compat-table#912]
Same goes for `JSON` methods. They call [EnumerableOwnProperties](https://tc39.github.io/ecma262/#sec-enumerableownproperties), thus key order is implementation-dependent (see step 5). Order was left as-is for backwards compatibility reasons.

**Comment by bterlson** [comment]
An object's own keys do have a defined ordering now. The implementation-definededness only comes into play when there are prototype properties involved.

**Comment by shvaikalesh** [comment]
That is awesome, thanks for clarification. Could you please explain the purpose of note in step 5?

**Comment by chicoxyzzy** [comment]
> An object's own keys do have a defined ordering now

Since ES6 right? Because the test is in ES6 tab

**Comment by bterlson** [comment]
@chicoxyzzy good point, I'm not sure off hand, and will have to double-check when the last changes landed. I will attempt to do this tomorrow

@shvaikalesh which note? Can you quote it?

**Comment by shvaikalesh** [comment]
@bterlson sure:

> Order the elements of properties so they are in the same relative order as would be produced by the Iterator that would be returned if the EnumerateObjectProperties internal method was invoked with O.

**Comment by ljharb** [comment]
My understanding is yes, since ES6 - in ES5, it was basically pegged to `for..in`, but in ES6, it's deterministic.

**Comment by chicoxyzzy** [comment]
Can we can close this?

**Comment by temporaryrespite** [comment]
If you compile Firefox ([since 2012](https://bugzilla.mozilla.org/show_bug.cgi?id=707017#c20)) with `ac_add_options --enable-more-deterministic` in `mozconfig` file, then you get predefined/sorted order, and [thus](https://kangax.github.io/compat-table/es6/) these will fail:
```
Proxy, internal 'get' calls:
 Object.assign
 Object.defineProperties

Proxy, internal 'set' calls:
 Object.assign

Proxy, internal 'defineProperty' calls:
 SetIntegrityLevel

Proxy, internal 'getOwnPropertyDescriptor' calls:
 Object.assign

own property order:
 Object.getOwnPropertyNames
 Object.assign
 JSON.stringify
 JSON.parse
 Reflect.ownKeys, string key order
 Reflect.ownKeys, symbol key order
```

because [ie.](https://hg.mozilla.org/mozilla-central/rev/d87f60b6c99d#l1.77)
```c
 
+#ifdef JS_MORE_DETERMINISTIC
+
+    /*
+     * In some cases the enumeration order for an object depends on the
+     * execution mode (interpreter vs. JIT), especially for native objects
+     * with a class enumerate hook (where resolving a property changes the
+     * resulting enumeration order). These aren't really bugs, but the
+     * differences can change the generated output and confuse correctness
+     * fuzzers, so we sort the ids if such a fuzzer is running.
+     *
+     * We don't do this in the general case because (a) doing so is slow,
+     * and (b) it also breaks the web, which expects enumeration order to
+     * follow the order in which properties are added, in certain cases.
+     * Since ECMA does not specify an enumeration order for objects, both
+     * behaviors are technically correct to do.
+     */
```

found out the hard way: https://bugs.gentoo.org/717374

**Comment by ljharb** [comment]
Seems like a really bad idea to compile a browser with most flags enabled, since that’s not what the web does.
