### ISSUE TITLE
INTL table missing the proposed features for ECMA402

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#930]
We have a table showing proposals for future versions of ECMAscript, but we have nothing about the proposed features for the internationalization API:
https://github.com/tc39/ecma402

**Comment by afmenez** [comment]
The table could also be split by version, like the ES2016+ tab.  I believe currently there are 3 specifications:
[ECMAScript Internationalization APIs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Specifications)

**Comment by chicoxyzzy** [comment]
Duplicate of #467
