### ISSUE TITLE
Some proposal updates

### ISSUE THREAD

**Issue by hzoo** [compat-table/compat-table#931]
- object rest/spread from stage 2 to stage 3
- async iteration from stage 2 to stage 3
- System.global from stage 2 to stage 3 (-> global)
- string trimming is already in 2017 but its also included in stage 1 still

**Comment by Constellation** [comment]
Is there any pointer to the change that string trimming becomes ES2017?

**Comment by ljharb** [comment]
Whoops, you're right - string trimming is only stage 2. https://github.com/rwaldron/tc39-notes/blob/d0c651b358b361b0855cfe7af9ba0b76cab73949/es7/2016-07/jul-27.md#10iic-trimstarttrimend Fixed in 7914694d3429155b89cbd36dbcc762ccc0352bbb

@hzoo heads up on string trimming being stage 2, not 4.

**Comment by Constellation** [comment]
@ljharb Thanks :)

**Comment by hzoo** [comment]
Ohh I totally misread https://github.com/tc39/proposals/blob/master/finished-proposals.md - string padding not trimming (of course)
