### ISSUE TITLE
No tests for ArrayBuffer.transfer "strawman"

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#940]
There is no test for the ArrayBuffer.transfer "strawman" specification, which is already implemented on Firefox Nightly since FF36.
https://gist.github.com/lukewagner/2735af7eea411e18cf20

**Comment by ljharb** [comment]
This proposal was withdrawn in the September TC39 meeting, and will soon be removed from Firefox. I removed it in fa5b98ac90a6ad4444140b4b5150a564717c2d9e.
