### ISSUE TITLE
Split ES2016 and ES2017 in their own tabs

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#945]
Shouldn't ES2016 and ES2017 each have it's own tab?  It would make it easier to visualize that some implementations are already 100% ES2016 compliant (like Chrome 56, Firefox 52 and Safari TP).  Node 6.5 is also almost fully ES2016 compliant but shows only 32% because it has no ES2017 features yet.

**Comment by ljharb** [comment]
That would make for an explosion of tabs as a new one will come out every year, and it would continue to promote the idea that the year of publication matters – when in fact, the only thing that matters is "stage 4", and being in the master branch on github.

**Comment by chicoxyzzy** [comment]
I think we should concentrate on tests and browsers (and other environments) data first so we can improve UI easily later and make it possible for other tools to use our data
