### ISSUE TITLE
Mark Opera 12 as obsolote?

### ISSUE THREAD

**Issue by chicoxyzzy** [compat-table/compat-table#947]
Twitter discussion with Vadim Makeev, Opera Software evangelist

https://twitter.com/chicoxyzzy/status/793049618686808064

On the other hand the intent of people may be to see historically-related data. In that case it does make sense to have Opera 12 in ES5 tab. But it's weird that other browsers doesn't show historically-related data. So making Opera 12 obsolete seems reasonable.

**Comment by chicoxyzzy** [comment]
I have a branch in my fork already but I want to be sure we want this before I'll create PR

https://github.com/kangax/compat-table/compare/gh-pages...chicoxyzzy:opera12_obsolete?expand=1

**Comment by afmenez** [comment]
I agree, it is obsolete and should be marked as such.  It will still be available for comparison if the user wants it.

**Comment by chicoxyzzy** [comment]
Yes I think so too. We can hide Opera 12 under `obsolete: true` flag. Also ideally we should mark browsers by `obsolete: 'very'` only for those of them which was stable right before particalar specification was released.
