### ISSUE TITLE
traceur and Map, Set, WeakMap

### ISSUE THREAD

**Issue by Yaffle** [compat-table/compat-table#96]

**Comment by kangax** [comment]
what about it?

**Comment by Yaffle** [comment]
I think, Traceur does not provide Map, Set and WeakMap support

**Comment by kangax** [comment]
@arv could you shed some light on this?

**Comment by arv** [comment]
Traceur does not provide any of these. Traceur is mostly focusing on new syntax and semantics and not polyfills. Existing polyfills ashtray work great with Traceur. No need to duplicate them.

**Comment by Yaffle** [comment]
@arv, but existing polyfills for Map and Set can not provide O(1) performance for object as keys, seems

**Comment by arv** [comment]
If you can mutate object keys you can get O(1) which is the standard solution.

**Comment by Yaffle** [comment]
@arv, ok, what about WeakMap ?

**Comment by arv** [comment]
Where did that "ashtray" come from? Stupid Android auto complete!

@Yaffle WeakMaps cannot be fully emulated. The closest thing is to store the association as an expando on the key itself. Once again this require extensible keys.

Here is one:

https://github.com/Polymer/WeakMap

This is not complete but it is very small and it has been highly optimized for speed.

**Comment by Yaffle** [comment]
anyway, 
Map, Set, WeakMap should be setted as not supported for "Traceur" column
