### ISSUE TITLE
Broken css - Overflowing thead

### ISSUE THREAD

**Issue by katsos** [compat-table/compat-table#967]
Selecting ecmascript 5 I get the result below.
<img width="1680" alt="screen shot 2016-11-22 at 1 18 03 pm" src="https://cloud.githubusercontent.com/assets/9785225/20521928/4ac1dd9e-b0b6-11e6-95e8-b2f41eff45a3.png">

I'm using 
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2926.0 Safari/537.36

JavaScript: V8 5.6.326
Flash: 24.0.0.154

**Comment by chicoxyzzy** [comment]
Yes, this is an old issue 😞 
Contributions are very welcome!

**Comment by chicoxyzzy** [comment]
related issue #751

**Comment by mkoryak** [comment]
I'll take a look when I get to a computer

**Comment by mkoryak** [comment]
There is a slight misalignment here, not sure yet what is causing it. Here is the weirdness:

```js
const orig = Array.prototype.slice.call(document.querySelector('#table-wrapper thead tr').children).map(el => el.clientWidth);

const float = Array.prototype.slice.call(document.querySelector('.floatThead-table thead tr').children).map(el => el.clientWidth).filter(Number)
```

and

```
float
[361, 61, 11, 46, 50, 46, 46, 46, 46, 46, 46, 55, 56, 61, 61, 61, 61, 46, 46, 46, 46, 52, 46, 46, 46, 46, 46, 46, 46]

orig
[360, 60, 11, 46, 50, 46, 46, 46, 46, 46, 46, 55, 56, 61, 61, 61, 61, 46, 46, 46, 46, 52, 46, 46, 46, 46, 46, 46, 46]
```

**Comment by mkoryak** [comment]
i also see this error on the console:

> For elements with box-sizing: border-box, only absolute content area dimensions can be applied

but I don't know what element is doing it. I assume this page wasn't always broken and some css changes caused this?

**Comment by Trias** [comment]
I've made a fix for this issue, see here: https://trias.github.io/compat-table/es6/

* chrome's implementation of position:sticky appparently is broken so i've made it use the fallback version
* updated the jquery.thead,js dependency (does not appear to solve the relevant issue here)

tell me if you like to merge this fix

**Comment by chicoxyzzy** [comment]
It works like charm in Chrome now! Not sure if something changed in FF, Edge or Safari but I think we should accept the changes! cc @zloirock @ljharb

**Comment by ljharb** [comment]
@Trias would you mind making a PR, so we can evaluate it?

**Comment by ljharb** [comment]
Oops, nvm, I see #984
