### ISSUE TITLE
Link to developer.mozilla.org for the feature

### ISSUE THREAD

**Issue by quangkieu** [compat-table/compat-table#973]
As developer.mozilla.org usually have some additional information, usage, paremeter and polifill sample for the missing feature

**Comment by chicoxyzzy** [comment]
Personally I don't consider MDN as a source of truth but it might be useful

**Comment by ljharb** [comment]
MDN is probably the second-best site to link to besides the spec itself.

Note that none of the polyfills on MDN should be used in production; they're there for instructional purposes. Use a package on npm if you want a polyfill.

**Comment by kangax** [comment]
I also wanted this back in the days. MDN is great for simple explanation, examples, etc. +1 from me.

**Comment by sarahkadar** [comment]
I've started working on this.

**Comment by sarahkadar** [comment]
So it looks like this right now: 
<img width="361" alt="screenshot 2017-03-29 14 11 41" src="https://cloud.githubusercontent.com/assets/48946/24453824/bff3714a-1489-11e7-933e-6a8a63d84f7c.png">

For starters, I've added an `mdn` property to each test for ES6, and a few for some of the subtests. Changed `build.js` so it add them as `(mdn)`. Looks kinda ugly tbh but functional?

Is this the right direction? Let me know if I should invest more time in this.

You can find the code [here](https://github.com/KTamas/compat-table/tree/mdn).

**Comment by chicoxyzzy** [comment]
@KTamas this looks great! Can we use MDN logo instead of text?

**Comment by sarahkadar** [comment]
@chicoxyzzy I'm all for it, as long as Mozilla has no issue with that

**Comment by sarahkadar** [comment]
@chicoxyzzy es5, es6, 2016+, next is done. intl is under construction (right?), is there a point of doing non-standard?

**Comment by sarahkadar** [comment]
I looked up mozilla trademark policies and there is nothing on the MDN logo specifically, unfortunately

edit: nvm see pull req

**Comment by ljharb** [comment]
Closed in #1063.
