### ISSUE TITLE
Add Edge 15 Insider Preview

### ISSUE THREAD

**Issue by chicoxyzzy** [compat-table/compat-table#980]
I am trying to get Edge 15 in VM on my mac, but that doesn't work for some reason.

https://twitter.com/chicoxyzzy/status/806841888217120769

Can anyone help with testing Edge 15 and adding it's results to repo?

**Comment by jdalton** [comment]
You can check out the [Windows Insider](https://insider.windows.com/) page to get the [Windows Insider Preview iso](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso).

**Comment by jdalton** [comment]
Erm the [Windows Insider Preview iso](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso).

**Comment by chicoxyzzy** [comment]
@jdalton thank you! Downloading it now.

BTW is it a bug that VM from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ includes wrong version? Should I report it somewhere?

**Comment by jdalton** [comment]
I'm guessing VMs there are for stable releases. Insider builds are preview releases.

**Comment by chicoxyzzy** [comment]
But there is Microsoft Edge on Win 10 Preview (15.14959) in a list

**Comment by jdalton** [comment]
Ah, prolly a bug then. \cc @dstorey

**Comment by jdalton** [comment]
\cc @dstorey

**Comment by Chudesnov** [comment]
Btw, @jdalton, maybe you could point us to a place to file issues about the Insider program. Kangax repo seems a bit strange for such discussion.

For example, I cannot download the ISO from the page you're linking to (says I need to become an Insider, although I already am).

**Comment by jdalton** [comment]
Try [this](https://twitter.com/nolanlawson/status/763807113105723392).

**Comment by Chudesnov** [comment]
Wow, that's great! Definitely gonna use the hashtag if I find anything worth fixing.

But I guess this only works for the Windows web platform, not the Insider / Update infrastructure. Any ideas on how we could reach out to these folks?

**Comment by chicoxyzzy** [comment]
I'll close this issue because it was (partially) resolved by #981

(There should be [new results for 15.14986](https://twitter.com/MSEdgeDev/status/806641150186528768) but my Insider Windows doesn't get updates being logged in as insider and having Insider Level "Fast" so I added 15.14965 which I was able to test)
