### ISSUE TITLE
Add ES6 -> String.prototype.repeat support to IE11

### ISSUE THREAD

**Issue by jquintozamora** [compat-table/compat-table#982]
Hi,
I have tested String.prototype.repeat on IE11 (version 11.447.14393.0) and it worked for me.

Cheers!

**Comment by Chudesnov** [comment]
Sorry, but I'm trying to confirm this using the latest build for Fast Ring (11.1000.14986) and String.prototype.repeat evaluates to undefined. Are you sure you've tested the native engine's object without any polyfills?

**Comment by chicoxyzzy** [comment]
It's not available on my IE 11.1001.14965.0 as well

**Comment by jquintozamora** [comment]
It is weird... Probably it worth to investigate little bit more, this is my environment.

Probably the fact, I have installed IE Edge as well have something to do... I will try to test in other env as well. 

![image](https://cloud.githubusercontent.com/assets/12530031/21081368/e1d43ad2-bfbc-11e6-896d-1d00963982b6.png)

**Comment by paulsonnenschein** [comment]
@jquintozamora Thats because you are testing this on google.com. They probably use a polyfill. If you go to about:blank you will _hopefully_ get `undefined`

**Comment by Chudesnov** [comment]
@jquintozamora the fact that you see some minified code between the curly braces instead of the `[native code]` placeholder should be enough to say that this is not a browser feature.

It's sad, but IE's not getting any ES2010s stuff anytime soon (or ever).

**Comment by jquintozamora** [comment]
Hi @Chudesnov  and @cookiecavekeeper, you are right. I didn´t realise about the polyfill, but it is because using about:blank I got undefined as well.

Thanks!
