### ISSUE TITLE
Safari 7 missing from tables

### ISSUE THREAD

**Issue by keithamus** [compat-table/compat-table#99]
OSX Mavericks features Safari 7, which should be included in the ES5/6 tables

![safari 7 about window](https://f.cloud.github.com/assets/118266/1748849/bd734f0c-64e3-11e3-8bd1-df7af0821a29.PNG)

**Comment by keithamus** [comment]
It seems Safari 7 has pretty much the same feature set for ES5/6 as Safari 6. See:

![screen shot 2013-12-14 at 17 20 18](https://f.cloud.github.com/assets/118266/1748856/2c648674-64e4-11e3-962a-a7f3e57c17a2.PNG)
![screen shot 2013-12-14 at 17 20 51](https://f.cloud.github.com/assets/118266/1748857/2f18e144-64e4-11e3-886b-735ca70dc7f8.PNG)
![screen shot 2013-12-14 at 17 21 51](https://f.cloud.github.com/assets/118266/1748859/5a6c19ce-64e4-11e3-8379-6bf55581f625.PNG)

**Comment by kangax** [comment]
Thanks, I'm on Mavericks myself and been forgetting to add it. Done.
